### ISSUE TITLE
key controls no longer work after EOF

### ISSUE THREAD

**Issue by samushighwind** [huceke/omxplayer#10]
It seems that once the whole file has ended buffering, I can no longer pause/rw/ffw/etc.  A fix would be super appreciated!

Ben

**Comment by XavM** [comment]
+1

I guess it has to be around line 710 in omxplayer.cpp where if EOF we get out of the loop waiting for key press : 

   if(m_omx_reader.IsEof())
        break;

**Comment by samushighwind** [comment]
That makes sense.. is there another sort of qualifier available that could be alternatively used to indicate end of playback?

**Comment by XavM** [comment]
Hi dear OMXPlayer Team,

This is clearly an uneducated hack, but changing omxplayer.ccp line 712 would do the trick.

before :
     if(m_omx_reader.IsEof())
after :
     if(m_omx_reader.IsEof() && m_player_audio.GetCached() == 0 && m_player_video.GetCached() == 0)

Would you mind give your advise and fixe this little annoying bug.

Regards

**Comment by popcornmix** [comment]
This is fixed.
