### ISSUE TITLE
HTTP authentication

### ISSUE THREAD

**Issue by vpetersson** [huceke/omxplayer#100]
First, let me say thanks for a great tool.

I'm the creator of [Screenly](https://github.com/wireload/screenly-ose), a digital signage player for the Raspberry Pi. Thanks to omxplayer, it was trivial to add support for video playback.

One request we've received from a few users however is the ability to stream content from password protected http/https resource. 

I know mplayer supports this, and I was just curious if this is something you'd be interested in adding. I do realize this is somewhat of a niche feature, but I just wanted to reach out and check.

(This is discussed in Screenly ticket [#19](https://github.com/wireload/screenly-ose/issues/19).)

**Comment by matiaspl** [comment]
If it's not working already this could be easily implemented, as ffmpeg supports it.

**Comment by popcornmix** [comment]
What does the command line to play one of the streams (from mplayer or ffmpeg) look like?

**Comment by vpetersson** [comment]
> What does the command line to play one of the streams (from mplayer or ffmpeg) look like? 

```
$ mplayer [...] −user <username> −passwd <password> [...]
```

(from [man](http://www.mplayerhq.hu/DOCS/man/en/mplayer.1.html))

**Comment by popcornmix** [comment]
How about ffmpeg?
I really want to know if these just form part of the URL (e.g. http://username:password@foobar.com)
or whether there are any libffmpeg/libavcodec functions to configure this.

**Comment by vpetersson** [comment]
Yes, it appears as it has been supported in ffmpeg since 0.6.3 [1][2].

I cannot find any references to any username or password flags, so I assume that means that the standardized syntax http://username:password@domain.com is used. 
- 1 [StackOverflow](http://stackoverflow.com/questions/5014973/does-ffmpeg-support-rtsp-authentication)
- 2 [Changelog](http://www.ffmpeg.org/releases/ffmpeg-0.6.3.changelog)

**Comment by popcornmix** [comment]
Can you find an address where http://username:password@domain.com works on ffmpeg.
Can you try the same address on omxplayer?

**Comment by vpetersson** [comment]
Sorry for the late response.  However, here are my findings.

As for mplayer, I can confirm that both of the following commands work:

```
$ mplayer http://foobar:foobar@example/test.mp4
$ mplayer  -user foobar -passwd foobar http://example/test.mp4
```

I can also confirm that ffmpeg works with the following command (or in this case, ffprobe):

```
$ ffprobe http://foobar:foobar@example/test.mp4
```

**Comment by popcornmix** [comment]
Does anyone have a real url like http://foobar:foobar@example/test.mp4 I can use to test?

**Comment by skgsergio** [comment]
I've created a test, works with mplayer and vlc but can't test it on omxplayer due I don't have my Raspberry Pi now with me:

http://test:test@omxplayer.sconde.net/test/big_buck_bunny_480p_h264.mov

**Comment by popcornmix** [comment]
@ skgsergio thanks.
It plays fine!
(and if username or password is wrong it doesn't play as expected).

**Comment by skgsergio** [comment]
As I thougth :) due omxplayer is using ffmepg.

@vpetersson works for you?

**Comment by vpetersson** [comment]
Yep, works fine. Thanks guys. I should have tested this before escalating it.
Maybe we should add a note in the docs about this newly found support :)
