### ISSUE TITLE
Overscan & framebuffer problems

### ISSUE THREAD

**Issue by gyeben** [huceke/omxplayer#103]
I have connected my Raspberry Pi to my old CRT TV via RCA, and I have edited /boot/config.txt to make the text and graphics not to spill of the "viewable area" of my screen. But when I play a video using omxplayer, it doesn't seem to check the overscan and framebuffer settings, and as a result, the video spills of my screen way too much.
Can this be fixed?

Thanks for your help and your hard work.

EDIT: my framebuffer is set to 640x480, and my overscan settings are the following:
overscan_left=16
overscan_right=16
overscan_top=-16
overscan_bottom=-16

**Comment by popcornmix** [comment]
You can add (to config.txt):
overscan_scale=1
