### ISSUE TITLE
Sound but no picture

### ISSUE THREAD

**Issue by Vulcan1** [huceke/omxplayer#105]
Have latest version installed (0.2.4~git20130124~2051027b) on standard Wheezy install attached via HDMI to TV. On playback of an avi can only get sound, no video.

Have also installed tboplayer gui. This plays sound and video!

So would like help getting command line version working correctly.

Any help/advice would be appreciated.

**Comment by popcornmix** [comment]
The same video file plays on tboplayer but not on omxplayer?

What gpu_mem setting do you have in config.txt? Can you try increasing it?

**Comment by Vulcan1** [comment]
It's set at 128. I've tried 64 and 192 with the same result.

**Comment by popcornmix** [comment]
What is mediainfo of file?
What is in omxplayer.log?

**Comment by KenT2** [comment]
Weird, TBOPlayer just calls omxplayer through Pexpect

TBO Player sends 

/usr/bin/omxplayer -s

instead of omxplayer so you may be using a different version of omxplayer if you have installed your own.

**Comment by Vulcan1** [comment]
It is weird. I'm using the latest build available on GitHub, details as per my first post. Should I be using another?

**Comment by popcornmix** [comment]
What happens if you directly run:
`/usr/bin/omxplayer <filename>`

**Comment by Vulcan1** [comment]
Okay, this is strange!

If I come out of X (ctrl+alt+F1) and go to a command line the following happens;

If I type omxplayer <filename> I get a black/blank screen with flashing cursor top left and sound

If I type /usr/bin/omxplayer <filename> I get perfect video/picture but no sound, 

and if I type  /usr/bin/omxplayer -o hdmi <filename> I get perfect video/picture and sound

I'm confused as I thought 'omxplayer' should do the same as '/usr/bin/omxplayer'.

**Comment by popcornmix** [comment]
Well, /usr/bin/omxplayer is an older version. You can either checkout an older version of omxplayer from git, and find the commit that breaks your file and let me know.
Or produce a sample of your failing file (e.g. 100MB) and post it somewhere (e.g. dropbox).

**Comment by skgsergio** [comment]
May I suggest running `which omxplayer` and see if there is another omxplayer rather than /usr/bin/omxplayer?

It's weird because it's using my package (as I see in the version number he pasted) and my package installs omxplayer into /usr/bin/omxplayer...

**Comment by Vulcan1** [comment]
Thanks Sergio, you've cracked it. 'which omxplayer' found it in /usr/lib/bin. I've deleted omxplayer from that directory and now it's using the version in /usr/bin without any issues.

Thanks to all that contributed.

**Comment by JamesHagerman** [comment]
Is anyone working through these issues? Shouldn't this be closed?
