### ISSUE TITLE
Audio popping

### ISSUE THREAD

**Issue by JorgeCarranco-GMG** [huceke/omxplayer#106]
Audio pops at beginning and end of videos playing out of the analog port of raspberry pi.  No popping playing out of HDMI.

**Comment by ghost** [comment]
This isn't just an issue with omxplayer I guess. I've noticed the same using mplayer. When analog audio starts, even at low volume, an annoying pop sounds. Also when audio is stopped. 

Looks like a firmware issue: https://github.com/raspberrypi/linux/issues/128

**Comment by Scubafloyd** [comment]
But there are no problems with MOC (console audio player), for example. 

The problem seems related to how omxplayer is handling the snd_bcm2835 audio device.

The first post of this thread might also describe the problem in more detail:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=38&t=30669

**Comment by popcornmix** [comment]
This should be fixed with latest firmware. Please reopen if a problem.
