### ISSUE TITLE
Error when compile on the Pi

### ISSUE THREAD

**Issue by adks3489** [huceke/omxplayer#107]
Hi, I am compile on the Pi.
After I type make, there is a Error about RBP

---

In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:50:74: error: ‘TV_SUPPORTED_MODE_NEW_T’ has not been declared
./DllBCM.h:54:45: error: ‘HDMI_PROPERTY_PARAM_T’ does not name a type
./DllBCM.h:54:68: error: ISO C++ forbids declaration of ‘property’ with no type [-fpermissive]
./DllBCM.h:55:39: error: ‘TV_DISPLAY_STATE_T’ has not been declared
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:89:74: error: ‘TV_SUPPORTED_MODE_NEW_T’ has not been declared
./DllBCM.h:95:45: error: ‘HDMI_PROPERTY_PARAM_T’ does not name a type
./DllBCM.h:95:68: error: ISO C++ forbids declaration of ‘property’ with no type [-fpermissive]
./DllBCM.h:97:39: error: ‘TV_DISPLAY_STATE_T’ has not been declared
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_get_supported_modes_new(HDMI_RES_GROUP_T, int_, uint32_t, HDMI_RES_GROUP_T_, uint32_t_)’:
./DllBCM.h:92:14: error: ‘::vc_tv_hdmi_get_supported_modes_new’ has not been declared
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_power_on_explicit_new(HDMI_MODE_T, HDMI_RES_GROUP_T, uint32_t)’:
./DllBCM.h:94:14: error: ‘::vc_tv_hdmi_power_on_explicit_new’ has not been declared
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_set_property(const int_)’:
./DllBCM.h:96:48: error: invalid conversion from ‘const int_’ to ‘uint32_t {aka unsigned int}’ [-fpermissive]
./DllBCM.h:96:48: error: too few arguments to function ‘int vc_tv_hdmi_set_property(uint32_t, uint32_t, uint32_t)’
/opt/vc/include/interface/vmcs_host/vc_tvservice.h:465:22: note: declared here
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_get_display_state(int_)’:
./DllBCM.h:98:14: error: ‘::vc_tv_get_display_state’ has not been declared
./DllBCM.h:98:50: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_set_property(const int_)’:
./DllBCM.h:96:51: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_power_on_explicit_new(HDMI_MODE_T, HDMI_RES_GROUP_T, uint32_t)’:
./DllBCM.h:94:69: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function ‘virtual int DllBcmHost::vc_tv_hdmi_get_supported_modes_new(HDMI_RES_GROUP_T, int_, uint32_t, HDMI_RES_GROUP_T_, uint32_t_)’:
./DllBCM.h:92:130: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [linux/RBP.o] Error 1

---

Is there anything I need to install?
Thanks.

**Comment by popcornmix** [comment]
Top of tree omxplayer requires updated firmware. Can you try running rpi-update first?

**Comment by adks3489** [comment]
I Already ran rpi-update first.

**Comment by popcornmix** [comment]
I don't believe you are up to date. What does:
`grep TV_SUPPORTED_MODE_NEW_T /opt/vc/include/interface/vmcs_host/vc_tvservice_defs.h`
return? You should get:
`} TV_SUPPORTED_MODE_NEW_T;`

**Comment by adks3489** [comment]
Thanks!
I found the problem is my rpi-update not working right.
