### ISSUE TITLE
Buffer size parameter for live streams

### ISSUE THREAD

**Issue by kktuax** [huceke/omxplayer#109]
Some internet live HTTP streams won't play fluently. 
It would be nice to have a command line option to specify a bigger buffer size.

**Comment by iz8mbw** [comment]
Hi. I also need this feature when play 1080p movies from cifs (samba) share via ethernet.
Thanks!

**Comment by akshaylad** [comment]
is the issue resolved?

**Comment by popcornmix** [comment]
Not yet. I've got changes in progress.

**Comment by akshaylad** [comment]
Thank you sir! I've tried everything i could for past one week ! nothing
helped pls keep me updated

On Thu, Mar 21, 2013 at 12:25 AM, popcornmix notifications@github.comwrote:

> Not yet. I've got changes in progress.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huceke/omxplayer/issues/109#issuecomment-15196036
> .

## 

_Akshay Lad_
_(Technical Asst. Systems)_
_NIT-GOA_
_08007081745_

**Comment by popcornmix** [comment]
https://github.com/huceke/omxplayer/commit/730ca6571ed8bc3bc7d5fd934bc0ec0607522501

adds the ablity to tune the buffers used.
omxplayer --audio_queue=10 --video_queue=40
for example will allow larger file buffers.

**Comment by akshaylad** [comment]
i will check ! thanks

On Tue, Mar 26, 2013 at 3:32 AM, popcornmix notifications@github.comwrote:

> 730ca65https://github.com/huceke/omxplayer/commit/730ca6571ed8bc3bc7d5fd934bc0ec0607522501
> 
> adds the ablity to tune the buffers used.
> omxplayer --audio_queue=10 --video_queue=40
> for example will allow larger file buffers.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huceke/omxplayer/issues/109#issuecomment-15428518
> .

## 

_Akshay Lad_
_(Technical Asst. Systems)_
_NIT-GOA_
_08007081745_

**Comment by akshaylad** [comment]
how do i use this feature ? i cannot use it with my current omxplayer
\

On Tue, Mar 26, 2013 at 3:44 PM, Akshay Lad akshay@nitgoa.ac.in wrote:

> i will check ! thanks
> 
> On Tue, Mar 26, 2013 at 3:32 AM, popcornmix notifications@github.comwrote:
> 
> > 730ca65https://github.com/huceke/omxplayer/commit/730ca6571ed8bc3bc7d5fd934bc0ec0607522501
> > 
> > adds the ablity to tune the buffers used.
> > omxplayer --audio_queue=10 --video_queue=40
> > for example will allow larger file buffers.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/huceke/omxplayer/issues/109#issuecomment-15428518
> > .
> 
> ## 
> 
> _Akshay Lad_
> _(Technical Asst. Systems)_
> _NIT-GOA_
> _08007081745_

## 

_Akshay Lad_
_(Technical Asst. Systems)_
_NIT-GOA_
_08007081745_

**Comment by skgsergio** [comment]
I've just uploaded a new build to my site, you can try it (I didn't do it): http://omxplayer.sconde.net/#builds

**Comment by popcornmix** [comment]
Recent builds (e.g. http://omxplayer.sconde.net/) allow buffering sizes to be specified on command line so should fix this issue.
