### ISSUE TITLE
Playing mjpeg with single chanel pcm gives assertion in PCMRemap.cpp

### ISSUE THREAD

**Issue by rahrah** [huceke/omxplayer#114]
Hi,

I've been trying to use omxplayer to play avi files from my Canon 
digital camera:

The file util give this:

RIFF (little-endian) data, 
AVI, 640 x 480, 
30.00 fps, 
video: Motion JPEG, 
audio: uncompressed PCM (mono, 11024 Hz)

On playing, I get an assertion:

omxplayer.bin: utils/PCMRemap.cpp:457: PCMChannels\* 
CPCMRemap::SetInputFormat(unsigned int, PCMChannels*, unsigned 
int, unsigned int): Assertion `sampleSize == 2' failed.

The file PCMRemap.cpp seems to have its genesis in xbmc (I'm new to this), 
and that project seems to have zapped this file some time ago.

I built the buildroot-rbp successfully enough (some packages would 
not build there as their dependencies were detected on the host, 
rather than the target), then built omxplayer, successfully.  
Commenting out the assert didn't fix the problem. :-( Is there an 
easy fix for this?

Incidentally, needed patch thus wise to get omxplayer to build:

$BUILDROOT/output/staging/opt/vc/include/interface/vmcs_host
diff -u vcgencmd.h.org vcgencmd.h
--- vcgencmd.h.org      2013-02-11 19:09:43.000000000 +0000
+++ vcgencmd.h  2013-02-11 19:09:58.000000000 +0000
@@ -30,7 +30,7 @@
 #ifndef GENCMD_H
 #define GENCMD_H

-#include "vchost_config.h"
+#include "linux/vchost_config.h"
 #include "interface/vchi/vchi.h"

 VCHPRE_ void VCHPOST_ vc_vchi_gencmd_init(VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections );

Thanks for reading!

===Rich

**Comment by popcornmix** [comment]
Yes, omxplayer only currently supports 16-bits per sample audio.

**Comment by rahrah** [comment]
@popcornmix Hi Dom,

Thanks for getting back to me.  You posted on the github xbmc repo: 

https://github.com/xbmc/xbmc/pull/2119

> The MJPEG (mov) one is a locking issue between JPEG block used by xbmc for images, and the MJPEG
> codec and it will be fixed with a firmware update.

Any idea when that might be fixed?  Just trying to play those mjpeg avi files!

Thanks again,

===Rich
