### ISSUE TITLE
Doesn't recognize arrow keys when run in "screen" session

### ISSUE THREAD

**Issue by fastcat** [huceke/omxplayer#119]
If omxplayer is run from within screen, it seems that the arrow keys send different bytes, and omxplayer doesn't recognize them, thus making seeking impossible.

pressing left, right under `cat | hd` in a "normal" terminal:
`1b 5b 44 1b 5b 43`
And in screen:
`1b 4f 44 1b 4f 43`

**Comment by fastcat** [comment]
The screen session is running on a PC running screen "Screen version 4.01.00devel (GNU) 2-May-06" (debian package 4.1.0~20120320gitdb59704-7)

**Comment by popcornmix** [comment]
Should be solved with https://github.com/popcornmix/omxplayer/pull/15

**Comment by fastcat** [comment]
I don't see how that enhancement would fix this issue, since it doesn't allow the custom key configuration to specify the multi-byte key sequences used by arrow keys, except as "macros" for the built in knowledge of the arrow keys that were my original problem.

That said, I can't reproduce this issue any more either, so I'm not too worried about it.

**Comment by popcornmix** [comment]
https://github.com/popcornmix/omxplayer/commit/efd1049bc5ef77af9eda5d9e31d8ebf00f140b4c

adds the support I was thinking of. E.g.
`SEEK_FORWARD_SMALL:hex 0x4f43`

**Comment by fastcat** [comment]
Aah, thank you :+1:
