### ISSUE TITLE
SIGTERM not handled correctly

### ISSUE THREAD

**Issue by carli2** [huceke/omxplayer#120]
When I send TERM to omxplayer, omxplayer just quits while omxplayer.bin keeps playing the video.

I would expect omxplayer to handle the TERM signal and send TERM to its omxplayer.bin

**Comment by carli2** [comment]
This patch could fix it, but I did not test it yet.

```
diff --git a/omxplayer b/omxplayer
index 18b3ed2..a5ba6cd 100755
--- a/omxplayer
+++ b/omxplayer
@@ -35,7 +35,12 @@ if [ -e $FBSET ]; then
   fbset -xres 1 -yres 1
 fi

-$OMXPLAYER --font $FONT "$@"
+$OMXPLAYER --font $FONT "$@"&
+PID=$!
+
+trap "kill $PID" INT TERM
+
+wait

 if [ -e $FBSET ]; then
   fbset -xres ${XRES} -yres ${YRES}
```

**Comment by popcornmix** [comment]
omxplayer is just a script that launched omxpleyer.bin.
You should kill omxplayer.bin.

**Comment by carli2** [comment]
Please fix the script to kill omxplayer.bin
