### ISSUE TITLE
Option no cache 

### ISSUE THREAD

**Issue by hmess** [huceke/omxplayer#121]
Hi.
It is possible to have the option nocache like mplayer because in rtsp we have 2 secondes latency from ip camera ?
Thank you.
Best regards.

**Comment by matiaspl** [comment]
I think that omxplayer - being more or less a ffmpeg wrapper - should not do any option translation/mapping and allow to pass ffmpeg-style options to the demuxing/decoding process. We currently lack a lot of useful options: selection of video tracks in HLS streams, to name just one, input buffer size is also on the list. Ffmpeg offers them out of the box. It could be done just like ffmpeg does it (or used to do) with x264 libs, by adding -x264opts followed by a list of parameters.

**Comment by popcornmix** [comment]
I don't see omxplayer as being an ffmpeg wrapper at all.
The latency described here does not come from ffmpeg, but from the openmax queue, and the packet queue in OMXPlayerVideo/OMXPlayerAudio, so command line options to ffmpeg would do no good.

**Comment by hmess** [comment]
I think so. Like in mplayer, it have a second cache that we can desactivate.
In my case i don't have audio in the stream.

**Comment by matiaspl** [comment]
Ok, I agree that calling it a wrapper was harsh to say the least ;) 
I had the impression, that as far as network input and demultiplexing  is concerned, omxplayer uses ffmpeg. And so I also thought all the internal buffers (i.e. probe buffer) are in place adding to the latency. 
How low can we teoreticaly go with only omxplayers very own queues (in terms of frames, GOPs, etc.)?

**Comment by hmess** [comment]
I don't reach to reduce the latency.  I have try a lot of things, like reduce de Max duration analyse but that do nothing.
I don't find where the buffer size it is fixed. In the log file i always have 81920 buffersize for the stream the video.
I am sure that the latency is caused by the buffer cache but where can i modifie it ?
Thanks for you help.

**Comment by popcornmix** [comment]
https://github.com/huceke/omxplayer/commit/730ca6571ed8bc3bc7d5fd934bc0ec0607522501

allows the buffer sizes to be tuned. omxplayer hasn't been designed for really low latency, but it should be possible to make it under a second (assuming bitrate is modest)

**Comment by weekendowel** [comment]
I tried this with a camera (RTSP stream) but I can see no less latency than using omxplayer without tuning the buffer sizes. If I add buffer sizes I can see that the latency is worse and that is of course natural. But even if I try to set buffer size to just 1 MB it still has the same latency that it has without adding buffer switches at all. Is there some default buffer that always exists and this new feature just adds more buffer to the default buffer?

**Comment by popcornmix** [comment]
1MB may still be a number a seconds for a low bit rate stream. The buffer sizes are all floats, so you can try 0.1.

**Comment by hmess** [comment]
I have also try it with buffer size egal to 0.1, but  that have no effect.
I reach to reduce the latency near 0.5 secondes, by making the program start quickly by simplifying it.
I found one thing is that after one or two hours, the latency is close to 0 second. I thinks, it's because the clock of the Raspberry run faster that the real time and after it had display all frames in cache, the program wait for next frame send by the camera.

**Comment by weekendowel** [comment]
hmess what camera model are you using? I never had it running for a longer period I will try it.

**Comment by hmess** [comment]
it is a sony snc-zp550. By using the program like it is, to reduce the latency that take more time the two hours.

**Comment by weekendowel** [comment]
Ok, are you fetching a 1280 x 720 H.264 stream? What is your bit-rate? I´m using a Pelco IM10LW10-1E and are trying to get H.264 1280x720 stream, I also tried to get a MJPEG stream which seems to have less latency, but has a much higher bit-rate of course.

**Comment by weekendowel** [comment]
One more question hmess, how do you make omxplayer start quicker by simplifying it?

**Comment by hmess** [comment]
I am fetching a 1024x720 MP4 stream, H264 have more latency and MJPEG did not work. The bitrate that i use is 1024k, but it also work with 2048k.

It start quicker by removing : all printf, all call to clog ( not only by not using g option but really remove it) file, removing code of audio, subtitle and code who are call two times without needed, like clearstream, registerall etc...

**Comment by weekendowel** [comment]
Ok, so you built your own version. Any chance of sharing binary file with me?

**Comment by hmess** [comment]
Binray file ? what i do is modifying the source and compile it in the raspberry on arch linux system. I don't know to make a install. Only the bin , i thinks it did not work.
I can send you the image of the SD card but it that make 700Mo.
Or i will try tomorrow to put the source that i have modify on my repository.

**Comment by weekendowel** [comment]
If you could share the modified source it would be wonderful. That way I can build it on my Rasp :-)

**Comment by hmess** [comment]
I don't reach to post a new repositories ( i try use the program github for windows but it fail to publish it).
I post it in my dropbox here is the link : https://www.dropbox.com/s/a807062wf4qk82r/omxplayer_rstp.zip
Nota the source it is not finish to be clean but it work faster.

**Comment by popcornmix** [comment]
Recent builds (e.g. http://omxplayer.sconde.net/) allow all the buffers to be set from the command line.
While omxplayer isn't designed for low latency, it should be possible to get <1s.
