### ISSUE TITLE
Generating Log file every time is terrible.

### ISSUE THREAD

**Issue by StevenHickson** [huceke/omxplayer#128]
I think this is really annoying that it generates a log file every time you use omxplayer so that my folders all end up having omxplayer.log and omxplayer.old.log
It causes clutter and excessive writes on the SD card.

It bothered me enough that I pulled the code today, added a flag -g that enabled logging and turned logging off. It was pretty easy to do and I don't know why it's not a command line option. I can post the changes if necessary. It just requires a couple of differences in utils/log.cpp and omxplayer.cpp

**Comment by hinxx** [comment]
:+1: for the -g flag

**Comment by popcornmix** [comment]
-g flag implemented.

**Comment by ffloress** [comment]
Can we specify the log path?
