### ISSUE TITLE
Subtitles are terribly formatted

### ISSUE THREAD

**Issue by godofgrunts** [huceke/omxplayer#129]
Tried watching some anime using your omxplayer on the Raspberry Pi Rev B (512 MB version). When I turned on subtitles they are terribly done. I know this sub group pretty well and they don't use that font and your player completely ignores the soft subtitle rendering instructions. Github seems to be having some issues uplaoding my picture so here's a link to imgur http://i.imgur.com/UTYjwZw.jpeg

**Comment by gyeben** [comment]
I just tried watching some softsubbed MKVs, and all the styles described in the SSA format subtitles were totally ignored. Plus, omxplayer has problems when eg: a subtitle must be displayed during another one.

This issue has been mentioned here, too: https://github.com/huceke/omxplayer/issues/142, but again, no reply or whatever. :(

**Comment by popcornmix** [comment]
I'd suggest using xbmc which does support SSA formatting.
If you feel omxplayer should support this, then pull requests are welcome, but support is not planned.
