### ISSUE TITLE
screen goes blank when plaing two videos aligned horizontaly

### ISSUE THREAD

**Issue by reefer-zz** [huceke/omxplayer#130]
Hello!

I have got an issue using the --win option. If i start omxplayer with videos taking quarter of screen I can align them vertically (one under another), but if I try to do this horizontally(side by side) I get a black screen until I quit omxplayer. This happens when videos are aligned perfectly. If I move the other window down the y axis enough screen starts to flicker instead of blanking. This flickering vanishes when the other video is moved outside of the first video y axis. Then both videos play fine (now diagonally aligned: 1st in top-right corner, 2nd in bottom-left).

Has anyone had similar issues? I have B model with Hynix memories. Tried different splits up to 256MB but it doesn't seem to do anything.

Thanks for help.

**Comment by popcornmix** [comment]
Are the videos 1080p? You may be hitting a memory bandwidth issue.
By default the display is composited on the fly. Try adding:
dispmanx_offline=1
to config.txt (and reboot).
That uses an offscreen buffer that increases the memory latency tolerated.
(although decoding two 1080p streams is still going beyond what the chip supports).

**Comment by reefer-zz** [comment]
Hello,

Thanks for answer. Indeed both video files are 1080p bot downloaded from:
http://www.h264info.com/clips.html (Simpsons and I am Legend). There is no
problem in performance when I invoke 2 windows aligned vertically. So I
don't think it's a problem atm. Only horizontal alignment gives me the
screen blank. If both videos are aligned 0-540 screen is blank 100% time if
on is 0-540 2nd:270-810 it seems like a 50% blank (visible and blank
monitor intervals are the same) and if 1st is 0-540 and 2nd 541-1080
everything is fine. Placement along X axis dosen't make any difference.  I
will try your fix and let you know if it helps. Also something I noticed is
the window for 2nd movie shows up fine and after like 100ms I get a blank
screen or flicker (depending on positioning). Like some procedure after the
movie display procedure causes things to fail. I didn't had time to test
more today. I will try with different videos tomorrow and let you know.

Thanks for help.

2013/3/11 popcornmix notifications@github.com

**Comment by reefer-zz** [comment]
Hello,

I have tested the dispmanx_offline=1 option. It had indeed solved my problems. On the side note I managed to run 3 concurrent FullHD streams (Turbo over-clock) with almost no noticeable stutter or frame loss on videos. Two are working perfectly fine.

Cheers

**Comment by etam89** [comment]
Is there a way to display video on a vertical orienated TV ?

**Comment by popcornmix** [comment]
Latest omxplayer (source: https://github.com/popcornmix/omxplayer binaries: http://omxplayer.sconde.net/)
Supports --orientation command line option.
