### ISSUE TITLE
Gapless audio playback on Pi

### ISSUE THREAD

**Issue by ijhammo** [huceke/omxplayer#131]
Hi, is it possible to support gapless auido playback for MPS, FLAC and ALAC formats?

**Comment by popcornmix** [comment]
omxplayer (either command line version, or XBMC) doesn't support gapless.

The Pi and OpenMAX can support gapless playback, but it requires a more complicated setup.
You would do something like create two audio_decode components, they connect to a single audio_mixer and you feed the first track though the first audio_decode component, the second track through the second audio_decode component shortly before the first one finishes. The audio_mixer component combines the audio, and can provide fade in and fade out.

Personally, this is low on the list of priorities for things to do, and it doesn't require any work on the GPU side, so it's very unlikely I'll do this.
However it is something anyone who writes software could have a go at, and submit a pull request for.

**Comment by ijhammo** [comment]
ok thanks popcornmix.  Its still beyond my non-existent coding skills :-p  For now I have a workaround using a VM running windows

**Comment by popcornmix** [comment]
No support for this is planned.
