### ISSUE TITLE
Showing/playing jpeg, png images

### ISSUE THREAD

**Issue by hinxx** [huceke/omxplayer#132]
Would jpeg, png, bmp image displaying be of interest to anyone using omxplayer?

I know there are other many image viewers out there, but I would like to resort to a single application for the purpose of media center I'm trying to put together - not using openELEC or XBMC at all. Currently I'm running fbi (in console) to show images and omxplayer to play videos.

Another solution would be to create a video from a single image - not sure how to do that. In fact it would probably be the best thing to do, with least coding - It would even make showing multi-page PDFs appear as a smooth slideshow (after they are converted to pngs) :)

**Comment by popcornmix** [comment]
No plans to support still images in omxplayer.

**Comment by earthbound19** [comment]
Creating a video from a still image is technically very involved and a job for another tool. ffmpeg can do it:

`ffmpeg -loop 1 -i image.png -t 7 looped_image.mp4`

The -t parameter gives how many seconds the video loops the image for.
