### ISSUE TITLE
Can't seek when playing online video

### ISSUE THREAD

**Issue by bladeworks** [huceke/omxplayer#134]
When playing online video, the seek function fails. I've tried online flv/mp4 files.

**Comment by zhangjiemin005** [comment]
there is a diffrent from ffmpeg and omxplayer,
omxplayer is build on the lib of the ffmpeg, and ffplay can seek time when the video is online, but omxplayer cannot.
 m_ioContext = m_dllAvFormat.avio_alloc_context(buffer, FFMPEG_FILE_BUFFER_SIZE, 0, m_pFile, dvd_file_read, NULL, dvd_file_seek);
------>>>>m_ioContext ->seekable =0
that means the streams cannot to seek, why? there is possible to seek the online video?

**Comment by zhangjiemin005** [comment]
I was just found the way, actually, AvFormat can seek the online video, but omxplayer set some code to forbidden seek stream when the source is not a file, so if you comment all of code like " if(m_pfile)"  to force the omxplayer to seek online video ,and then build it, it would be work.
hope that can help you

**Comment by popcornmix** [comment]
If you can build from source there's an experimental patch:
https://github.com/popcornmix/omxplayer/commit/39ca5236098a01478414d3cc51914a0e2f8e727e

that allowed seeking from the stream I tried.

**Comment by bladeworks** [comment]
I got the following issue while building on arch.
OMXReader.cpp:153:23: error: ‘av_dict_count’ was not declared in this scope

Did I miss anything? Thanks.

**Comment by bladeworks** [comment]
I suppose it's a ffmpeg dependency issue. My ffmpeg version is 1.2.1.

**Comment by popcornmix** [comment]
Did you build ffmpeg with omxplayer? 
Do you have this file in your source:
ffmpeg_compiled/usr/local/include/libavutil/dict.h
That should declare av_dict_count.

**Comment by bladeworks** [comment]
Thanks for your reply.
I didn't build ffmpeg myself but installed it from the repo.

I found the dict.h with av_dict_count declared in /usr/include/libavutil but I didn't find it in /usr/include/ffmpeg-compat/libavutil/dict.h. I suppose it's the root cause. Do you have any suggestion? Thanks.

**Comment by popcornmix** [comment]
Sorry don't use arch. I'd suggest you ask the question in an arch forum.

**Comment by bladeworks** [comment]
Finally I make it working after compile ffmpeg. Thanks.
And I have another concern: is it possible to seek forward when playing named pipe? Thanks.

**Comment by popcornmix** [comment]
No, pipes don't support seeking.
It would be very slow if they tried to, e.g. by reading and discarding.
