### ISSUE TITLE
Passthrough + subtitles = crash

### ISSUE THREAD

**Issue by akerbos** [huceke/omxplayer#140]
I have embedded subtitles into MKV files. Video is encoded `V_MPEG4/ISO/AVC`, audio `A_AAC` and subtitles as `S_TEXT/UTF8` (values from `mkvinfo`).

If I watch the video without `-p`, all works fine. If I enable passthrough, though, the video crashes just when the first subtitle is shown. I was able to reproduce this with multiple videos.

**Comment by popcornmix** [comment]
Posting a sample video that shows the problem would be useful.

**Comment by akerbos** [comment]
@popcornmix You mean a file causing the problem, or a video of the screen while it happens? The latter is utterly boring.

I'll try and reproduce the error and post shell and log output.

**Comment by popcornmix** [comment]
A file that causes the problem would be useful.

**Comment by akerbos** [comment]
Both videos provided [here](http://www.iphonelife.com/blog/87/test-videos-my-forthcoming-video-playback-bible-deinterlacing-full-hd-mkv-mp4-and-subtitle-p) ([1](http://www.auby.no/files/video_tests/h264_1080p_hp_4.1_10mbps_dts_unstyled_subs_monsters.mkv), [2](http://www.auby.no/files/video_tests/h264_720p_hp_5.1_3mbps_vorbis_styled_and_unstyled_subs_suzumiya.mkv)) exhibit the problem.

I seem to have remembered resp. derived wrongly, though; `-p` has no influence, the subtitles "crash" the player no matter whether passthrough is active. I write "crash" because it does seem to continue runnning, but with bad lag.

I run omxplayer version 0.2.4~subtitle (as in the Raspbian repositories, libs current accordingly).

Do do remember that subtitles worked at some point; apparently me switching to passthrough coincided with an upgrade, and now it does no longer work.

**Comment by akerbos** [comment]
Ok, turns out my libraries were not as current as I thought. I [updated them](http://pastebin.com/pNvEKyaZ) and now subtitles work, with and without passthrough. Curious.

Especially curious is that now the first example video I linked above (the Monsters excerpt) no longer works; audio plays but the screen is grey. [Some other bug?](http://pastebin.com/NfDKgXS6)

**Comment by popcornmix** [comment]
Monsters trailer is playing for me. What memory split do you have?

**Comment by akerbos** [comment]
According to `/boot/config.txt`, it's at 64M, the default. [This post](http://raspberrypi.stackexchange.com/questions/673/what-is-the-optimum-split-of-main-versus-gpu-memory) suggests more may be wise. What do you think?

**Comment by popcornmix** [comment]
More is recommended when subtitles are used. Try 128M (although 96M is probably enough).

**Comment by akerbos** [comment]
That worked, thanks! Too little RAM causes grey screen, now that's ... interesting.
