### ISSUE TITLE
Player does not terminate if passthrough is on

### ISSUE THREAD

**Issue by akerbos** [huceke/omxplayer#141]
I pass through audio to my Bluray/Receiver with the `-p` flag. This works fine for the most part, but in some cases the player does not exit when the video is finished. The log does not give any indication of errors. Ctrl+C successfully quits the player.

**Comment by akerbos** [comment]
I have observed the effect with [this video](http://www.auby.no/files/video_tests/h264_1080p_hp_4.1_10mbps_dts_unstyled_subs_monsters.mkv) (via [this blog](http://www.iphonelife.com/blog/87/test-videos-my-forthcoming-video-playback-bible-deinterlacing-full-hd-mkv-mp4-and-subtitle-p)). [Here is a log without passthrough](http://pastebin.com/dCtevw0u) -- terminating regularly -- and [one with passthrough](http://pastebin.com/hFbEpPBf) -- had to quit with Ctrl+C.

**Comment by popcornmix** [comment]
Thanks for sample file. I see the same issue. Seems passthrough formats have a fixed pipeline latency (in addition to latency from amount of audio submitted). 
That means when we wait for audio to play out, we wait forever as it doesn't reach zero. 
I've changed the firmware to only add the fixed latency when it is non-zero and that makes the clip stop correctly.
The fix will be in next firmware (rpi-update) update.

**Comment by akerbos** [comment]
Great, thanks!

(Am I the only one who uses passthrough, or have I been unlucky with my files? O.o)

**Comment by popcornmix** [comment]
Should be fixed.

**Comment by akerbos** [comment]
Great! Hope this update ends up in the Raspbian repositories soon, this is _very_ annoying.

**Comment by popcornmix** [comment]
Run rpi-update and it will be fixed.

**Comment by akerbos** [comment]
Seems to have worked, thanks for your help!
