### ISSUE TITLE
SSA subtitles not working

### ISSUE THREAD

**Issue by mwestphal** [huceke/omxplayer#142]
ssa sub are not displayed.

Here is an example of a not working ssa sub.
http://pastebin.com/download.php?i=qWSTbvJ8

**Comment by gyeben** [comment]
This issue has been mentioned here, too: https://github.com/huceke/omxplayer/issues/129, but there isn't a solution yet.

**Comment by popcornmix** [comment]
I'd suggest using xbmc which does support SSA formatting.
If you feel omxplayer should support this, then pull requests are welcome, but support is not planned.
