### ISSUE TITLE
-i does not show height and width

### ISSUE THREAD

**Issue by nelsontb** [huceke/omxplayer#143]
The -i options does not show the movie size, has the --win scales the clip without maintaining the aspect ratio, if the -i supplied the original size, the caller program could adjust the sizes to avoid deforming the picture.

On a related note the nb_chapters appears twice but the values come from different variables

**Comment by popcornmix** [comment]
Looking at the code, it seems av_dump_format should be plumbed into the -i info option which gives output like ffmpeg. This now includes width/height and details on each stream.
Updated here.
https://github.com/huceke/omxplayer/commit/dd4f59c52a5fa850422f6730e346dce2cf30042b

**Comment by nelsontb** [comment]
Impressive timing and quality, was going to suggest to commit it but noticed you already did it.

Thank you
