### ISSUE TITLE
error when cross compile omxplayer

### ISSUE THREAD

**Issue by antoniocov** [huceke/omxplayer#147]
Hi! I have a raspberry pi with 512 MB of RAM. I installed fedora remix.
I upgraded the operating system. I upgraded the firmware to the latest version from github. 
I tried to compile omxplayer with the usual three commands:
1) make ffmpeg (ok)
2) make (no)
3) make distro

The first command is successful, but when I run the second command I get this error:
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:51:74: error: 'TV_SUPPORTED_MODE_NEW_T' has not been declared
./DllBCM.h:55:45: error: 'HDMI_PROPERTY_PARAM_T' does not name a type
./DllBCM.h:55:68: error: ISO C++ forbids declaration of 'property' with no type [-fpermissive]
./DllBCM.h:56:39: error: 'TV_DISPLAY_STATE_T' has not been declared
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:90:74: error: 'TV_SUPPORTED_MODE_NEW_T' has not been declared
./DllBCM.h:96:45: error: 'HDMI_PROPERTY_PARAM_T' does not name a type
./DllBCM.h:96:68: error: ISO C++ forbids declaration of 'property' with no type [-fpermissive]
./DllBCM.h:98:39: error: 'TV_DISPLAY_STATE_T' has not been declared
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_get_supported_modes_new(HDMI_RES_GROUP_T, int_, uint32_t, HDMI_RES_GROUP_T_, uint32_t_)':
./DllBCM.h:93:14: error: '::vc_tv_hdmi_get_supported_modes_new' has not been declared
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_power_on_explicit_new(HDMI_MODE_T, HDMI_RES_GROUP_T, uint32_t)':
./DllBCM.h:95:14: error: '::vc_tv_hdmi_power_on_explicit_new' has not been declared
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_set_property(const int_)':
./DllBCM.h:97:48: error: invalid conversion from 'const int_' to 'uint32_t {aka unsigned int}' [-fpermissive]
./DllBCM.h:97:48: error: too few arguments to function 'int vc_tv_hdmi_set_property(uint32_t, uint32_t, uint32_t)'
In file included from /home/coviello/rpi/usr/include/bcm_host.h:47:0,
                 from ./DllBCM.h:34,
                 from linux/RBP.h:45,
                 from linux/RBP.cpp:22:
/home/coviello/rpi/usr/include/interface/vmcs_host/vc_tvservice.h:465:22: note: declared here
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_get_display_state(int_)':
./DllBCM.h:99:14: error: '::vc_tv_get_display_state' has not been declared
./DllBCM.h:99:50: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_set_property(const int_)':
./DllBCM.h:97:51: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_power_on_explicit_new(HDMI_MODE_T, HDMI_RES_GROUP_T, uint32_t)':
./DllBCM.h:95:69: warning: control reaches end of non-void function [-Wreturn-type]
./DllBCM.h: In member function 'virtual int DllBcmHost::vc_tv_hdmi_get_supported_modes_new(HDMI_RES_GROUP_T, int_, uint32_t, HDMI_RES_GROUP_T_, uint32_t_)':
./DllBCM.h:93:130: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [linux/RBP.o] Errore 1

How can i fix?

**Comment by popcornmix** [comment]
> I upgraded the operating syste. I upgraded the firmware to the latest version from github.

How did you update? It sounds like /opt/vc/include is not up to date.
Either:
sudo apt-get update && sudo apt-get upgrade
or
sudo rpi-update

is needed to update firmware.

**Comment by antoniocov** [comment]
I update fedora remix with:
yum upgrade

and i update the firmware follow this guide:
https://github.com/Hexxeh/rpi-update

**Comment by triffid** [comment]
I saw errors like those when I tried it with gcc-4.6. As it says in
omxplayer's readme, it requires gcc-4.7. When I switched my profile to 4.7
it compiled successfully and works.

**Comment by popcornmix** [comment]
What does:

```
grep TV_SUPPORTED_MODE_NEW_T ~/rootfs/opt/vc/include/interface/vmcs_host/*
```

return? It should show:

```
/home/dc4/rootfs/opt/vc/include/interface/vmcs_host/vc_tvservice_defs.h:} TV_SUPPORTED_MODE_NEW_T;
/home/dc4/rootfs/opt/vc/include/interface/vmcs_host/vc_tvservice.h:                                                    TV_SUPPORTED_MODE_NEW_T *supported_modes,
```

**Comment by antoniocov** [comment]
My gcc is 4.7.2
Tomorrow, in the afternoon, i will run your command because now i don't have raspberry with me!
I'll let you know the outcome.

Thank you for your support!

**Comment by antoniocov** [comment]
I have mounted sysroot of raspberry pi with sshfs in "~/rpi". Your command gets this
output:

~/rpi/opt/vc/include/interface/vmcs_host/vc_tvservice_defs.h:}
TV_SUPPORTED_MODE_NEW_T;
~/rpi/opt/vc/include/interface/vmcs_host/vc_tvservice.h:
TV_SUPPORTED_MODE_NEW_T *supported_modes,

How can I fix?

2013/4/2 popcornmix notifications@github.com

**Comment by antoniocov** [comment]
it is possible that I have the wrong file Makefile.include for cross-compiling omxplayer

**Comment by popcornmix** [comment]
Okay, your ~/rpi/opt/vc/include/interface/vmcs_host/vc_tvservice_defs.h looks up to date.
The default Makefile.include assumes the rootfs is at /opt/bcm-rootfs.
You can either mount the rootfs there, or edit Makefile.include to point at your rootfs.

**Comment by antoniocov** [comment]
Thank you for your support but I left fedora remix and install wheezy...
