### ISSUE TITLE
Video lag

### ISSUE THREAD

**Issue by cgimenez** [huceke/omxplayer#148]
Hello, when playing big bunny 1080 h264 video I get many many lags (one or two per second).

My 512Mb Pi is not overclocked, the sdcard is a class 10 (so the fastest) and the same file plays fine with hello_video

No other process consumes cpu ressources

**Comment by skinkie** [comment]
I can confirm what you see. Even with a 256MB version.

The "lag" can best be observed when looking at the last scene when looking at the grass while moving forward. You can clearly see that the video stutters. This doesn't occur with hello_video. I wonder if this may be related to the refreshrate of the screen.

**Comment by popcornmix** [comment]
The sample in hello_video is a raw bitstream, with no packetisation or framerate or timestamps.
It's not really the sort of format that omxplayer is designed for.

Try adding it to a container (e.g. mkv) and I expect omxplayer will behave better.

**Comment by skinkie** [comment]
I was unable to correctly mux the test.h264 file into mkv without recoding. (The famous "Can't write packet with unknown timestamp") but I can confirm with recoding the mkv the movie is seamless but the bitrate is lowered significantly then (and the startup delay is still quite high).

When muxing it in mov instead, the lag is still there. It doesn't really matter if the mov header is in the front or on the back, tried both. @popcornmix could you evaluate especially this scene yourself?

**Comment by cgimenez** [comment]
Just to clarify my first message : I never used a raw h264 with omxplayer, I know this is a pure h264 that omxplayer could not handle correctly.

What I did was :
- play an official HD 1080 Big Bunny MP4 file with omxplayer, which he wasn't able to do without lagging every second
- play the same file after having removed the MP4 container, with hello_video, which prooved to be very flawless

My idea was to be sure there wasn't a problem with the GPU, the kernel, the modules, the firmware or whatever... because I allready used omxplayer in the past with 1080 Big Bunny MP4 file without problem, long starting delay excepted.

I did not checked again with the latest raspbian omxplayer version (if any)... I'll do the test this week

**Comment by popcornmix** [comment]
``sudo apt-get update && sudo apt-get upgrade`
should get you the omxplayer from latest raspbian.

omxplayer plays the 1080p 264 big buck bunny fine. It's one of my standard test clips. Can you point at the download URL of your version. I don't think they make a mp4 version (it's mov).

I'm not sure if your problem is a buffer underrun or judder from unsynchronised player and display.

If the former, where are you playing it from? Can you try playing it from another location (e.g. USB stick)
If the latter, are you using -r and does your display support 24 fps.

**Comment by skinkie** [comment]
Op 11 jun 2013 om 12:08 heeft popcornmix notifications@github.com  
het volgende geschreven:\

**Comment by cgimenez** [comment]
I did only used official versions from the big bunny download page...

But you're right I used h264 in .mov container, and stripped out the container to get raw H264 for test with hello_video, for comparing the two.

**Comment by popcornmix** [comment]
Just downloaded big_buck_bunny_1080p_h264.mov and it plays fine with omxplayer.

**Comment by skinkie** [comment]
I can confirm that the downloaded .mov file from the website doesn't inhibit the lag. Does make me wonder what is wrong with that distributed h264 file ;)

**Comment by popcornmix** [comment]
As I said:
"The sample in hello_video is a raw bitstream, with no packetisation or framerate or timestamps.
It's not really the sort of format that omxplayer is designed for."

**Comment by skinkie** [comment]
So it is naive from me to expect that an ffmpeg -i test.h264 -vcodec copy test.mov would add that?

**Comment by popcornmix** [comment]
I would expect that ffmpeg line to produce a file that is packetised and with timestamps, and so more suitable for omxplayer.

**Comment by skinkie** [comment]
Now my point is, that exactly that file gives problems as well. Maybe I should put it around somewhere so you can take a peak at it, and see if it gives problems for you as well?

**Comment by popcornmix** [comment]
Sure, post it somewhere and I'll have a look.

**Comment by skinkie** [comment]
http://stefan.konink.de/contrib/omx/test-muxed.mov

**Comment by popcornmix** [comment]
I've had a look. I see dropped/duplicated frames. It's a frame rate sync issue.
If you run with "-r" we'll switch to 50Hz (video is 25) and try to lock onto the framerate.
Trouble is this procedure takes a few seconds to get an accurate framerate measure, and the clip is too short.

I believe if you grab the full video, extract the 264 and put it in a mov file, it will become smooth after the first few seconds.

**Comment by skinkie** [comment]
You say that you will take a framerate measure. But why isn't the movie meta data used for that?

**Comment by popcornmix** [comment]
Because it can't be trusted to be accurate.
Even being 0.1% out you will drop a frame every 40 seconds.

**Comment by torarin** [comment]
@popcornmix: Is using -r different from first setting the correct HDMI mode with tvservice and then running omxplayer? I can see that OMXClock::HDMIClockSync sets some OMX_IndexConfigLatencyTarget parameters, but it is not clear to me what this achieves exactly.

Edit: I see that LatencyTarget is set in video_render as well. Presumably this adjusts the HDMI display frequency and is not enabled by default.

**Comment by popcornmix** [comment]
Yes, we contantly monitor the presentation timestamps and the vsyncs and (slightly) vary the HDMI clock to keep the frame updates at constant offset from the vsync.

We need a few seconds of timestamps to be sure that the framerate is within the hdmi clock tolerance and to know if increasing or decreasing the clock is the right thing to do.

The video_render LatencyTarget option enables this.

**Comment by popcornmix** [comment]
Solution is to use "-r" and a longer file.

**Comment by skinkie** [comment]
-r isn't always an option obviously. Because if you want to playout to for example a fixed framerate encoder...
