### ISSUE TITLE
What limits the number of instances of omxplayer?

### ISSUE THREAD

**Issue by aquadat0r** [huceke/omxplayer#158]
Hi there,

Currently it seems that omxplayer maxes out at around 4-5 instances. I'm attempting to playback multiple h264 videos, each being around 512 kbit/s. Since the hardware is able to support around 40Mbps???, what could the potential bottleneck be?

Regards,
Johan

**Comment by popcornmix** [comment]
Most likely RAM. Try increasing gpu_mem (e.g. to 384 on 512M board).
and try reducing buffer sizes:

```
              --audio_fifo  n           Size of audio output fifo in seconds
              --video_fifo  n           Size of video output fifo in MB
              --audio_queue n           Size of audio input queue in MB
              --video_queue n           Size of video input queue in MB
```
