### ISSUE TITLE
Omxplayer slow to start

### ISSUE THREAD

**Issue by aquadat0r** [huceke/omxplayer#160]
Hi there,

I have recently experienced that omxplayer take very long to actually display network video. It require me to actually hit space one or two times. Any ideas?

Thanks
Johan

**Comment by aquadat0r** [comment]
To add to this, omxplayer actually start ups as per normal however the video is just not displayer onscreen until I actually pause/unpause.

**Comment by popcornmix** [comment]
Can you provide a URL that shows this problem?

**Comment by aquadat0r** [comment]
It is a rtsp stream from one of my home security cameras. I have two scenarios, one working perfectly and the other not.

I have identical installations on two seperate SD cards, one a 2GB and another 4GB.

My 2GB has almost zero free space on its root partition, 99.9% full. On this card the streams start playing back almost instantly.

On my 4GB card, of which have a tried multiple makes, speeds etc it exhibits the behaviour mentioned above. 
It seems that because there is not disk space left on the 2GB, omxplayer aborts some disk operation and starts earlier, perhaps uses memory???

**Comment by popcornmix** [comment]
> It seems that because there is not disk space left on the 2GB, omxplayer aborts some disk operation and starts earlier, perhaps uses memory???

No. Are the versions of omxplayer identical?
Is this version: http://omxplayer.sconde.net/
good or bad?

**Comment by aquadat0r** [comment]
omxplayer version identical from http://omxplayer.sconde.net/

**Comment by popcornmix** [comment]
Do these setting affect things:
              --audio_fifo  n           Size of audio output fifo in seconds
              --video_fifo  n           Size of video output fifo in MB
              --audio_queue n           Size of audio input queue in MB
              --video_queue n           Size of video input queue in MB

**Comment by aquadat0r** [comment]
no not at all, tried various combinations of that, no effect

**Comment by aquadat0r** [comment]
sorry, my mistake. there is a difference
the older build works 100%, the newer one does not work.

**[works]** omxplayer_0.2.5~git20130326~5b369233_armhf.deb (41ac5e90dd6637b03469fcff0e5818366263d21a)
**[don't work]** omxplayer_0.2.5~git20130421~ae4dc6e9_armhf.deb (dd045526b0e09fc66a3ec1f22122feaf2728eddf)

**Comment by popcornmix** [comment]
Sorry, you'll have to be clearer. What effect are you seeing with each build? 
Are you talking about using the fifo/queue options?

**Comment by aquadat0r** [comment]
Sorry, omxplayer_0.2.5~git20130326~5b369233_armhf.deb allows me to start playback of any rtsp stream almost instantly (even up to four instances, no problem), whereas the latest build omxplayer_0.2.5~git20130421~ae4dc6e9_armhf.deb does not. 

I am not using any of the fifo/queue options at all.

**Comment by popcornmix** [comment]
That is to be expected. The newer build only starts playing when the fifo is somewhat full. It makes videos less likely to stutter. Reducing the queue/fifo sizes should allow you get get fast startup with the new omxplayer.
Try "--audio_fifo 1" or even "--audio_fifo 0.2"

**Comment by aquadat0r** [comment]
No luck, still does not fix it. Just as a note, my streams do not have audio.

**Comment by popcornmix** [comment]
Ah - no audio may well make a difference. I'll see if I can find a video only file to test.

**Comment by skgsergio** [comment]
@aquadat0r can you try this versions?

http://omxplayer.sconde.net/builds/omxplayer_0.2.6~git20130425~8e8e6c88_armhf.deb (newer one, no diferences with the other. Rebuilt this version using an updated buildenv)

http://omxplayer.sconde.net/builds/omxplayer_0.2.5~git20130423~8e8e6c88_armhf.deb

**Comment by aquadat0r** [comment]
will do

**Comment by aquadat0r** [comment]
unfortunately the problem still exists

**Comment by StevenHickson** [comment]
I actually have seen the same issue on my newest version.
It happens even on videos that aren't streaming. My local videos occasionally require pause/unpause to start.
This has been an issue with the newest commit. It happened somehow between 3/26 and now. I'm going to go through the log and check.

**Comment by StevenHickson** [comment]
So it seems it only happens on certain videos. On the videos that work, my output looks like this:
Output mode 16: 1920x1080@60 N:10
ntsc_freq:0 
Video codec omx-h264 width 512 height 384 profile 100 fps 25.000000
Audio codec mp3 channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
Video codec omx-h264 width 512 height 384 profile 100 fps 25.000000
Video codec omx-h264 width 512 height 384 profile 100 fps 25.000000

On the videos that don't work. I get this:
Output mode 32: 1920x1080@24 :20
ntsc_freq:1 
Video codec omx-h264 width 512 height 384 profile 100 fps 23.976025
Audio codec ac3 channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
C : 86019 2 48000 0 16
N : 86019 2 48000 192000 16
Audio codec ac3 channels 2 samplerate 48000 bitspersample 16

Then I have to press space twice. 

I think it is commit ae4dc6e917f69e9477d1df465183f64a660ab8cf that did this.
line 333 in OMXPlayerAudio.cpp always shows up when this happens and it didn't use to. So something went crazy in the Decode function. This happens right when it starts and whenever you skip around.

**Comment by popcornmix** [comment]
Can you post a sample of a file that does this?

**Comment by StevenHickson** [comment]
You can grab one of mine that does this at http://stevenhickson.com/test.mkv

**Comment by aquadat0r** [comment]
Any luck with solving this issue? Still broken on omxplayer_0.2.7~git20130611~27d3bb74_armhf.deb.

**Comment by StevenHickson** [comment]
I haven't had any luck yet but I'm building a new version tonight to print out a lot more debug information to hopefully help me figure out what's happening.

**Comment by StevenHickson** [comment]
Ahh just figured it out. Need to do some more testing to make sure I don't break other videos. Will post resolution soon.

**Comment by popcornmix** [comment]
Can you try latest build here:
http://omxplayer.sconde.net/
or source:
https://github.com/popcornmix/omxplayer

**Comment by StevenHickson** [comment]
Worked for me!
Switched the codec properly even with the 0 bitrate on the new FFMPEG.
So is https://github.com/popcornmix/omxplayer where all the new development is going?
If so I'll have to pull the code from there from now on.

**Comment by popcornmix** [comment]
Yes.

**Comment by StevenHickson** [comment]
Good to know. This version actually fixes all of the problems people have told me except for one. 
I'll update my blog to point people to the newest version.
Thanks!

**Comment by StevenHickson** [comment]
There seems to be no issues section in the newest fork. Is that intentional or is it just Github's new interface messing with me?
Where do we report/discuss/attempt to fix weird problems?

**Comment by popcornmix** [comment]
Ah, perhaps they weren't enabled - try now.

**Comment by popcornmix** [comment]
Recent builds (e.g. http://omxplayer.sconde.net/) allow buffering sizes and threshold when to come out of buffering to be specified on command line, so should fix this issue.
