### ISSUE TITLE
Streaming issue: Problems with new builds, no video displayed 

### ISSUE THREAD

**Issue by sive** [huceke/omxplayer#164]
Hello.
For testing purposes I’m streaming a RTP Transport Stream with VLC Player from my PC to the Raspberry Pi (raspbian). It’s a h264 720p video with audio.
Until build “omxplayer_0.2.5~git20130326~5b369233_armhf.deb” the omxplayer starts and displays the video. It’s not a smooth video (sometimes colored boxes etc.), but it's being displayed. 
The builds afterwards do not display the video (I have updated the firmware of the Pi).
There are two errors in the log (build 20130427):
COMXCoreComponent::SetParameter – OMX.broadcom.audio_mixer failed with omx_err(0x80001005)
COMXAudio::AddPackets error SetParameter 1 omx_err(0x80001005).

I am starting the player with omxplayer udp://192.168.2.255:5004 since rtp:// seems not being supported. I guess this might be a problem? Is there any chance in implementing rtp streams or is there a good workaround for the standalone omxplayer? In raspbmc it is possible to play rtp streams and raspbmc is using omxplayer.  

Another question (using build 20130326): In case of streaming RTP the omxplayer needs about 6 sec to start and display the stream. I made use of the parameters --video_queue and --video_fifo (with e.g. 0.2). In the --stats output I see  that the buffer and the cache is never growing larger than the given values, but unfortunately this changes nothing about the 6 sec it needs to start. Is this a problem with other buffers not affected by video_queue or video_fifo? I don’t understand how it is possible that omxplayer plays the stream with 6 sec delay, where is the data stored in the meantime? 
If I pause the stream and wait until the 6 sec are over, then start again the stream,  omxplayer plays it nearly without any delay.

Thanks a lot & best regards!

**Comment by andreashouben** [comment]
Hi there,

I hava a similar problem. I'm using omxplayer_0.2.6~git20130427~fcfb7911_armhf.deb to stream an rtsp stream. The player starts but there is no image visible. But if I press 2 the stream gets visible. That is quite impractical because I want to setup an autonomous video system that automatically starts streaming without the need of any user inputs. Any suggestions?

**Comment by andreashouben** [comment]
If anyone's interested I built an expect script to workaround the issue:

``` bash
#! /usr/bin/expect -f
#
# start omxplayer and press 2
#
spawn omxplayer rtsp://x:y@10.1.1.116:554/axis-media/media.3gp
expect "Subtitle"
sleep 5
send "2"

while {1>0} {sleep 1}
```

I call this script on startup. Works like a charm.

Funny thing to mention... I have no idea why, but suddenly the video starts to play when omxplayer is started. Yet you still have to send 2, because otherwise you have a massive streaming lag. After pressing 2 the video seems to go fast forward until the point where it hits real time. Then it works just fine.

**Comment by btweb** [comment]
Very interested, thanks, that works well.  I just added a command line argument so I could call it from an existing script in place of omxplayer:

``` expect
#! /usr/bin/expect -f
#
# start omxplayer with the argument supplied to this script, and press 2
#
set url [lrange $argv 0 0]
spawn omxplayer $url
expect "Subtitle"
sleep 5
send "2"

while {1>0} {sleep 1}
```

And put it in a script called omxplay (marked executable).

There is however quite a delay before it starts and when it plays it is sped up.  I suspect the multiple levels of scripts are buffering a bit of the data.

This is quite a disappointing development for omxplayer as the previous functionality worked well for displaying video from a security camera as soon as motion was detected (by zoneminder).

**Comment by Berryfier** [comment]
After recent apt-get update & upgrade to my raspberry pi I found that omxplayer would only show the first few frames from a mjpeg stream of 960x720 pixels. In reading the above comments I found that by using the "2" key immediately after entering the command to play the stream, omxplayer is able to overcome the moment of stall  with 960x720 and continue playing. Omxplayer still (just) starts with a 640x480 mjpeg stream, but it used to start and continue just fine at all image sizes.

**Comment by aquadat0r** [comment]
I've been trying to get this resolved for months, the only 100% working version is http://omxplayer.sconde.net/builds/omxplayer_0.2.5~git20130421~ae4dc6e9_armhf.deb. Please have a look at the issue I logged. https://github.com/huceke/omxplayer/issues/160

**Comment by StevenHickson** [comment]
Just figured it out and got it to work on my system. Need to do some testing on other videos to make sure it doesn't break other things. Will post resolution soon.
