### ISSUE TITLE
Project work/ programming basis

### ISSUE THREAD

**Issue by selkemann** [huceke/omxplayer#165]
Hi,
I'm a beginner at C, I've became a project work to adjust the omxplayer.
But unfortunately I don't know which programming basis is possible to adjust the player.
Could you name me a good dvelopment kit for the omxplayer?

**Comment by popcornmix** [comment]
I think a general programming question like this is best asked the raspberry pi forums.
You can build omxplayer directly on the Pi (after installing gcc 4.7) which is the simplest solution, or you can use a cross compiler from a more powerful machine. (e.g. https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian).

But this isn't an omxplayer specific question. This may be a better place to ask:
http://www.raspberrypi.org/phpBB3/viewforum.php?f=33
