### ISSUE TITLE
Change how omxplayer reports playback ended

### ISSUE THREAD

**Issue by akameswaran** [huceke/omxplayer#166]
While working on lyrics issue on XBMC, it was discovered omxplayer sends the "wrong" signal back to xbmc when a song ends.  Please see the issue that I was requested to open at xbmc.  http://trac.xbmc.org/ticket/14306  the most relevant portion is this:
"omxplayer seems to triggers an OnPlaybackEnded notification after every song, whereas paplayer only calls OnPlaybackEnded at the end of the playlist. "

I think this also explains why my AVR gets very unhappy between songs when they naturally advance (the lack of gapless is also part of the problem, but it does seem worse if I let songs advance as opposed to skipping to next track etc.

**Comment by popcornmix** [comment]
This repo is for the command line omxplayer app. The Trac system is the correct place to report issues.
