### ISSUE TITLE
1080i videos dropping frames

### ISSUE THREAD

**Issue by julianscheel** [huceke/omxplayer#167]
With 1080i50 content from DVB-S I see the video not beeing smooth most of the time. I uploaded a sample capture from Anixe HD to http://www.jusst.de/files/anixehd.ts
The first scene looks fine, but when the ape appears it seems to drop a lot of frames. Deinterlacing seems not to have an impact.

**Comment by popcornmix** [comment]
Is it the same with the "new_stall" branch.
Are you running with "-r" option?

I'm not certain I'm seeing the effect you are reporting. Possibly it is a little juddery, but it's very subtle.
One issue is there are a few points in the clip with packet loss.

If you lose an audio packet, then some compensation needs to be done. In general you don't know a packet has been lost, you just know there is jitter on the timestamps compared to what you believe the time should be compared with number of samples decoded. Unfortunately timestamp jitter is very common in files so isn't completely reliable in indicating packet loss.

When timestamps don't tie up with number of samples decoded, the clock component tries to adjust. If there is a big jump (>100ms) it resets the audio clock. If there is a smaller jump it adjust the clock speed (resampling the audio to compensate). Either of these effects could result in video frames not being displayed.

Can you confirm if the effect only occurs with audio packet loss?
(i.e. remux in perfect audio into a problematic video and see if it is improved?)

**Comment by julianscheel** [comment]
I did quite some further testing (all with new_stall branch) and at the moment this works just fine. So I close this for the moment. In case I see the issue again I will reopen. Sorry for the noise.
