### ISSUE TITLE
oxmplayer with framebuffer devices

### ISSUE THREAD

**Issue by iltomma** [huceke/omxplayer#168]
Is it possible to use oxmplayer with framebuffer devices (ex: /dev/fb1)?

**Comment by popcornmix** [comment]
No. omxplayer is a GPU decoder, with the GPU doing decode, scheduling and rendering.
The GPU has no knowledge of /dev/fb1.

While you could just use the GPU for decode (there are some people who have this working with gstreamer), the performance is much lower, and this is not something omxplayer will support.
