### ISSUE TITLE
Seeking causes omxplayer to stop displaying frames

### ISSUE THREAD

**Issue by earthmeLon** [huceke/omxplayer#172]
omxplayer is capable of playing my H.264 videos very nicely.  However, if I attempt to fast-forward or seek forward (using right arrow key), my screen goes blank and does not resume.  I have tries sitting for about a minute to see if it's a caching issue or something, but it just does not resume playback.

Whenever I seek, the terminal will output something similar to:
    Video codec omx-h264 width 976 height 720 profile 100 fps 23.976025

I have to terminate omxplayer and relaunch for it to display correctly.

Any suggestions on how to get seeking working?

**Comment by earthmeLon** [comment]
Pressing **o** to skip to the next chapter works.

**Comment by earthmeLon** [comment]
It seems as though adding **--audio_queue=10** and **--video_queue=40** lets me seek forward. 

It still randomly doesn't work, but if I seek again and again it will eventually work.  It's a bit frustrating because it's hard to tell if it's taking a second or if it's failing to seek.

**Comment by popcornmix** [comment]
Does this still occur with version from:
http://omxplayer.sconde.net/
