### ISSUE TITLE
[Enhancement] LIRC Support

### ISSUE THREAD

**Issue by earthmeLon** [huceke/omxplayer#173]
Waiting patiently for LIRC support, but I was wondering if it was in the plans or something that you are even interested in, yourself.

Thanks for such a great media player :D

**Comment by popcornmix** [comment]
As usual, pull requests would be welcome.

**Comment by earthmeLon** [comment]
I'd love to give it a try, but I am unable to get it to compile because of xmbc-bcm dependencies.  

Even when setting CROSS_COMPILE=${RASPTARGET}, as I have set up, it is trying to use xbmc-bcm gcc to compile :\

**Comment by earthmeLon** [comment]
Frustrating that one must use a special cross-compiler just to work on this project vs other RaspberryPi projects.

I've found your project https://github.com/huceke/buildroot-rbp and will try to use it.  Why is it required and hard-coded into the code?  Just a bit confused about it.

**Comment by popcornmix** [comment]
There are instructions in README for building omxplayer natively on the Pi.
If you want to cross-compile you will have to edit the makefiles.
These are the differences for my build environment
http://pastebin.com/xQD4naWf
but you may have to edit paths to match yours.

**Comment by popcornmix** [comment]
Superceded by:
https://github.com/popcornmix/omxplayer/issues/10
