### ISSUE TITLE
Aspect ratio changes not detected

### ISSUE THREAD

**Issue by julianscheel** [huceke/omxplayer#174]
When playing mpeg ts streams aspect ratio changes within the stream are not honoured by omxplayer. A sample file can be found here: http://jusst.de/files/iptv-capture-pro7_mpeg2_d1_mp2a_48k_aspect-switch.ts

**Comment by popcornmix** [comment]
I was going to try implementing this, but on a quick search, couldn't find a suitable sample.
I'll have a try with your sample.

**Comment by popcornmix** [comment]
A quick look shows the GPU side ignores the apsect ratio change (deliberately - it does detect it). I've issued a bug report and got this response from codecs team:
"This isn't actually valid in mpeg2 - a repeat sequence header isn't supposed to change anything except quantisation matrices. However, we should probably support it."

Just wondering where the file came from? Is it from a live broadcast, or has it been concatenated somehow?

**Comment by julianscheel** [comment]
It's a live broadcast from a german TV station (ProSieben) received over DVB-S. These type of aspect ratio changes happen several times a day there.

**Comment by popcornmix** [comment]
Got the fix in firmware. Will plumb into omxplayer tomorrow.

**Comment by julianscheel** [comment]
Thanks, this is very good :)

**Comment by popcornmix** [comment]
Try latest omxplayer:
https://github.com/popcornmix/omxplayer/commit/b853c397724fa147ba2adbc9084dc748e3b2a6e2
and latest (rpi-update) firmware:
https://github.com/Hexxeh/rpi-firmware/commit/3d022de4ba6e293449f3616e90b2361dcea4f67b

**Comment by julianscheel** [comment]
Works well, thank you!
