### ISSUE TITLE
Resume video question

### ISSUE THREAD

**Issue by media601** [huceke/omxplayer#175]
I'm not sure if this is the right place to ask this, but I couldn't find a suitable OMXPlayer forum. I'm looking for a way to resume a video from a time mark after it has been closed and resumed--similar to the way XBMC does it. I've looked into bash scripting and python, but can't find a way to draw this information from the video.  I had an idea to start a timer when the video starts, write the number of seconds to a text file when the video closes, then apply the number of seconds as a variable when the video is reopened. This would probably work until you skip ahead or back in the video, which would throw off the timer. I have not found a way to get the specific time mark from the video and apply it as a variable on resume. Any ideas how this may be accomplished? I love the small footprint and performance of Raspbian/OMXplayer, but this is the one feature that is keeping me with RaspBMC. Finally, I just want to say Thank you Thank you Thank you for all the work you have done on this fantastic media player.

**Comment by popcornmix** [comment]
Perhaps making omxplayer output the elapsed time if it is stopped before the end? E.g.
Elapsed time: 3600s

You could parse that and store it away, and when next played, you use that as initial seek position.
Sound okay?

**Comment by media601** [comment]
Thank you for the reply.

Your suggestion would work great if it output the true time mark of the video and not just the number of seconds it was running. The latter would not work if the video was skipped back or forward during playback. 

Are you saying that I could somehow get this information from OMXPlayer now, or this would require a developer enhancement? I don't know of any way to get this information from OMX at present.

**Comment by popcornmix** [comment]
Yes, I'm suggesting I could add to a future version of omxplayer the elapsed video time (i.e. the time you would seek to to get back there) when stopping a video early.

**Comment by media601** [comment]
Yes, I think that would be a terrific addition. Thank you for your consideration.

Date: Fri, 24 May 2013 06:55:15 -0700

**Comment by popcornmix** [comment]
Can you try latest build here:
http://omxplayer.sconde.net/
or source:
https://github.com/popcornmix/omxplayer

It outputs:
Stopped at: 00:06:31
have a nice day ;)

**Comment by media601** [comment]
Thank you. I will try it this weekend.

Date: Tue, 18 Jun 2013 04:23:19 -0700
