### ISSUE TITLE
flac support broken

### ISSUE THREAD

**Issue by gkreidl** [huceke/omxplayer#177]
Flac support is broken (distorted, wrong timing) since version 0.2.5~git20130421. It was working fine in older versions.

**Comment by popcornmix** [comment]
Can you try latest build here:
http://omxplayer.sconde.net/
or source:
https://github.com/popcornmix/omxplayer

**Comment by gkreidl** [comment]
with omxplayer_0.2.7~git20130618~69cd6589_armhf.deb 
I don't get any sound from music files at all, independant from file format (mp3 and flac tested). Audio inside video files does work, however, using hdmi sound
did apt-get update/upgrade and rpi-update before.

after reinstalling omxplayer_0.2.6~git20130427~fcfb7911_armhf.deb mp3 files played again, flac distorted

after reinstalling omxplayer_0.2.5~git20130326~5b369233_armhf.deb both mp3 and flac are working

Hope, that helps.

**Comment by popcornmix** [comment]
Ah yes, just fixed a bug with audio only files:
https://github.com/popcornmix/omxplayer/commit/6527785c53dbaf8467293995151100a0900c94d8

You'll need to rebuild from source or wait for next http://omxplayer.sconde.net/ build.

**Comment by gkreidl** [comment]
I will wait for next update on http://omxplayer.sconde.net/
