### ISSUE TITLE
omxplayer blocked

### ISSUE THREAD

**Issue by bluerobert** [huceke/omxplayer#178]
Hello, I am new in github, hope this is the correct place.

Error : omxplayer blocked after a loop count of 40 - 200.

In the omxplayer.log file there is only one line:
00:00:00 T:0 DEBUG: DllBcm: Using omx system library

my test:

a="0"
while true
do
a=`expr $a + 1`
echo $a
omxplayer -o hdmi 00485.MTS
done

00485.MTS:
Video codec omx-h264 width 1920 height 1080 profile 100 fps 50.000000
Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
Subtitle count: 1, state: off, index: 1, delay: 0

Hardware : 256/512MB, GPU 128MB, no overclock, Power 5.2V/4A
Software : omxplayer : 0.2.6~git20130427, OS : Raspbian wheezy

Any suggestions how to get it working? Thanks a lot !
( I also post this problem in : http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=45000 )

**Comment by popcornmix** [comment]
What does "vcgencmd version" report?
There has been a firmware fix that could cause this problem.
(https://github.com/Hexxeh/rpi-firmware/commit/bf4dedc9a66dc4c374d373ccea27ff77fa545bc6)

**Comment by bluerobert** [comment]
Hello popcornmix, thanks for your reply.
 vcgencmd version
May 24 2013 16:54:51
Copyright (c) 2012 Broadcom
version    \6676ab07e56aeec897f23d09b8fb87b55cbec981 (clean) (release)
without "\"

rpi-update reports:
 **\* Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS
 **\* ARM/GPU split is now defined in /boot/config.txt using the gpu_mem option!
 **\* Your firmware is already up to date

**Comment by bluerobert** [comment]
<b>
Additional tests:
</b>
Between each test, there is a power off/on of the Rpi.

<table>
<tr>
<td>connected to Rpi</td><td>   power</td><td>  loop <br> count</td><td>    remarks</td>
</tr>
<tr>
<td>Keyboard    </td><td>       5.1V/4A </td><td>-      </td><td>manual user break after 104 loops</td>
</tr>
<tr>
<td>Keyboard        </td><td>   5.1V/4A</td><td>    -   </td><td>   manual user break after 105 loops</td>
</tr>
<tr>
<td>Keyboard, WLAN  </td><td>5.1V/4A    </td><td>51 </td><td>   running ping from other system, 
                                omxplayer blocked,
                                ping is running<br>
In the omxplayer.log file there is only one line:<br>
00:00:00 T:0 DEBUG: DllBcm: Using omx system library
</td>
</tr>
<tr>
<td>Keyboard, WLAN  </td><td>5.1V/4A</td><td>   -   </td><td>   running ping from other system, 
                                manual user break after 157 loops</td>
</tr>
<tr>
<td>D-link USB HUB  <br>    Keyboard, WLAN, DISK</td>
<td>5.1V/4A </td><td>97 </td><td>   running ping from other system, 
            omxplayer (video on disk) blocked,
                                ping is running<br>
In the omxplayer.log file there is only one line:<br>
00:00:00 T:0 DEBUG: DllBcm: Using omx system library</td>
</tr>
<tr>
<td>Keyboard        </td><td>   5.1V/4A</td><td>    83  </td><td>   omxplayer blocked, keyboard is working<br>
In the omxplayer.log file there is only one line:<br>
00:00:00 T:0 DEBUG: DllBcm: Using omx system library</td>
</tr>
<tr>
<td>No USB dev  </td><td>       5.1V/4A </td><td>18 </td><td>   before teststart disconnect keyboard,
                                omxplayer blocked,
                                connect keyboard, keyboard is working</td>
</tr>
<td>No USB dev  </td><td>       5.1V/4A </td><td>22 </td><td>   before teststart disconnect keyboard,
                                omxplayer blocked,
                                connect keyboard, keyboard is working<br>
In omxplayer logfile, last line : <br>
00:00:00 T:0 ERROR:COMXCoreComponent::DecoderEventHandler <br>
OMX.broadcom.audio_mixer - <br>
OMX_ErrorPortUnpopulated port 0, <br>
cannot parse input stream<br>
</td>
</tr>
<tr>
<td>No USB dev  </td><td>       5.1V/4A </td><td>6  </td><td>   before teststart disconnect keyboard,
                                omxplayer blocked,
                                connect keyboard, keyboard is working<br>
In omxplayer logfile, last line : <br>
00:00:00 T:0 ERROR:COMXCoreComponent::DecoderEventHandler <br>
OMX.broadcom.audio_mixer - <br>
OMX_ErrorPortUnpopulated port 0, <br>
cannot parse input stream<br>
</td>
</tr>
<tr>
<td>No USB dev  </td><td>       5.1V/4A </td><td>30 </td><td>   before teststart disconnect keyboard,
                                omxplayer blocked,
                                connect keyboard, keyboard is working<br>
In omxplayer logfile, last line : <br>
00:00:00 T:0 ERROR:COMXCoreComponent::DecoderEventHandler <br>
OMX.broadcom.audio_mixer - <br>
OMX_ErrorPortUnpopulated port 0, <br>
cannot parse input stream<br>
</td>
</tr>
</table>

Let me know if you need more information.

**Comment by popcornmix** [comment]
Do all files have the same failure?
Sounds like there is a memory leak (on GPU), and after enough runs we fail to start up.

**Comment by bluerobert** [comment]
Yes/No. It is dependent to the connected USB devices. 
Without connecting any USB devices to the Rpi, the maximum loop count is in range from 6 to 30.
With connected USB devices, the loop count is from 51 to oo.
Please read my table above.

If you have time to run the same test by yourself, you can download the video file from
http://www.franksalomon.de/robert/pub/00485.MTS
But I think it is useful to test without USB devices. 
Let me know if you need more information.

**Comment by bluerobert** [comment]
After a rpi-update the omxplayer is running very well in a loop.
Before the maximum loop count was 30 (No USB devs connected).
Now I runs 2 tests:
- reboot.
- manual user break after a loop count of 478.
- reboot.
- manual user break after a loop count of 403.

@popcornmix 
Many thanks for your great work.
