### ISSUE TITLE
Video having embedded subtitles does not play as expected

### ISSUE THREAD

**Issue by stifi** [huceke/omxplayer#179]
omxplayer shows a gray image and black rectangles instead of the expected video when playing a matroska having embedded subtitles as shown below. After removing the subtitle stream the video plays fine.

```
omxplayer -i sample.mkv

[matroska,webm @ 0xe13650] max_analyze_duration 0 reached at 0 microseconds
[matroska,webm @ 0xe13650] decoding for stream 0 failed
Input #0, matroska,webm, from 'sample.mkv':
  Metadata:
    creation_time   : 2013-05-27 07:17:31
  Duration: 00:00:09.61, start: 0.000000, bitrate: 5515 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p, 1912x1072 [SAR 1:1 DAR 239:134], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      title           : CC
```

After removing Stream #0:2(eng) by 
`mkvmerge -o sample_nosubs.mkv --nosubs sample.mkv`
video and audio works fine.

```
omxplayer -i sample_nosubs.mkv

[matroska,webm @ 0x1701650] max_analyze_duration 0 reached at 0 microseconds
[matroska,webm @ 0x1701650] decoding for stream 0 failed
Input #0, matroska,webm, from 'sample_nosubs.mkv':
  Metadata:
    creation_time   : 2013-05-27 07:18:19
  Duration: 00:00:05.86, start: 0.000000, bitrate: 9048 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p, 1912x1072 [SAR 1:1 DAR 239:134], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
```
- sample w/ subtitles: http://tiny.cc/hdfqxw
- sample w/o subtitles: http://tiny.cc/sweqxw

System:
Rasperberry Pi
omxplayer: latest git (fcfb791)

**Comment by popcornmix** [comment]
How much gpu_mem do you have configured? 64M isn't really enough for 1080p with subs. Try with 128M.

**Comment by stifi** [comment]
Yes, that solved the issue!

As guessed by you, I used 64M only. By changing the configuration to 128M the movies (including the subs) play fine.

Thanks for the fast response!
