### ISSUE TITLE
Bug in Branches new_stall

### ISSUE THREAD

**Issue by fcarlier** [huceke/omxplayer#180]
Hello,
Little infos on new_stall :
In MY case, '[rbp] Don't block waiting for EOS in audio/video players' / commit ad94346dbccb6d315bf80f40fdd04cb57de8edf3, is OK
After, 'Make deinterlace automatic for deinterlaced streams.' / commit c227bdc64c7e7a89a4e36b9cf97fb4306e060db8, i have an error : 

omxplayer.bin: OMXCore.cpp:845: OMX_ERRORTYPE COMXCoreComponent::FreeOutputBuffers(): Assertion `m_omx_output_buffers.size() == m_omx_output_available.size()' failed.
/usr/bin/omxplayer : ligne 22 :  2278 Abandon                 LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN "$@"

It's identical with all after commit ;)

THX
Florent

**Comment by popcornmix** [comment]
I'm going to need a sample file and the omxplayer command entered to fix this.

**Comment by fcarlier** [comment]
omxplayer :
"""
#!/bin/bash

OMXPLAYER_BIN="/usr/bin/omxplayer.bin"
OMXPLAYER_LIBS="/opt/vc/lib:/usr/lib/omxplayer"

FBSET="/bin/fbset"

if [ -e $FBSET ]; then
    DEPTH2=`fbset | head -3 | tail -1 | cut -d " " -f 10`
    if [ "$DEPTH2" == "8" ]; then
        DEPTH1=16
    elif [ "$DEPTH2" == "16" ]; then
        DEPTH1=8
    elif [ "$DEPTH2" == "32" ]; then
        DEPTH1=8
    else
        DEPTH1=8
        DEPTH2=16
    fi
fi

LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN "$@"; true

if [ -e $FBSET ]; then
    fbset -depth $DEPTH1 && fbset -depth $DEPTH2
fi
"""
and an temporary link for the video : http://goo.gl/l5RK

C-U

**Comment by popcornmix** [comment]
Got the file. Played it with 
omxplayer GoProHERO3.mp4
No other options. I also tried adding -o local and -o hdmi with no change.
I let it play for a few minutes, and pressed 'q'. No complaints.

Does that fail for you? Every time?

What does "vcgencmd version" report?

**Comment by fcarlier** [comment]
pi@rasp6 ~ $ vcgencmd version
May 17 2013 14:41:27
Copyright (c) 2012 Broadcom
version 4db618758f738458ba904cacc4572be4b094af85 (clean) (release)

Every time ! ;)

**Comment by fcarlier** [comment]
pi@rasp6 ~ $ vcgencmd version
May 17 2013 14:41:27
Copyright (c) 2012 Broadcom
version
'4db618758f738458ba904cacc4572be4b094af85' (clean) (release)

**Comment by popcornmix** [comment]
```
pi@raspberrypi:~ $ omxplayer -o hdmi dell/hang/GoProHERO3.mp4
Video codec omx-h264 width 1920 height 1080 profile 100 fps 29.970030
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
A:PortSettingsChanged: bits:32 mode:0 channels:2 srate:44100 nopassthrough
V:PortSettingsChanged: 1920x1080@29.97 progressive
have a nice day ;)
```

I let it play all the way through and still no complaint. I've committed a few unpushed fixes I had - any change if you update?

**Comment by fcarlier** [comment]
It's excellent. The last commit and my modification is OK :)
The problem is the modification in OMXVideo::Open with the new function OMXVideo::PortSettingsChanged

i modify my version and now, it's so cool :)

issues closed
