### ISSUE TITLE
Picture Cropping

### ISSUE THREAD

**Issue by julianscheel** [huceke/omxplayer#181]
For videos which have slightly garbled picture at the edges (frequently seen on TV broadcasts) it would be nice to have an option to crop some amount from the picture boundaries (ideally some percentage).
I think OMX_IndexConfigCommonInputCrop would be able to handle this?

**Comment by dasced** [comment]
It is possible to crop the picture on the right and the bottom by moving and/or resizing with the --win option. I wish --win 'x1 y1 x2 y2' option accepted negative values for x1 and y1 to be able to crop the picture on the top and left, too.

**Comment by popcornmix** [comment]
Try:
https://github.com/popcornmix/omxplayer/commit/8486405aaf75fe1f7049ac226966996b12adae9c

Should allow something like:
omxplayer --win "-1000 -1000 2000 1500" mnt/Prometheus.Sample.mkv

(make sure firmware is up to date or the negative coordinates won't work)

**Comment by dasced** [comment]
The revision 8486405 works as it should, indeed. Thank you.
