### ISSUE TITLE
omxversion ;)

### ISSUE THREAD

**Issue by fcarlier** [huceke/omxplayer#184]
Hello,

I look a new branch popcornmix separate of huceke ;)
inversion master<->new_stall ;)
Can you explain ?
And
Can you add a omxversion.h with version release ? it's more easy to know the new feature and follow the project.
THX
Florent

**Comment by hehe2** [comment]
Yes, I agree with you, that would be nice to have some "--version" option allowing us to know what build we're running...

**Comment by skgsergio** [comment]
Hi, popcornmix contacted me some days ago to change my builds to his branch. As far as I know currently huceke new_stall branch is the same as popcornmix fork but eventually popcornmix will push updates to his repo.

Anyway this weekend I'm going to make a patch to implement this --version feature :)

**Comment by popcornmix** [comment]
@skgsergio 
Sounds good. I would prefer the version to be a git hash and a build date, rather than a manually incremented version.h file.

**Comment by skgsergio** [comment]
@popcornmix Yes, I'm going to script it. The makefile will generate a version.h that will contain (if possible) the git hash, build date and repo/branch.

Maybe tomorrow (European Time Zone) I'll make a pull request :)

**Comment by fcarlier** [comment]
Excellent ;)
I prefer a incremental build number because the git hash don't permit to know the progression of version.
