### ISSUE TITLE
pipe:

### ISSUE THREAD

**Issue by fcarlier** [huceke/omxplayer#185]
Hello,

Can you explain the pipe: function in https://github.com/popcornmix/omxplayer/commit/75f213a5d71d0bc2d0106824db62d931e0c56c52

How use it the pipe ?

I'm research a little streaming server for raspberry and connect the result with omxplayer.

C-U
Florent

**Comment by popcornmix** [comment]
See:
https://github.com/huceke/omxplayer/issues/51
