### ISSUE TITLE
[ FEATURE SUGGESTION / REQUEST ] Overlay display

### ISSUE THREAD

**Issue by hehe2** [huceke/omxplayer#187]
Hi,

I'd like to see the current "subtitles delay" value displayed as overlay while adjusting it using the shortcuts (d and f keys) because sometimes, you don't know where you actually are and it's taken into account with a slight delay... so you keep adjusting it but the lag makes it hard to get the subtitles really synched...

I also would like the adjustment step not being that "huge" (250 ms is a quarter of a second, which is too much when you run at 24 fps...). I think a value like 100ms or even 50ms would be better. May be adjusting it with "x frames" delay could be nicer ? Don't know at all if that would be relevant...

It's sometimes frustrating to have either the subtitles displayed slightly ahead of the sound or slightly after it and not being able to accurately synch both of them...

Regards and congrats to the dev team !

**Comment by torarin** [comment]
There shouldn't be any delay between pressing d/f and having the timings for the subtitles updated, but you don't know whether your offset is good until the next subtitle, of course.

I'm surprised that you find 250 ms too large. In my experience, the accuracy of subtitle timings are no better than that, so I wouldn't think you gained anything by adjusting by a smaller amount.

If you are sure it is a problem, I'm OK with setting it to 100 ms, but the downside is that it then becomes more tedious to correct larger delays.

**Comment by popcornmix** [comment]
Superceded by:
https://github.com/popcornmix/omxplayer/issues/9
