### ISSUE TITLE
Incorrect surround channel mapping

### ISSUE THREAD

**Issue by antrix** [huceke/omxplayer#188]
Hi.

I have a Sony home theater system connected via HDMI to my raspberry pi. 

When playing a video containing 5.1 surround sound using omxplayer, the channel mapping is incorrect. The Sony system plays the rear left/right channels out of the front left/right speakers. 

This issue happens only for the audio decoded by omxplayer, i.e. either AC3/AAC/DolbyDigital. 

In case of using hdmi passthrough for DTS audio, which the Sony can decode natively, the Sony plays the audio correctly.

The Sony also has no trouble playing the audio correctly when the same files are streamed via DLNA (no transcoding) using Serviio or Plex. 

So I suspect it is an issue with the channel mapping matrix used by omxplayer.

Would it be possible to make this mapping matrix configurable? I know there's ways to do it using alsa/pulseaudio but I don't think omxplayer uses those systems.

**Comment by popcornmix** [comment]
omxplayer only supports 5.1 in passthrough mode. 
Non-passthrough will be sent as stereo PCM.

**Comment by antrix** [comment]
Interesting! A cursory reading of OMXAudio.cpp had led me to believe that omxplayer does support 5.1 output.. there's a lot of channels related code in there!

**Comment by popcornmix** [comment]
It supports 5.1 (or even 7.1) audio, but it will be downmixed to stereo.
