### ISSUE TITLE
MMS Streaming support

### ISSUE THREAD

**Issue by radioactive73** [huceke/omxplayer#19]
Can support for MMS video/audio streams be added? I want to use omxplayer for automatically receiving webcasts. 

I've tried running:
omxplayer -o (hdmi | local) http://stream.url
and
omxplayer -o (hdmi | local) mms://stream.url

Neither seems to work, but both URLs work with Mplayer (not hardware accelerated)

All I get a simple 'have a nice day ;)'  output log below, VC-1 is licensed and works with local files.

Log Reads:

00:00:00 T:0   DEBUG: DllBcm: Using omx system library
00:00:00 T:0   DEBUG: DllOMX: Using omx system library
00:00:00 T:0   DEBUG: DllAvFormat: Using libavformat system library
00:00:00 T:0   DEBUG: DllAvUtilBase: Using libavutil system library
00:00:00 T:0   DEBUG: DllAvCodec: Using libavcodec system library
00:00:00 T:0   DEBUG: DllAvFormat: Using libavformat system library
00:00:00 T:0   ERROR: COMXPlayer::OpenFile - avformat_open_input mms://media.sonoma.edu/pinball.wmv

**Comment by popcornmix** [comment]
I've added support for mmst, mmsh and mmsu in 313b2b8.
Can you try using those instread of mms?

**Comment by vinloren** [comment]
I too am having the same problem. After built the patched omxplayer version now  mmst://media.sonoma.edu/pinball.wmv works nicely, yet the problem persists on the RAI TV (italianTV) urls which are made like this: 
mms://a1273.l6934729272.c69347.g.lm.akamaistream.net/D/1273/69347/v0001/reflector:29272?auth=daEaLckdIcobUbpaRdGcxakbta9cPbybUaz-bqLamp-c0-HlrxvG 
The do not work even using mmst, mmsh or mmsu either.

It's weird to notice that those urls (mms:) work fine if accessed by the omxplayer embedded in raspi XBMC!

Nov 17th 2012
further testing proved mmsh: could play my urls (italian TV)  failing with mms: or mmst:
Problem closed as far as I'm concerned

**Comment by radioactive73** [comment]
Hi popcornmix,

I finally got around to testing the changes and my streams are working perfectly with mmsh, thank you so much! This will get my project rolling nicely, got paypal? I don't mind donating :)

I can close this but I'm not sure if you plan on looking into straight mms for vinloren or not.

**Comment by jester-xbmc** [comment]
I'm trying to stream NASA ISS live stream using omxplayer in raspbmc
mms://a1709.l1856953708.c18569.g.lm.akamaistream.net/D/1709/18569/v0001/reflector:53708

changed the url to mmsh:

no video but audio works:

error output:
6:58:40 T:3037765632  NOTICE: COMXPlayer: Opening: mmsh://a1709.l1856953708.c18569.g.lm.akamaistream.net/D/1709/18569/v0001/reflector:53708
16:58:41 T:2858374208  NOTICE: Thread COMXPlayer start, auto delete: false
16:58:41 T:2858374208  NOTICE: Creating InputStream
16:58:41 T:2858374208  NOTICE: Creating Demuxer
16:58:43 T:2858374208  NOTICE: Opening video stream: 1 source: 256
16:58:43 T:2974807104   ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.video_decode - OMX_ErrorUnsupportedSetting, unsupported setting
16:58:43 T:2858374208   ERROR: COMXCoreComponent::AllocInputBuffers component(OMX.broadcom.video_decode) - OMX_UseBuffer failed with omx_err(0x80001018)
16:58:43 T:2858374208   ERROR: COMXVideo::Open AllocOMXInputBuffers error (080001018)
16:58:43 T:2858374208   ERROR: OMXPlayerVideo : Error open video output
16:58:43 T:2858374208  NOTICE: OMXClock using video as reference
16:58:43 T:2858374208 WARNING: OpenVideoStream - Unsupported stream 1. Stream disabled.
16:58:43 T:2858374208  NOTICE: Opening audio stream: 0 source: 256
16:58:43 T:2858374208  NOTICE: Creating audio thread
16:58:43 T:2833208384  NOTICE: Thread COMXPlayerAudio start, auto delete: false
16:58:43 T:2858374208 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
16:58:43 T:2833208384 WARNING: Previous line repeats 1 times.
16:58:43 T:2833208384  NOTICE: OMXClock using audio as reference
16:58:54 T:2833208384   ERROR: COMXCoreComponent::GetInputBuffer OMX.broadcom.audio_decode wait event timeout

audio stream type WMA2
video stream type Winows Media Video 9 (WMV3)
video resolution: 640x360

**Comment by popcornmix** [comment]
What does this report:
vcgencmd codec_enabled WVC1

**Comment by jester-xbmc** [comment]
_kicks self, prints label dumber than a bag of hammers_ 
ie tricky font in the license key e-mail caused a typo
_runs away in shame_
