### ISSUE TITLE
--win "x1 y1 x2 y2" window size parameter not working

### ISSUE THREAD

**Issue by aquadat0r** [huceke/omxplayer#196]
Hi there,

In the previous versions 0.2.x --win worked perfectly for my specific rtsp stream, but since 0.3.x it always shows the video fullscreen irrespective. Latest version c99bc80 I tested still does not work.

Any help?

Thanks

**Comment by popcornmix** [comment]
Duplicate of https://github.com/popcornmix/omxplayer/issues/41
