### ISSUE TITLE
Playlist black holes between videos

### ISSUE THREAD

**Issue by bdbais** [huceke/omxplayer#198]
Is it possible to remove blackholes between videos on a playlist?
Black screen appear with a Loading icon on left bottom of screen.

Is it possible to create a "pre-loading" system ?
Is it possible to create a transaction effect between videos?
Is it possible to put a logo overlayed?
Is it possible to possible to take RSS feed scrolling on bottom of screen?

thx

**Comment by popcornmix** [comment]
None of these features are planned. If you have implementationed new features you can submit a pull request.
