### ISSUE TITLE
Method to exit cleanly via commandline

### ISSUE THREAD

**Issue by jjmcousineau** [huceke/omxplayer#204]
I am looking for a way to send the command to exit omxplayer through the terminal to facilitate ending one video and starting another.

**Comment by leucos** [comment]
q ?

**Comment by Ruffio** [comment]
@popcornmix are there any plan for this?

**Comment by popcornmix** [comment]
The 'q' key or using dbus to send a quit command are the options.
Anyway, this repo is dead. If there is an issue it should be in popcornmix/omxplayer.
