### ISSUE TITLE
lagging when pause/seek/etc..

### ISSUE THREAD

**Issue by misantronic** [huceke/omxplayer#213]
I am facing an issue with some files when pause/seek/whatever while a file is playing. It then starts lagging. 

I am using a Raspberry Pi with a musicbox pi image (raspian wheezy). Using 128 MB ON GPU, overclocked to 850 Mhz

Here is the mediainfo for two examples:

Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 1.97 GiB
Duration                                 : 2h 5mn
Overall bit rate                         : 2 250 Kbps
Writing application                      : VirtualDubMod 1.5.10.2 (build 2540/release)
Writing library                          : VirtualDubMod build 2540/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings, BVOP                    : 2
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (MPEG)
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 2h 5mn
Bit rate                                 : 1 695 Kbps
Width                                    : 720 pixels
Height                                   : 304 pixels
Display aspect ratio                     : 2.35:1
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.310
Stream size                              : 1.48 GiB (75%)
Writing library                          : XviD 64

Audio #1
ID                                       : 1
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : 2000
Duration                                 : 2h 5mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 344 MiB (17%)
Alignment                                : Split accross interleaves
Interleave, duration                     : 40 ms (1.00 video frame)
Interleave, preload duration             : 500 ms

Audio #2
ID                                       : 2
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Mode                                     : Joint stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 2h 5mn
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 137 MiB (7%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 24 ms (0.60 video frame)
Interleave, preload duration             : 422 ms
Writing library                          : LAME3.98.3

And another:

Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 5.25 GiB
Duration                                 : 1h 45mn
Overall bit rate                         : 7 123 Kbps
Encoded date                             : UTC 2013-08-28 17:58:23
Writing application                      : mkvmerge v6.2.0 ('Promised Land') built on Apr 28 2013 12:22:01
Writing library                          : libebml v1.3.0 + libmatroska v1.4.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1h 45mn
Bit rate                                 : 3 961 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 040 pixels
Display aspect ratio                     : 1.85:1
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.083
Stream size                              : 2.92 GiB (56%)
Title                                    : encounters-iceman_1080p
Writing library                          : x264 core 132 r2310 76a5c3a
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1h 45mn
Bit rate mode                            : Constant
Bit rate                                 : 1 510 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.11 GiB (21%)
Title                                    : German_DTS_1510kbps
Language                                 : German
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1h 45mn
Bit rate mode                            : Constant
Bit rate                                 : 1 510 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.11 GiB (21%)
Title                                    : Englisch_DTS_1510kbps
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:00:00:00.000
00:04:19.301                             : en:00:04:19.301
00:11:25.727                             : en:00:11:25.727
00:19:58.197                             : en:00:19:58.197
00:29:21.551                             : en:00:29:21.551
00:38:07.035                             : en:00:38:07.035
00:45:44.533                             : en:00:45:44.533
00:54:42.821                             : en:00:54:42.821
01:01:02.325                             : en:01:01:02.325
01:09:42.303                             : en:01:09:42.303
01:19:51.745                             : en:01:19:51.745
01:30:39.934                             : en:01:30:39.934

**Comment by popcornmix** [comment]
This repo is dead. Check you have the latest omxplayer (http://omxplayer.sconde.net/)
and if still a problem report here:
https://github.com/popcornmix/omxplayer
