### ISSUE TITLE
Eventual OMXCore.cpp assertion failure

### ISSUE THREAD

**Issue by SleepyBrett** [huceke/omxplayer#214]
I have a few PIs running with a omxplayer looping script that eventually (after 48ish hours) results in the following error:

```
omxplayer.bin: OMXCore.cpp:876: OMX_ERRORTYPE COMXCoreComponent::FreeOutputBuffers(): Assertion `m_omx_output_buffers.size() == m_omx_output_available.size()' failed.
/usr/bin/omxplayer: line 56: 16823 Aborted                 LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
```

I've done a few google searches and have come up pretty empty any suggestions? Seems like the output buffer isn't getting freed correctly.

The script I'm using is one that has been bandied about here and in the forums:

``` bash
#!/bin/bash
SERVICE='omxplayer'

./blank.sh

while true; do
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
sleep 1
else
$SERVICE -o hdmi "$1" &
fi
done
```

Is it possible that one copy of omxplayer.bin just isn't releasing properly at some point? Once a machine enters this state things go a little nuts and I find 1500+ copys of dbus-daemon running.

**Comment by popcornmix** [comment]
That generally occurs when something went wrong earlier meaning the shutdown code is unable to release the buffers (perhaps because OMX isn't in the state it's meant to be in due to an earlier error). Can you run with "-g" and catch the omxplayer.log for that run?

A test case that fails reliably and quickly would be ideal (but I know that may not be easy).

**Comment by SleepyBrett** [comment]
Yeah so far it's wait 48ish hours, I wonder if a shorter video would lead to a quicker result (i.e. does it happen every n launches).

If I set -g will it not get overwritten each run?

**Comment by popcornmix** [comment]
Yes, -g will get overwritten, so have the launching script copy it (e.g. include `date` in destination filename).
Or have it stop on error (e.g. by grepping for the error text).

Also this repo is out of date. Can you confirm you are using recent code (either source from https://github.com/popcornmix/omxplayer or prebuilt from http://omxplayer.sconde.net/).

**Comment by SleepyBrett** [comment]
I'm currently using whatever is being installed by apt in weezy, I'm circling back around to this today so I'll get the logging set up and wait for it to fail.

**Comment by popcornmix** [comment]
May be worth updating to http://omxplayer.sconde.net version. It will be newer than apt-get version and could behave differently.

**Comment by SleepyBrett** [comment]
This may or may not be related. I am still at:

```
        Build date: Mon, 16 Dec 2013 22:06:42 +0100
        Version   : b34143c [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

and I've got rotating logs running trying to catch what leads to the crash above. However I just looked over and saw a black screen. Checking the logs I found the video that was playing was still playing and still generating a log file. I killed it. The log file can be found here: http://islandzero.com/omxplayer.log.17.gz

It seems to be fairly normal until it hits this block:

```
22:55:33 T:1229013907    INFO: CDVDPlayerVideo::Decode dts:6160000 pts:6160000 cur:6160000, size:10790
22:55:33 T:1229014994    INFO: CDVDPlayerVideo::Decode dts:6200000 pts:6200000 cur:6200000, size:10391
22:55:33 T:1229015970    INFO: CDVDPlayerVideo::Decode dts:6240000 pts:6240000 cur:6240000, size:10247
22:55:33 T:1229016897    INFO: CDVDPlayerVideo::Decode dts:6280000 pts:6280000 cur:6280000, size:12993
22:55:33 T:1229017901    INFO: CDVDPlayerVideo::Decode dts:6320000 pts:6320000 cur:6320000, size:14452
22:55:33 T:1229023903    INFO: CDVDPlayerVideo::Decode dts:6360000 pts:6360000 cur:6360000, size:13130
22:55:33 T:1229030074   DEBUG: Normal M:125652 (A:0 V:6360000) P:0 A:-0.13 V:6.23/T:0.20 (0,0,1,1) A:0% V:39% (0.00,0.00)
22:55:33 T:1229050147   DEBUG: Normal M:145742 (A:0 V:6360000) P:0 A:-0.15 V:6.21/T:0.20 (0,0,1,1) A:0% V:45% (0.00,0.00)
22:55:33 T:1229070686   DEBUG: Normal M:166280 (A:0 V:6360000) P:0 A:-0.17 V:6.19/T:0.20 (0,0,1,1) A:0% V:52% (0.00,0.00)
22:55:33 T:1229091117   DEBUG: Normal M:186683 (A:0 V:6360000) P:0 A:-0.19 V:6.17/T:0.20 (0,0,1,1) A:0% V:58% (0.00,0.00)
22:55:33 T:1229111302   DEBUG: Normal M:206851 (A:0 V:6360000) P:0 A:-0.21 V:6.15/T:0.20 (0,0,1,1) A:0% V:64% (0.00,0.00)
22:55:33 T:1229132627   DEBUG: Normal M:228167 (A:0 V:6360000) P:0 A:-0.23 V:6.13/T:0.20 (0,0,1,1) A:0% V:70% (0.00,0.00)
22:55:33 T:1229152539   DEBUG: Normal M:248116 (A:0 V:6360000) P:0 A:-0.25 V:6.11/T:0.20 (0,0,1,1) A:0% V:77% (0.00,0.00)
22:55:33 T:1229172847   DEBUG: Normal M:268336 (A:0 V:6360000) P:0 A:-0.27 V:6.09/T:0.20 (0,0,1,1) A:0% V:84% (0.00,0.00)
22:55:33 T:1229192826   DEBUG: Normal M:288397 (A:0 V:6360000) P:0 A:-0.29 V:6.07/T:0.20 (0,0,1,1) A:0% V:90% (0.00,0.00)
22:55:33 T:1229213206   DEBUG: Normal M:308781 (A:0 V:6360000) P:0 A:-0.31 V:6.05/T:0.20 (0,0,1,1) A:0% V:96% (0.00,0.00)
22:55:33 T:1229235891   DEBUG: Normal M:331493 (A:0 V:6360000) P:0 A:-0.33 V:6.03/T:0.20 (0,0,1,1) A:0% V:99% (0.00,0.00)
22:55:33 T:1229257142   DEBUG: Normal M:352748 (A:0 V:6360000) P:0 A:-0.35 V:6.01/T:0.20 (0,0,1,1) A:0% V:99% (0.00,0.00)
```

Then it just continues like that forever.

**Comment by popcornmix** [comment]
Did a specific file get stuck here (and does it get stuck every time)?
Or does this file normally play, and just once it got stuck?

**Comment by SleepyBrett** [comment]
It played fine at least a dozen times before hanging.

**Comment by SleepyBrett** [comment]
I'm going to close this and open a slightly different failure that we are seeing with omxplayer_0.3.4~git20140212~bf48901
