### ISSUE TITLE
I want to know how to cross-compile the source

### ISSUE THREAD

**Issue by chenyayun** [huceke/omxplayer#215]
I have Ubuntu10.04 and the cross-compile enviroment is ok .
I think it need the userland source .

could you tell me how to ...
Thankyou!

**Comment by skgsergio** [comment]
First of all this repo is outdated, the new source is at https://github.com/popcornmix/omxplayer/

Then I dont know what you mean by userland, a raspbian system with the libs and etc? If is that just use debootstrap.

**Comment by chenyayun** [comment]
Ok, Success!
