### ISSUE TITLE
player should black out the rest of screen behind video

### ISSUE THREAD

**Issue by stevepeart** [huceke/omxplayer#22]
When using omxplayer in an x window system, depending on the ratio of the video, you can still see the desktop above and below the video. It would be cool if omxplayer could black out the screen so this does not happen.

**Comment by XavM** [comment]
My own personal user feed back on this : 

In console mode or after startx, when used with '-r / --refresh', omxplayer blacks out the screen, but doesn't give it back when the video is over.

Conf : 

```
Debian Wheezy 
uname -a : Linux raspberrypi 3.1.9+ #155 PREEMPT Mon Jul 9 12:49:19 BST 2012 armv6l GNU/Linux
/opt/vc/bin/vcgencmd version : Jul  9 2012 13:00:40 
```

**Comment by prashker** [comment]
Cannot confirm -r blacks out the screen as XavM mentioned.

Linux raspbian 3.1.9+ #202 PREEMPT Wed Jul 25 22:11:06 BST 2012 armv6l GNU/Linux

A minor annoyance, however should be addressed.

**Comment by Tamis** [comment]
Like XavM said when using -r it does indeed black out the desktop but once you hit "q" to exit the video you end up with a black screen and no way to get back to desktop.
This is a major annoyance as it forces you to unplug the r-pi.

**Comment by ph0ng** [comment]
@Tamis: did you try `fbset -depth 8 && fbset -depth 16` after exit? This would typically go into your script that runs omxplayer. Or maybe this only works outside X.

**Comment by huceke** [comment]
The only way i'm aware of getting the backgtound black is fbset.

**Comment by ghost** [comment]
I can confirm this. It would be great, if omxplayer could fill the rest of the screen just black without using '--refresh'. '--refresh' has the disadvantage for me that I have to manually select the aspect ratio of my TV (HDMI) everytime I watch a movie. Or does anybody know a workaround for this issue?
fbset works fine to get the video back.

**Comment by Aaronthereason** [comment]
The most simple fix I have found is:
Setterm -cursor off
Omxplayer -o hdmi <video file> | clear

Hope this helps.

**Comment by mwestphal** [comment]
-r / --refresh did not black the screen during video playing.

however Aaronthreason workaround is working.

Should be corrected.

**Comment by dns2utf8** [comment]
I fixed the black screen at the end with an ´xrefresh :0´

**Comment by mwestphal** [comment]
The "black out screen during playback" error should be fixed before closing this issue.

**Comment by popcornmix** [comment]
I've added a -b option to set a black layer just behind the video. This will hide console/X pixels.

Note: this is less efficient that removing the background layer as recommended in this thread.
GPU will be compositing a display with a console framebuffer, a black rectangle and a video layer all present.
https://github.com/popcornmix/omxplayer/commit/957decadfa235497da410e71519cf3c3d2631080

**Comment by puccaso** [comment]
i'm actually looking for the opposite of this fix. lol 
i'm hoping to play omxplayer ontop of the current Desktop, like in the corner somewhere, but it always seems to play with the -b option, even if my init script doesnt mention blanking.

any way to disable blanking?
