### ISSUE TITLE
MP4 files loop hang after few iterations

### ISSUE THREAD

**Issue by ilgala** [huceke/omxplayer#220]
Hi everyone.
I've created an advertising software. It's very simple... The raspberry at startup connects itself to a remote server, look for advertising updates, and if necessary download them locally to play them. The system save all the MP4 files in a specific folder and a script starts a loop playing them.

The problem is that between 10 and less than 100 iterations the loop hangs... This is the code i execute:

``` #!/bin/bash

setterm -cursor off

SERVICE="omxplayer"

while true; do
    if ps ax | grep -v grep | grep $SERVICE > /home/pi/mediaPlayer/mediaplayerLog
        then
        sleep 1;
    else
        sudo sh -c "TERM=linux setterm -foreground black -clear >/dev/tty0"
        clear > /dev/tty1
        files=(/home/pi/mediaPlayer/media/*.mp4)
        omxplayer -r -b -o hdmi  "${files[RANDOM % ${#files[@]}]}"
        xrefresh -display :0
        clear
    fi
done
```

And this is the output on mediaplayerLog which is the same i have when a video hangs...

```
Output mode 16: 1920x1080@60 N:10
ntsc_freq:0
Video codec omx-h264 width 1920 height 1080 profile 77 fps 24.000000
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@24.00 interlace:0 deinterlace:0 par:1.00 layer:0
have a nice day ;)
```

The OMXPlayer build i'm using is:
`omxplayer_0.3.5~git20140624~0be4eec_armhf.deb`

I'm sorry for my bad english and i hope someone can help me with this problem.

**Comment by popcornmix** [comment]
Can you try to reproduce the issue with a single file?
Ideally pick a short file as it will probably hang on start or stop, and so will fail quicker.

If you can get it so a single file hangs reasonable quickly, upload the file (e.g. to dropbox or google driver) and give me a link. I can investigate.

**Comment by ilgala** [comment]
Thanks for your reply. 

Meanwhile I've overcloccked the PI with the "medium" configuration (with the `sudo raspi-config` command) and the loop now appears to be working. I'm going to test it till tomorrow morning (I'm Italian, atm it's 4.37 pm). It's more than double the time the raspberry has to run, but you never know :) 

If it blocks i will try with 1 second video and i will write you the results.

**Comment by popcornmix** [comment]
Is this still an issue with latest omxplayer?

**Comment by ilgala** [comment]
I haven't tried... I've closed the project a lutto e time ago... The pis are using 

omxplayer_0.3.5~git20140624

Filippo Galante
Mail: galante.filippo@gmail.com

**Comment by popcornmix** [comment]
Please open a new issue (should be here: https://github.com/popcornmix/omxplayer/ this repo is dead) if you have a problem with latest version of omxplayer.
