### ISSUE TITLE
running omxplayer via nodejs's exec function

### ISSUE THREAD

**Issue by diederikfeilzer** [huceke/omxplayer#223]
When running proc.exec('omxplayer -o hdmi "http://localhost:8888"'); in a nodes app the hot keys are not working.
The video is playing in fullscreen so in order to stop I have to pull the plug on my Raspberry Pi.
Typing the same line in terminal does give full support.

**Comment by popcornmix** [comment]
What version of omxplayer are you using?
If you launch something else (e.g. nano) via nodejs's exec function, that uses the keyboard can you type into it?
