### ISSUE TITLE
Request: synchronizing multiple players over the network

### ISSUE THREAD

**Issue by ZoranIT** [huceke/omxplayer#224]
Hi!
I need to play videos on several pi's that run in sync with each other over the network.
Videos are stored on the raspberries.
The omxplayer-sync and raspi-video-sync have a small delay between them.
Is it possible to implement some syncing features into the omxplayer so that they play the videos synchronous?

**Comment by popcornmix** [comment]
I don't think this is a common enough feature to add to the default omxplayer, but there is a patch that does what you want here
https://github.com/popcornmix/omxplayer/issues/85

(BTW, this repo is dead, you should use popcornmix/omxplayer for iisues in future).
