### ISSUE TITLE
Webradio problem

### ISSUE THREAD

**Issue by Yacou** [huceke/omxplayer#226]
Hi all.

I've got issues with OMXplayer when I'm trying to listen my own webradio.
It reads normally only one song, then stops.

I tried the last version with apt-get and this one : http://omxplayer.sconde.net/builds/omxplayer_0.3.5~git20140923~6ee9a0a_armhf.deb, both have the same problem.

I use a RPi B+ V1.2 with updated firmware and 5V/2A power supply.
I also have put back the GPU memory at 128Mo.

I've got another RPi (model B 2011/12) with an older version of OMX (can't tell which one, -v arg returns nothing) and with this one, all works fine.

Here are some parts of the OMX logs:

When it works:

http://pastebin.com/JLrUiy1r

And thousands of lines like this until it fails;

when the song finish, I've got this:

http://pastebin.com/nYjsuFAx

(thousands of lines too).

I noticed I've many instances of OMXplayer in htop (on both RPi) while I launch it only once (same thing with MySQL as you can see, or Python scripts), I don't get why it does this (if someone knows…).

https://imagizer.imageshack.us/v2/1653x824q90/540/1dP0B6.png

Sorry for my English and thanks.

**Comment by popcornmix** [comment]
This tree is dead. Create issues here:
https://github.com/popcornmix/omxplayer/
