### ISSUE TITLE
External SRTs with two letters ISO code don't display

### ISSUE THREAD

**Issue by labilbe** [huceke/omxplayer#227]
omxplayer loads automaticaly the SRT file if it has exactly the same name as the video running.

But if the SRT has the name [video-file].fr.srt the SRT won't load.
This feature is implemented in XBMC as well as other players (VLC, MPC...).

It should be great to have this feature inside of it.

**Comment by popcornmix** [comment]
This tree is dead. Create issues here:
https://github.com/popcornmix/omxplayer/

**Comment by labilbe** [comment]
Ok thank you.
