### ISSUE TITLE
Bug omxplayer using livestreamer preventing normal playback 

### ISSUE THREAD

**Issue by expandables2** [huceke/omxplayer#228]
Hi i have the latest omxplayer from http://omxplayer.sconde.net/ and when I am using livestreamer with the original livestream.com it stops the playback every 20 seconds i submit a bug to liverstreamer they said it is an omxplayer bug can you fix it here is the log from livestreamer 

[cli][info] Available streams: 0, 446k (worst, best)
[cli][info] Opening stream: 446k (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1523 to queue
[stream.hls][debug] Adding segment 1524 to queue
[stream.hls][debug] Adding segment 1525 to queue
[stream.hls][debug] Download of segment 1523 complete
[cli][info] Creating pipe livestreamerpipe-2428
[cli][info] Starting player: omxplayer -o hdmi
[stream.hls][debug] Download of segment 1524 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1525 complete
Video codec omx-h264 width 512 height 384 profile 578 fps 30.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 512x384@30.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 layer:0
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1526 to queue
[stream.hls][debug] Download of segment 1526 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1527 to queue
[stream.hls][debug] Download of segment 1527 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
have a nice day ;)

**Comment by popcornmix** [comment]
This repo is dead. Report here:
https://github.com/popcornmix/omxplayer/
