### ISSUE TITLE
MPEG-TS playback freezing

### ISSUE THREAD

**Issue by vozalexander** [huceke/omxplayer#229]
I'm playing an MPEG-TS H.264/AAC network stream (tried both RTMP and UDP). The originating stream is inherently glitchy due to the nature of how it's generated. After a few minutes omxplayer freezes, and I can't restart it without rebooting the RPi - after killing the process, any new omxplayer processes also freeze immediately. tvservice -s or -o commands  also freeze (only after the omxplayer freeze).

I've recorded the stream at a point when this issue occurred - happy to provide it, playing it back via Wowza reproduces the freeze reliably.

**Comment by vozalexander** [comment]
Typical output when frozen:
Video codec omx-h264 width 1280 height 720 profile 100 fps 59.940060
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1280x720@59.94 interlace:3 deinterlace:0 anaglyph:0 par:1.00 layer:0  
[aac @ 0x1444050] invalid band type0k A:  3.11   2.96s/  6.07s Cv:   542k Ca:     0k  
[aac @ 0x1444050] Number of bands (64) exceeds limit (49)..07s Cv:   584k Ca:     1k  
[aac @ 0x1444050] SBR was found before the first channel element.
[aac @ 0x1444050] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x1444050] decode_pce: Input buffer exhausted before END element found
[aac @ 0x1444050] channel element 3.15 is not allocated  6.07s Cv:   345k Ca:     0k  
[aac @ 0x1444050] Number of bands (58) exceeds limit (49).
[aac @ 0x1444050] TNS filter order 29 is greater than maximum 12.
[aac @ 0x1444050] Reserved bit set.0k A:  2.69   1.86s/  6.07s Cv:    63k Ca:     0k  
[aac @ 0x1444050] Number of bands (64) exceeds limit (49)..07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] TYPE_FIL: Input buffer exhausted before END element founda:     0k  
[aac @ 0x1444050] Number of bands (63) exceeds limit (49).
[aac @ 0x1444050] Number of bands (64) exceeds limit (49)..07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] Reserved bit set.
[aac @ 0x1444050] Number of bands (58) exceeds limit (49)..07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] Number of bands (56) exceeds limit (49).
[aac @ 0x1444050] Number of bands (66) exceeds limit (49)..07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] channel element 3.9 is not allocated/  6.07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] Number of bands (60) exceeds limit (49)..07s Cv:     0k Ca:     0k  
[aac @ 0x1444050] Number of bands (64) exceeds limit (49).
[aac @ 0x1444050] TYPE_FIL: Input buffer exhausted before END element founda:     0k  
[aac @ 0x1444050] Number of bands (54) exceeds limit (49).
M:312480074 V:  1.06s      0k/  4800k A:  0.27   0.05s/  6.07s Cv:     0k Ca:     0k

**Comment by popcornmix** [comment]
Yes, upload the sample file and explain what you did to provoke the failure and I'll take a look.

**Comment by vozalexander** [comment]
Link: https://www.dropbox.com/s/rq5x11sbqclzbm1/jigga_gowrie.stream.mp4?dl=0

Didn't do anything specific to provoke the failure - when the incoming stream has strong reception, everything runs perfectly, but when the transmission signal level drops, that results in malformed MPEG-TS, which causes errors above. At some point during this the freeze occurs, I would guess due to some specific form of MPEG-TS corruption which player can't cope with.

Thanks for your help, I really appreciate it - please let me know if I can provide any further information to make troubleshooting easier.

**Comment by popcornmix** [comment]
Yes, I see the problem. The file has a lot of corruption and eventually goes through an assert saying
"it should never happen" and seem to end up with a stack of picture id's containing -1 elements...

Now a few months ago, this would have involved a bug report to the codecs team, and a day or two later a fix would come back. Unfortunately there is no codecs team now (http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=78711).

It's more difficult now. I'll add it to our bug tracker and perhaps at some point we can contract an ex-codecs team to do some work, or someone at Raspberry Pi will have time to understand this code well enough to have a chance of fixing it (we do have access to the code).

But, I'm not sure we'll be able to solve this quickly.

**Comment by vozalexander** [comment]
Thank you so much for quick feedback, even though with bad news. What code are you referring to? Is it open-source? is it part of omxplayer, ffmpeg, raspbian? Would attempting to fix it ourselves or finding someone to do so be an option?

**Comment by popcornmix** [comment]
No it's part of the GPU firmware (start.elf), so this isn't really an omxplayer issue (xbmc crashes in the same way).

**Comment by vozalexander** [comment]
Is there maybe a way to reset the GPU without rebooting the pi, so at least we could recover faster?

**Comment by popcornmix** [comment]
No, the GPU is the master on the Pi. It boots first, starts up the ARM and is capable of resetting the ARM. The arm can't reset the GPU without resetting itself.

**Comment by popcornmix** [comment]
Good news. We've got @deborah-c (who wrote much of the video decoder on the GPU) fixing some bugs for us. I have a test firmware that fixes your example stream.
Could you give it a test, and let us know if any other streams cause similar problems?
https://dl.dropboxusercontent.com/u/3669512/temp/firmware_vozalexander.zip

**Comment by vozalexander** [comment]
That's fantastic news, thank you!

Can you please confirm how to update the firmware using the files you
provided? Do I get the latest master branch and overwrite the files there,
then run rpi-update?
https://github.com/raspberrypi/firmware/tree/master/boot

Warm regards,
Alex

**Comment by popcornmix** [comment]
Just overwriting the contents of boot partition with the zip should work.
If you haven't updated for a while, then rpi-update may be advisable, but be aware that things have changed: http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=9721

**Comment by vozalexander** [comment]
I ran rpi-update, then replaced files in /boot with ones in zip, rebooted,
appears to be working fine. HDMI output working, GPU firmware version shows
as:

Jan 21 2015 20:20:24

Copyright (c) 2012 Broadcom

2433779e6b2d922c3d1fff6101413156e7db747c

I'll test with the source that caused issues tomorrow and let you know how
it went. Thank you and @deborah-c! :)

**Comment by vozalexander** [comment]
The issue has been solved, thank you for your effort!
