### ISSUE TITLE
Video terminates early in version 0.2

### ISSUE THREAD

**Issue by mcrisc** [huceke/omxplayer#23]
Videos are not reaching the end. The log records the following message:

```
00:00:00 T:0   ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.audio_mixer - OMX_ErrorPortUnpopulated (0), cannot parse input stream
```

More details, including a first analysis, can be found at the forum post: 
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=38&t=11817&p=128541&hilit=omxplayer#p128541

**Comment by hp1337** [comment]
I am seeing this issue as well. I am using the official 2012-07-15-wheezy-raspbian.zip image.

**Comment by ph0ng** [comment]
This is actually another symptom of #10. 

It is essential that this bug is fixed soon but if you are building the program yourself, try to apply this fix (works for me) to solve the problem temporarily: https://github.com/huceke/omxplayer/issues/10#issuecomment-6800379

**Comment by torarin** [comment]
How do you reproduce this? None of my files stop early.

**Comment by ph0ng** [comment]
I didn't notice it for a while since I sometimes stop playback in the middle of ending credits (bad habit). But recently I noticed that the ending credits music stopped abruptly just a few seconds before the movie ended. I reproduce it (and confirm the href'd fix) by playing short sample files (H264) and use my PC player as reference. 

I guess that the following lines are supposed to prevent this from happening, but it seems they do not. The _GetCached() == 0_ assertion does a better job. 

```
if(!m_stop && !g_abort)
{
  if(m_has_audio)
    m_player_audio.WaitCompletion();
  else if(m_has_video)
    m_player_video.WaitCompletion();
}
```

EDIT: Without the suggested fix, I get 

> COMXAudio::Decode timeout
> have a nice day ;)

instead of just _have a nice day ;)_ when done. I have only tested this with your subtitles branch but I assume it will be the same with the master branch.

**Comment by torarin** [comment]
Pretty sure I get the whole thing, credits and all. Perhaps someone could upload a sample clip along with some description of where it stops?

**Comment by ph0ng** [comment]
I found [this clip](http://ftp.nluug.nl/ftp/graphics/blender/apricot/trailer/Sintel_Trailer1.720p.DivX_Plus_HD.mkv) which illustrates it well. The clip is actually from [this thread](http://www.raspberrypi.org/phpBB3/viewtopic.php?f=53&t=12076&sid=cdfdd1c342869a68fd09af373fed6c55) in which your help would be useful ;-) You should be able to see "COMING SOON" and the subsequent screen. Without the fix, I get less than half of the trailer. I guess it may vary with different ram splits and what else.

**Comment by torarin** [comment]
Plays all the way to the end for me on Wheezy soft-float with a 128/128 memory split.

**Comment by torarin** [comment]
Ah, if I apply https://github.com/huceke/omxplayer/commit/1de2395792c9c408f0c418a5130edad9f5a5dd91 I get the same behavior. I assume this is the version people are using. Working on a fix.

**Comment by skgsergio** [comment]
Please when reporting an issue don't use my versions number, are useless use the git revision, something like "ec4e7bc4". I only package it and my versions number are useless.

**Comment by ph0ng** [comment]
@skgsergio: Then it would be very useful if you attach the git revision in your packages!

**Comment by skgsergio** [comment]
@ph0ng I do it, in the package name and in the deb version (can be shown with apt-cache policy omxplayer).

**Comment by ph0ng** [comment]
OK :-)

**Comment by maribu** [comment]
Hi everybody!

I have a quite similar problem: While playing (pure) audio files playback stops before the end of the track or at some files just at the beginning. I tried it with torarins version (git clone https://github.com/torarin/omxplayer.git) but still the problem remains. The "uneducated hack" XavM suggested at https://github.com/huceke/omxplayer/issues/10 worked for me.

**Comment by ph0ng** [comment]
@maribu, you should use this branch instead: https://github.com/torarin/omxplayer/tree/stops_early. It is a good idea to verify the patch :-)

**Comment by maribu** [comment]
Oh, my fault.

I'll give it a try! Thank you!

**Comment by maribu** [comment]
Ok, now I can confirm that the patches, once you have applied them, do solve the problem with early stopping audio. Thanks, tararin and ph0ng!

**Comment by marosg** [comment]
@maribu could you please help me with compiing omxplayer ? I am stuck with libswresample, how to obtain it for raspbian.

**Comment by maribu** [comment]
Hey, marosg!

I'm using Arch Linux, so I don't know of how much help I can be. I would try using your package manager to instal missing dependencies. Look if there are two versions of a package, and choose the dev version.

Good luck!

**Comment by skgsergio** [comment]
Hi, I made a .deb pkg for testing the proposed patch that @torarin (See #24). I didn't tried it yet but should work ;)

http://omxplayer.sconde.net/builds/omxplayer_0.2-764877ae-torarin-fix-armhf.deb

**Comment by marosg** [comment]
Sergio,
I appreciate this, I will give it a try in the evening. However, could you tell me how to compile it myself ? I would really like to be able to do that.
Thank you

#  

# Marian Gasparovic 

"The mere thought hadn't  even  begun  to speculate about the merest possibility of crossing my mind."

**Comment by ph0ng** [comment]
@marosg: readme says make ffmpeg first, either try that or use a precompiled binary for your distribution. Further support questions belong in the user forums I believe.

**Comment by marosg** [comment]
ok, so no help for me, nowhere to run. I understand here are skilled people who now the stuff but I really have no idea where to start.
1. Of course I did make ffmeg first as suggested in README. It failed with ./configure not existing.
2. I tried just make, skipping ffmpeg, it compiled some files, then it stopped with unresolved reference to libswresample, which is not in raspbian directory
3. I tried .deb sergio provided above. It requires libavcodes54 and libavformat54. Only *53 are available on raspbian, so I am stuck again.
4. I checked his omxplayer.bin with ldd command, his binary is not using libawresample, so I have no idea why my compile fails on that.

I wanted to give it a try, but it looks like I will become just another user waitng for official packages.

Here is just an example, make ffmpeg failing because ./configure is not there.
HEAD is now at 13a7bd7... lavfi/select: 10l: llabs -> fabs after switching types.
cd ffmpeg; \
    CFLAGS="-D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_HAVE_SBRK -D_LARGEFILE64_SOURCE -DHAVE_CMAKE_CONFIG -DHAVE_VMCS_CONFIG -D_REENTRANT -DUSE_VCHIQ_ARM -DVCHI_BULK_ALIGN=1 -DVCHI_BULK_GRANULARITY=1 -DEGL_SERVER_DISPMANX -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__VIDEOCORE4__ -DGRAPHICS_X_VG=1 -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DOMX -DOMX_SKIP64BIT -isystem/opt/xbmc-bcm/buildroot/output/staging/staging/usr/include -isystem/opt/xbmc-bcm/buildroot/output/staging/staging/opt/vc/include -isystem/opt/xbmc-bcm/buildroot/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include -isystem/opt/xbmc-bcm/buildroot/output/staging/opt/vc/include/interface/vcos/pthreads" \
    LDFLAGS="" \
  ./configure \
            --extra-cflags="-mfpu=vfp -mfloat-abi=softfp -mno-apcs-stack-check -mstructure-size-boundary=32 -mno-sched-prolog" \
            --enable-cross-compile \
            --enable-shared \
            --disable-static \
            --arch=arm \
            --cpu=arm1176jzf-s \
            --target-os=linux \
            --disable-muxers \
            --enable-muxer=spdif \
            --enable-muxer=adts \
            --disable-encoders \
            --enable-encoder=ac3 \
            --enable-encoder=aac \
            --disable-decoder=mpeg_xvmc \
            --disable-devices \
            --disable-ffprobe \
            --disable-ffplay \
            --disable-ffserver \
            --disable-ffmpeg \
            --enable-shared \
            --disable-doc \
            --enable-postproc \
            --enable-gpl \
            --enable-protocol=http \
            --enable-pthreads \
            --disable-runtime-cpudetect \
            --enable-pic \
            --disable-armv5te \
            --disable-neon \
            --enable-armv6t2 \
            --enable-armv6 \
            --enable-armvfp \
            --enable-hardcoded-tables \
            --disable-runtime-cpudetect \
            --disable-debug \
            --cross-prefix=arm-unknown-linux-gnueabi-
/bin/sh: 2: ./configure: Permission denied
make[1]: **\* [configure] Error 126
make[1]: Leaving directory `/mnt/raspi/omx/omxplayer'
make: **\* [ffmpeg] Error 2

**Comment by marosg** [comment]
I am really stupid. I apologize for taking your time and bandwidth, looks like I found it.

**Comment by mcrisc** [comment]
Hi! Did you solve the libavcodes54 problem? I'm thinking of trying the .deb when I get home.

**Comment by ph0ng** [comment]
@marosg: I was simply pointing out that there are several active Raspberry Pi forums, most of them about your distribution or similar. This tracker is (correct me someone if I am wrong) intended for feature requests and bug reports. 

To clarify my previous post: If you cannot build ffmpeg for whatever reason, you can try to install the package (whatever version it has) and build against that one.

**Comment by mcrisc** [comment]
I can confirm the fix works. I was able to watch a 2-hour movie using the binary from skgsergio's .deb mentioned above. Thanks everybody!
