### ISSUE TITLE
Please consider having a library interface for omxplayer

### ISSUE THREAD

**Issue by LongChair** [huceke/omxplayer#230]
I have been willing to use omxplayer on other apps as its probably the best player you can find for Raspberry Pi.

Although from my findings, i found only the following ways to interact with it :

use it from command-line -> this will not allow any sort of integration into any other app).
use the dbus interface -> that will allow to control it once launched, but this adds some dbus dependency, and doesn't allow to get anything really integrated either
make its own wrapper, this is a possibility, although it makes it tricky to get a good overview of all the constraints and work cases, it also makes it harder to stay in line with the original codebase.
So i was wondering if you would / or had already thought about having a way to build it as a library and possibly have something that could be fully reusable from the outside, like a lib in which you would be able to instantiate some player object having the same scope of methods as the actions which are accessible thru dbus or keypresses.

IMHO this would make omxplayer intergration so much easier into any other apps.

**Comment by popcornmix** [comment]
This repo is dead. Use: https://github.com/popcornmix/omxplayer/issues/284
