### ISSUE TITLE
OmxPlayer exits with error in SubtitleRenderer.cpp:133

### ISSUE THREAD

**Issue by kdvolder** [huceke/omxplayer#231]
This error only happens wit one particular vieao file I have. The strange thing is that the first time I play the video file it appears to play fine. If I play the video for even a few seconds, then exit (press 'q') and then play it again I get only a black screen.

If I then press a key like SPACE or right arrow, then OMC player immediately exits with the following error:

```
    omxplayer.bin: SubtitleRenderer.cpp:133: SubtitleRenderer::load_glyph(SubtitleRenderer::InternalChar)::<lambda(FT_Face, VGFont, bool)>: Assertion `!vgGetError()' failed.
    /usr/bin/omxplayer: line 67:  2532 Aborted                 
     LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
```

Other videos seem to still play fine, just this one video no longer plays. This state persists until I reboot my pi. Then I can again play the video once.

The error made me suspect SubTitleRenderer is repsonsible (although the view has no subtitles). I tried adding commandling option --no-osd. And indeed tnen I can continue to play the video (as many times as I like). So this seems to confirm something is going wrong with subtitle rendering/osd machinery.

If there is any further information I can provide to help debug this please let me know.

**Comment by kdvolder** [comment]
Seems I am now getting the same problem on other files as well, what all of them seem to have in common is that they are 1080p videos.

**Comment by popcornmix** [comment]
Most likely lack of gpu_mem. Try setting gpu_mem=128 (or higher) in config.txt.

**Comment by kdvolder** [comment]
Thanks for the tip, I will try that first time I get a chance. Also, I was going to ask which config.txt you mean but I found the answer already: http://www.raspberrypi.org/documentation/configuration/config-txt.md (Just adding the link here, in case anyone else stumbles in here)

**Comment by kdvolder** [comment]
Well, I have increased gpu memory as suggested and not seen the error since. Closing issue.
