### ISSUE TITLE
Seeking causes loss of frames

### ISSUE THREAD

**Issue by Jyang772** [huceke/omxplayer#232]
When I attempt to seek forward more than a minute, omxplayer stops displaying frames. I waited a few minutes and the video still doesn't play. 

I am attempting to view the video on a Raspberry Pi. Video playback works perfectly, when not seeking. 
Has anyone else had this problem?

**Comment by popcornmix** [comment]
This repo is dead. Please report issues here: https://github.com/popcornmix/omxplayer
You'll likely need to supply a sample file (or find a publicly available file that shows the issue) to get it fixed.
