### ISSUE TITLE
omxplayer keeps stopping when plays a network HLS streams while Xbmc/Vlc never stops !!

### ISSUE THREAD

**Issue by rafaelSorel** [huceke/omxplayer#233]
Hello, 

I'm using omxplayer version :
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 24 Oct 2014 00:48:49 +0000
        Version   : 98982df [master]
        Repository: https://github.com/popcornmix/omxplayer.git

And I'm using a http HLS stream: 
(http://8.21.48.19:7777/MBC2_HD/MBC2_High.m3u8)

omxplayer keeps stopping again and again while making the same test with xbmc or vlc the stream never stops.
Here is some logs regarding the stream stops:
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6398957014, dts=6398960614, size=1343
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6398971414, dts=6398975014, size=1135
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6398985814, dts=6398989414, size=1624
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399000214, dts=6399003814, size=1879
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399014614, dts=6399018214, size=1062
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399029014, dts=6399032614, size=1305
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399043414, dts=6399047014, size=2259
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399057814, dts=6399061414, size=1391
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399072214, dts=6399075814, size=1200
[hls,applehttp @ 0x6beab0] Invalid timestamps stream=0, pts=6399086614, dts=6399090214, size=1991
[tcp @ 0xf6b6f0] Connection to tcp://8.21.48.19:7777 failed: Connection refused
[hls,applehttp @ 0x6beab0] Failed to reload playlist 0
[mpegts @ 0x6c32d0] PES packet size mismatch
[tcp @ 0x1064770] Connection to tcp://8.21.48.19:7777 failed: Connection refused
[hls,applehttp @ 0x6beab0] Failed to reload playlist 0
[aac @ 0x6f40a0] decode_band_types: Input buffer exhausted before END element found
have a nice day ;)

Please note that xbmc has also connection refused issue , but it can go on without any cut.

**Comment by popcornmix** [comment]
This repo is dead. Use
https://github.com/popcornmix/omxplayer

But please search - there's a number of issues about HLS, and it's not supported.

**Comment by henkhoo** [comment]
i know its closed, but just for enyone looking for the answer,

would like to add that for m3u8 streams, you want to add timeout option to 60s because else stream will stop every 30seconds or so.


so that would be : omxplayer http://whatever.m3u8 --timeout 60


also you can use omxplayer "http://whatever.url?account=youraccount&whatever=option&file.m3u8" --timeout 60
