### ISSUE TITLE
No sound with fifo

### ISSUE THREAD

**Issue by Yop59** [huceke/omxplayer#235]
Hello,

omxplayer -p -o hdmi "http://xxx.xxx.xxx.xxx:8888/" </tmp/omxplayer_fifo &
sleep 1
echo -n . > /tmp/omxplayer_fifo

Edit and solution:
Do not use "." in "echo -n . > /tmp/omxplayer_fifo" but for example "1234" and everything works

**Comment by popcornmix** [comment]
This repo is dead. If you have an issue report here:
https://github.com/popcornmix/omxplayer/
Make sure you are using a recent omxplayer (e.g. from http://omxplayer.sconde.net/)
I'll probably need a way of reproducing. E.g. a sample file and a script that shows the problem.

**Comment by 6desislava6** [comment]
Yop59 really helped me!
