### ISSUE TITLE
Feature request : display bitmap subtitles

### ISSUE THREAD

**Issue by FlachyJoe** [huceke/omxplayer#236]
Hi,
It seems the structure is there for displaying bitmap image's subtitles (as DVD ones) but it's not implemented.
avcodec_decode_subtitle2 already decode the subtitle stream but only the text output is used and overlayed so bitmaps are just ignored.
I can't do it myself so, please, give it to us !
Many thanks.

**Comment by popcornmix** [comment]
This repo is dead. You should use this:
https://github.com/popcornmix/omxplayer/
