### ISSUE TITLE
problems while Cross compiling omx player

### ISSUE THREAD

**Issue by Sekhar-jami** [huceke/omxplayer#241]
I am facing the following problems while trying to cross compile the omx player on my linux system:

/home/jsekhar/bcm-gcc/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ --sysroot=/home/jsekhar -isystem/include -pipe -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -O3 -mstructure-size-boundary=32 -mno-sched-prolog -std=c++0x -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CMAKE_CONFIG -D__VIDEOCORE4__ -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_OPT_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DHAVE_LIBSWRESAMPLE_SWRESAMPLE_H -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DTARGET_RASPBERRY_PI -DUSE_EXTERNAL_LIBBCM_HOST -isystem/opt/vc/include -isystem/home/jsekhar/usr/include -isystem/opt/vc/include/interface/vcos/pthreads -Ipcre/build -Iboost-trunk -Ifreetype2/include -isystem/usr/include -isystem/opt/vc/include -isystem/home/jsekhar/usr/include -isystem/opt/vc/include/interface/vcos/pthreads -isystem/usr/include/freetype2  -I./ -Ilinux -Iffmpeg_compiled/usr/local/include/ -c OMXCore.cpp -o OMXCore.o -Wno-deprecated-declarations
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:34:22: fatal error: bcm_host.h: No such file or directory
 #include <bcm_host.h>
                      ^
compilation terminated.
make: **\* [linux/RBP.o] Error 1
make: **\* Waiting for unfinished jobs....
In file included from OMXStreamInfo.cpp:22:0:
OMXStreamInfo.h:31:34: fatal error: libavcodec/avcodec.h: No such file or directory
   #include "libavcodec/avcodec.h"
                                  ^
compilation terminated.
make: **\* [OMXStreamInfo.o] Error 1
In file included from OMXOverlayCodecText.cpp:25:0:
OMXStreamInfo.h:31:34: fatal error: libavcodec/avcodec.h: No such file or directory
   #include "libavcodec/avcodec.h"
                                  ^
compilation terminated.
make: **\* [OMXOverlayCodecText.o] Error 1
OMXSubtitleTagSami.cpp:28:38: fatal error: boost/algorithm/string.hpp: No such file or directory
 #include <boost/algorithm/string.hpp>
                                      ^
compilation terminated.
make: **\* [OMXSubtitleTagSami.o] Error 1
In file included from BitstreamConverter.h:26:0,
                 from BitstreamConverter.cpp:26:
DllAvUtil.h:38:34: fatal error: libavutil/avutil.h: No such file or directory
     #include <libavutil/avutil.h>
                                  ^
compilation terminated.
In file included from OMXReader.h:25:0,
                 from OMXReader.cpp:28:
DllAvUtil.h:38:34: fatal error: libavutil/avutil.h: No such file or directory
     #include <libavutil/avutil.h>
                                  ^
compilation terminated.
make: **\* [BitstreamConverter.o] Error 1
make: **\* [OMXReader.o] Error 1
In file included from DllAvCodec.h:27:0,
                 from OMXAudioCodecOMX.h:24,
                 from OMXAudioCodecOMX.cpp:22:
DllAvUtil.h:38:34: fatal error: libavutil/avutil.h: No such file or directory
     #include <libavutil/avutil.h>
                                  ^
compilation terminated.
In file included from OMXCore.h:32:0,
                 from OMXCore.cpp:31:
DllOMX.h:36:25: fatal error: IL/OMX_Core.h: No such file or directory
 #include <IL/OMX_Core.h>
                         ^
compilation terminated.
make: **\* [OMXAudioCodecOMX.o] Error 1
make: **\* [OMXCore.o] Error 1

I would really appreciate it if someone could help me.

**Comment by popcornmix** [comment]
This repo is dead. Try https://github.com/popcornmix/omxplayer/ and report there if still a problem.
