### ISSUE TITLE
Request: dual audio output

### ISSUE THREAD

**Issue by fthiery** [huceke/omxplayer#248]
Hello,

My understanding is that omxplayer currently supports either analog (-o local) or hdmi (-o hdmi); it would be extremely useful to be able to specify both (e.g. -o both); however, would openmax allow this ? Is this feature actually possible ?

**Comment by popcornmix** [comment]
Note: this repo is deal. Use https://github.com/popcornmix/omxplayer/
But, yes, omxplayer does support:
`omxplayer -o both <file>`
