### ISSUE TITLE
omxplery stdout does't sync show

### ISSUE THREAD

**Issue by iahu** [huceke/omxplayer#250]
Hi, I use nodejs spwan module to controll omxplayer. I handle omxplayer's stdout to nodejs process stdout. When I put `-` key to volume down, the volume feedback message not show until nodejs process exited.

``` log
fetching playlist ...
pipe
|> title: White Reply    artist:Akeboshi    length:4:42    like ? No
-
-
-
-
-
-

layer stdout Audio codec mp3 channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
Current Volume: -3.00dB
Current Volume: -6.00dB
Current Volume: -9.00dB
Current Volume: -12.00dB
Current Volume: -15.00dB
Current Volume: -18.00dB
Stopped at: 00:00:10
have a nice day ;)
```

**Comment by jehutting** [comment]
Have a look at  https://github.com/popcornmix/omxplayer/issues/112

> stdout is line buffered.
> Piping will use larger (e.g. 4K) buffers. This is standard linux stuff and not really to do with omxplayer.

**Comment by iahu** [comment]
Thanks @jehutting
