### ISSUE TITLE
Exit code of OMXPLAYER

### ISSUE THREAD

**Issue by romuald-maillet** [huceke/omxplayer#251]
Hello

I think the management of the exit code of omxplayer does not meet the standard .

Therefore, when there is a FileNotFound etc. the exit code is 0 !

The user wants to read the file XXX . Omxplayer meets FileNotFound and the exit code is 0 !!!!

When I ping an address that does not respond , the ping exit code is not 0 .
Why OMXPlayer is not programmed like this
I do not understand what motivated this decision is a shame .

To conclude I will exit 0 if and only if :
1) Action Front exit
2) End playback / analysis

Best regards

Bonjour

Je trouve que la gestion du code de sortie d'omxplayer ne respecte pas le standard.

Pourquoi quand il y a un FileNotFound etc. le code de sortie est 0 !

L'utilisateur veut lire le fichier XXX. Omxplayer repond FileNotFound et le code de sortie est 0 !!!!

Quand je ping une adresse qui ne repond pas , le code de sortie de ping n' est pas 0.
Pourquoi OMXPlayer n'est pas programmé comme ca 
Je ne comprend pas ce qui a motivé cette décision c'est domage.

Pour conclure je dirai exit 0 si et seulement si : 
1) Reception action exit
2) Fin de lecture/analyse

Cordialement

**Comment by jehutting** [comment]
See https://github.com/popcornmix/omxplayer/issues/387 (where this issue is already closed).
