### ISSUE TITLE
HDMI remote

### ISSUE THREAD

**Issue by kaihendry** [huceke/omxplayer#252]
IIUC http://libcec.pulse-eight.com/ allows you to relay Stop/Play/Forward/Back type events through your TV remote to the device. So could omxplayer please support that?

Many thanks,

**Comment by popcornmix** [comment]
This repo is dead. You should use https://github.com/popcornmix/omxplayer/

However it's unlikely to be added to core omxplayer.
omxplayer has support for external scripts/apps to control it using dbus. This means a bash script could be written using cecclient to detect presses and then send commands with dbus.

See: https://github.com/popcornmix/omxplayer/blob/master/dbuscontrol.sh

**Comment by kaihendry** [comment]
Oh ok. Hopefully without sounding too stupid, what does the dbus interface give you over send commands in a fifo?

If you spot a bash script for cecclient, please let me know. Didn't find one today. Maybe because I was looking for `cec-client`. I am unsure what the difference is there or how it's practically used.
