### ISSUE TITLE
How to terminate an omxplayer with kill command?

### ISSUE THREAD

**Issue by hanyuwei70** [huceke/omxplayer#253]
I am developing a program to distribute video signals on rpi and used omxplayer. But when I send SIGTERM to omxplayer it doesn't stop.

There are 2 processes when I run omxplayer

```
/bin/bash /usr/bin/omxplayer rtmp://--/livetv/--.flv
/usr/bin/omxplayer.bin rtmp://--/livetv/--.flv
```

So I send SIGTERM to the first process, it disappeared from `ps`. But second is still alive and the video is still playing.

How can I terminate them both without put a `^C` into stdin?

**Comment by kscorpio** [comment]
ps -ef|grep omxplayer | grep -v grep|awk '{print "kill -9 "$2}' |sh

**Comment by popcornmix** [comment]
omxplayer is a wrapper script - no point in killing that.
omxplayer.bin is the executable and what should be killed.
`killall omxplayer.bin` will problably do what you want.

**Comment by Ruffio** [comment]
@hanyuwei70 I guess you are satisfied with the answears as you havn't commented it any further. Please close this 'issue'.
