### ISSUE TITLE
Receiving a stream from mjpg-streamer

### ISSUE THREAD

**Issue by danielmoreink** [huceke/omxplayer#258]
Hello,

I'm having an issue with OMXPlayer and mjpg-streamer. I'm pretty new to all of this but I promise I tried to find a solution elsewhere before bothering you. But to no avail...

This is what I am trying:
I'm working on an art installation that uses pairs of RPI's (A & B) to stream webcam footage. Pi A runs mjpg-streamer and works fine -- I can watch the stream via VLC from my Computer or the Web-Interface. But if I try to make OMXPlayer play this stream, it's not showing anything. I tried two ways, first by creating a pipe and feed it to the player and secondly to give OMXPlayer the adress of the stream directly (http://IP:8080/?action=stream). Both didn't work.

This is OMXPlayer's output:

```
` $: omxplayer -i -o hdmi 'http://10.0.3.112:8080/?action=stream'

[mjpeg @ 0x1b93bb0] Format mjpeg detected only with low score of 25, misdetection possible!
Input #0, mjpeg, from 'http://10.0.3.112:8080/?action=stream':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 1200k tbn, 25 tbc
have a nice day ;)

```

Trying the same with a mp4-video I put on my server, it works flawlessly.

Do you have any idea what could be the issue? 
Thanks a lot for your work!

Danie

**Comment by popcornmix** [comment]
This repo is dead. Continue in https://github.com/popcornmix/omxplayer/issues/426
