### ISSUE TITLE
-b option is not blanking

### ISSUE THREAD

**Issue by jame-s** [huceke/omxplayer#263]
Build date: Sat, 12 Sep 2015 00:49:19 +0000
Version   : d99bd86 [master]

has this been fixed on a newer build?

**Comment by popcornmix** [comment]
Why don't you try?
http://omxplayer.sconde.net/

**Comment by jame-s** [comment]
tried the latest build as suggested and it doesn't blank either
on an older install, i know version 337004e does blank. i dont know at which version it stopped working.

**Comment by jame-s** [comment]
i did a firmware update and the blanking is working again with the latest version
