### ISSUE TITLE
Programmatically control video playback.

### ISSUE THREAD

**Issue by ProgramErgoSum** [huceke/omxplayer#265]
I would like to play and stop videos by command line options. Is this possible? I do not want to use key board. This is for a demonstration where I want the Pi to use a .mp4 file provided by some other script

**Comment by popcornmix** [comment]
This repo is dead - https://github.com/popcornmix/omxplayer is active.
But really your question has nothing to do with omxplayer.
Just include `omxplayer file.mp4` in your script and it will play file.mp4.
If the question is about writing a bash script then https://www.raspberrypi.org/forums/index.php may be a better place.
