### ISSUE TITLE
Size and Offset

### ISSUE THREAD

**Issue by HKWhyIP** [huceke/omxplayer#27]
Hi,

Would like to have a feature that a video can be scaled and shown with offset.  For example, a video can be scaled down to 50% and shown at the top-right hand corner of the screen.  Therefore, there are spaces left at the left hand side and at the bottom for my other programs.

I have already successfully compiled omxplayer under Raspbian following the instructions provided at github.   Able to modify and compile omxplayer.cpp, OMXVideo.cpp, OMXPlayerVideo.cpp and etc.  However, no matter what I played with the configDisplay, hints, and a few other objects, there was still no change in the video size and offset.

Would anyone give me pointers to how and where I should modify the code?

Thanks a lot!

Kenneth

**Comment by Podmeister** [comment]
I have the same issue. 
Is there a workaround? 
It didn't even have to scale. I'd just like to have a video running in its native resolution in any of the screen's corners.

**Comment by neviaumi** [comment]
I think should modify OMXVideo.cpp.
I have attempt to modify this, it has some changed .
In end of function Open (Around line 590)
I have added following coding:
/_Custom Set_/
  OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
  OMX_INIT_STRUCTURE(configDisplay);
  configDisplay.nPortIndex = m_omx_render.GetInputPort();
  configDisplay.set = OMX_DISPLAY_SET_SRC_RECT;
  configDisplay.src_rect = src;
  omx_err = m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
  if (omx_err != OMX_ErrorNone)
  {
        return false;
  }
  configDisplay.set = OMX_DISPLAY_SET_TRANSFORM;
  configDisplay.transform = trans;
  omx_err = m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
  if (omx_err != OMX_ErrorNone)
  {
        return false;
  }
/_End Custome Set_/

 The src and trans is following structure:
 OMX_DISPLAYRECTTYPE srcCoordinate ;
  srcCoordinate.width = 300;
  srcCoordinate.height = 300;
  srcCoordinate.x_offset = 300;
  srcCoordinate.y_offset = 300;
  OMX_DISPLAYTRANSFORMTYPE transform = OMX_DISPLAY_ROT180;
If you type it into OMXVideo.cpp, you should see the video flip and just show part of video
I also try to modify the dest but not successful

void COMXVideo::setVideoDestSize(OMX_DISPLAYRECTTYPE dest)
{
  OMX_ERRORTYPE omError = OMX_ErrorNone;
  OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
  OMX_INIT_STRUCTURE(configDisplay);
  configDisplay.nPortIndex = m_omx_render.GetInputPort();
  configDisplay.set = OMX_DISPLAY_SET_DEST_RECT;
  configDisplay.src_rect = dest;
  omError=m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
  printf("%s\r\n","i am running!");
}
I call this method before OMXStart();
But it no any effect;
Any people know the issue?
Thanks.
Refer:
http://home.nouwen.name/RaspberryPi/documentation/ilcomponents/prop.html#OMX_IndexConfigDisplayRegion

**Comment by asclepius** [comment]
Any progress on this?  I have a system I would love to port to the pi/omxplayer but I need to be able to play video in a window.

**Comment by popcornmix** [comment]
Added parameter to set the video destination window coordinates:
https://github.com/huceke/omxplayer/commit/5c2f65e37d942973476766c63e599b955b2c72da

Note: video will be stretched to window size, so care must taken in calculating coordinates to maintain aspect ratio.

**Comment by torarin** [comment]
Nice!

**Comment by adks3489** [comment]
Hi, in OMXVideo.cpp
Line 1092: https://github.com/huceke/omxplayer/commit/5c2f65e37d942973476766c63e599b955b2c72da#L2R1092

is the 'if (dx2 <= dx2 || dy2 <= dy1)' correct?
or it should be 'if(dx2 <= dx1 || dy2 <=dy1)'

Thanks.

**Comment by popcornmix** [comment]
@adks3489
Yes.

**Comment by stoneater** [comment]
Is this in one of the builds? Can we use this somehow. I too would like to view multiple security camera feeds via the PI. If I could run 4 instances of omxplayer, each in a separate corner of the screen, this would be perfect. I could then rotate the streams if I desired, via script, while keeping one corner on the door camera.

**Comment by popcornmix** [comment]
http://omxplayer.sconde.net/

seems to have a new enough pre-built version.

**Comment by stoneater** [comment]
That is the one I am using (not the experimental). I tried using the --win x1 y1 etc, with different values for x/y (tried to do an x20 y20 x640 y 480 &etc) and entire screen was taken up by video, and it did not matter if I was in X or cli.

**Comment by stoneater** [comment]
Bloody hell! Found the problem... --win "0 0 1024 768" don't add the x's and y's... Now to run 4 instances and 4 streams at once...

**Comment by stoneater** [comment]
Can sometimes, by running several lxterm windows, and running several omxplayers. Can do one in small window without running x. Have tried running omxplayer with screen to no avail. Tried running as background process (with & or bg), but job is stopped in background. Any ideas? Also, any ideas to show gpu usage in a similar manner as showing cpu usage?

**Comment by mqsd** [comment]
Hi Everyone,
I also want to run 4 instances but I have a small problem, hope you could help.
I manege to compile omxplayer and get --win parameter to work successfully but it only works for one instance. When I play the second instance both of them hang. In another words, the second instance appears on the screen but the video stops in both of them. @stoneater any ideas? thx

**Comment by Grunge** [comment]
need also advise how to use the feature.
would like to play 2 videos (stream from webcams) on a TV (one left, one rigth side).
but when is start the videos (from two terminals) like:
omxplayer --win "0 0 640 480" -r /tmp/stream1.mjpeg
omxplayer --win "700 0 640 480" -r /tmp/stream2.mjpeg

the tv goes to a lower resolution (720x56?) and shows one of the streams.

**Comment by popcornmix** [comment]
Remove the -r parameter.

**Comment by Grunge** [comment]
looks better.
had todo reboot first.
now i have one of the stream in the top-left corner, the other one is still missing somwhere.
is there a possbility to force a 1920x1080 resolution or something to the hdmi port?
Greets and Thank you for the Great work and your answer.

**Comment by popcornmix** [comment]
What's the current resoluion? (tvservice -s)

**Comment by Grunge** [comment]
[HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60Hz, progressive

**Comment by popcornmix** [comment]
Try:

```
omxplayer --win "0 0 640 480" /tmp/stream1.mjpeg
omxplayer --win "700 0 1340 480" /tmp/stream2.mjpeg
```

**Comment by Grunge** [comment]
okay, sorry took me i while. that tv was hanging at a wall, in a other room... now i can see it from my desk...
it looks now like this:
the position is correct (thanks), but i can only see the video that starts first.

**Comment by popcornmix** [comment]
What's your gpu_mem set to? Obviously to play two videos requires more gpu_mem. 
Try with gpu_mem=128.

**Comment by Grunge** [comment]
i did earlier a modification according to http://www.cnx-software.com/2013/01/26/raspberry-pi-now-has-experimental-support-for-vp6-vp8-mjpeg-and-ogg-theora-video-codecs/.
maybe thats why i'm in trouble.

**Comment by popcornmix** [comment]
What do you have gpu_mem set to in config.txt? If it's not specified it will be 64M, which is not enough for two video players.

**Comment by Grunge** [comment]
It wasn't specified.
but i added gpu_mem=128.
but without success.
if i stop the omxplayer that started first, i can immediately see the video from the second started player.

**Comment by aquadat0r** [comment]
Hi all, great work. I'm also trying to get the multiple instances to work, but still no luck. I actually want to stream four rtsp streams to different areas on the screen, 2x2 grid. but so far, i can only see one at a time.

Any ideas?

**Comment by mqsd** [comment]
Just install the latest version http://omxplayer.sconde.net/ on raspbian, it worked for me. I run 4 and 6 independent instances with rtsp video resolution 720x576 and 640x480 and it works perfectly. Even tried to run 4 HD streams, it also worked but not so good:)

**Comment by aquadat0r** [comment]
Thank you, will try it tonight

Kind regards,
Johan

**Comment by aquadat0r** [comment]
@mqsd What specific command line parameters are you using for this?

**Comment by mqsd** [comment]
something like this: /usr/bin/omxplayer --win "0 0 720 576" rtsp://... where 0 0 are X and Y coordinates (left-top corner) and 720 576 are video resolution. To play another instance you should change que --win parameter to "720 0 1440 576"
Dont ask me why 1440, i belive the calculations are wrong in the code but only Works like this. hope this helps. Regards

**Comment by aquadat0r** [comment]
@mqsd thank you, are you able to running multiple instances from a single console or startup script? I'm actually struggling with that

**Comment by shuckle50** [comment]
I just tried this with two small files (mjpeg) and I also get serial execution. The other omxplayer starts only after the first has been stopped.
How to get them run at the same time in parallel?
(Basically this discussion probably should happen in issue 35 as issue 27 actually works fine?)

**Comment by aquadat0r** [comment]
@mqsd, @shuckle50, @huceke 
Hi all, I managed to figure this out. I have multiple 720p streams running in a 2x2 grid configuration with easy, only consuming around 15% CPU at its peak. I have posted the solution on my blog. http://t3chadd1ct.wordpress.com/2013/04/19/omxplayer/

**Comment by shuckle50** [comment]
Tried it, but it is still sequential. 
Screen command goes fine immediately, but the other omxplayer screen only comes visible after the first ends. I wonder if this depends on kernel or firmware version?

Mine are:
$ vcgencmd version
Mar 24 2013 19:39:03
Copyright (c) 2012 Broadcom
version 379325 (release)

$ uname -a
Linux raspberry4 3.6.11+ #399 PREEMPT Sun Mar 24 19:22:58 GMT 2013 armv6l GNU/Linux

**Comment by aquadat0r** [comment]
have you done sudo apt-get update; sudo apt-get upgrade; sudo apt-get dist-upgrade recently?

**Comment by aquadat0r** [comment]
@shuckle50 can you confirm that the first command actually runs from the background? can you start the second command from a different terminal session?

**Comment by aquadat0r** [comment]
$ vcgencmd version does not return anything for me
$ uname -a
Linux raspbmc 3.6.11 #2 PREEMPT Wed Mar 13 17:12:47 UTC 2013 armv6l GNU/Linux

**Comment by aquadat0r** [comment]
ok, got it.
Mar  7 2013 19:34:17
Copyright (c) 2012 Broadcom
version 375458 (release)

**Comment by aquadat0r** [comment]
Ok, I tried the lastest raspbian image and everything is still working 100%. Later kernel but older Broadcom drivers. Will now try night build drivers next.

$uname -a
**Linux raspberrypi 3.6.11+ #371 PREEMPT Thu Feb 7 16:31:35 GMT 2013 armv6l GNU/Linux**

Feb  7 2013 16:46:17
Copyright (c) 2012 Broadcom
**version 367974 (release)**

**Comment by aquadat0r** [comment]
Hi, just tried it once more on latest stable firmware available (rpi-update script). Still working 100%.

Linux **raspberrypi 3.6.11+ #414** PREEMPT Thu Apr 18 02:00:59 BST 2013 armv6l GNU/Linux

Apr 18 2013 02:23:00
Copyright (c) 2012 Broadcom
version **384972** (release)

**Comment by shuckle50** [comment]
Seems like I can not increase the amount of gpu_mem. This is due to a known corruption bug in recent firmware. I need to recover from backup. But the issue for me likely is the amount of gpu_mem.
How much gpu_mem do you have?

**Comment by shuckle50** [comment]
I was able to recover the corruption and set the gpu_mem to 128M, but still sequential. Amazing that it works for you.
I will build another SD card from scratch and test that, Maybe I have bad omxplayer version.
I am using omxplayer_0.2.5~git20130326~5b369233_armhf.deb.

**Comment by Grunge** [comment]
Hi again

i updated the firmware from

version 381148 (release)
to
version 384971 (release)
and did all upgrades.

but still have the same behavior.
i like to play to mjpeg stream parallel, but the only can be played serial.

i access the streams like these:
wget -O /tmp/stream1.mjpeg 'http://IP_ONE/axis-cgi/mjpg/video.cgi' &> /dev/null &
wget -O /tmp/stream2.mjpeg 'http://IP_TWO/axis-cgi/mjpg/video.cgi' &> /dev/null &  

and start the players like this:
nohup omxplayer --win "960 0 1920 720" /tmp/stream2.mjpeg &
nohup omxplayer --win "0 0 960 720" /tmp/stream1.mjpeg &

for clean up i do:
killall omxplayer.bin
fbset -depth 8 && fbset -depth 16 &
rm /tmp/stream*.mjpeg

i have  
383752 total of mem so i assume, the rest is used for the gpu.

if you like and if it helps, i can give you access to the streams.
maybee i should compile the player myself?
i used this one: (http://omxplayer.sconde.net/) 
http://omxplayer.sconde.net/builds/omxplayer_0.2.5~git20130326~5b369233_armhf.deb
because i'm lazy.
Greetings and have a nice weekend

**Comment by aquadat0r** [comment]
maybe it is birate/bandwitdh related. what is the rate of your streams?

**Comment by shuckle50** [comment]
I have been testing with P1020080.MOV from 
http://www.dvxuser.com/V6/showthread.php?170183-Untouched-Motion-JPEG-720-30P-Sample
Which I got from 
http://www.cnx-software.com/2013/01/26/raspberry-pi-now-has-experimental-support-for-vp6-vp8-mjpeg-and-ogg-theora-video-codecs/

Can you, please, verify that this file can be run parallel in your system? Maybe it is the size change that prevents parallel?

**Comment by popcornmix** [comment]
@shuckle50 
I think the MJPEG decoder may be the one codec that grabs a lock on the jpeg stills decoder, and so can't run in parallel.Try with a different codec to confirm that works correctly.

I'll investigate grabbing the jpeg lock per frame which should make this possible when I get a chance.

**Comment by shuckle50** [comment]
Hi, thanks !
It indeed works with another test file, which is not JPEG. (VLC shows with H264 - MPEG-4 AVC (Part 10) (avc1))
Nice to know that there is reason for this. Unfortunately my web cams are feeding only mjpeg (through zoneminder), so I can't use this yet.

Is that locking happening in omxplayer? Or in the GPU?

**Comment by popcornmix** [comment]
In the GPU,

**Comment by shuckle50** [comment]
ok, I can't much help then. Good luck with fixing it.

**Comment by Grunge** [comment]
Heia
I'm glad that the issue is confirmed.

@popcornmix: 
Any Idea when the bug will be fixed in the Firmware?

Thanks to all for your help and work.

**Comment by juanmoura** [comment]
How can I pass the coordinates x1, y1, x2, y2 as variables?

I've tried everything here and it's not right. Continues or does not execute, or when executed, assigns the variable name as coordinates.

Ex: screen -dmS stream2 sh -c 'omxplayer --refresh --win "$CAM02" rtsp://admin:@suportern@@10.8.9.82:554/Streaming/Channels/102'

If i do:
TEST="screen -dmS stream2 sh -c 'omxplayer --refresh --win "$CAM02" rtsp://admin:@suportern@@10.8.9.82:554/Streaming/Channels/102'"

And: echo $TEST

i will see with the coordinates "0 0 640 480" correctly, but when i put:

$TEST do nothing.
