### ISSUE TITLE
Opencv implementation

### ISSUE THREAD

**Issue by radrajith** [huceke/omxplayer#275]
Hi,

I have been using omxplayer for openning a rtsp live stream from ip camera. Omxplayer is the only player that works without any lag on my raspberry  pi2. I would like do facial recognition on the feed using opencv, however opencv has a lot of lag and latency. Is there anyway Omxplayer can be used as for decoding the h264 stream and input that to the opencv. If there is any way to convert the rtsp feed to mp4 or something using omxplayer, that will be helpful as well. 

Thank you,
Raj

**Comment by popcornmix** [comment]
No. omxplayer is a gpu based player - the video is decoded, scheduled and rendered on the gpu with the arm never seeing the decode pixels.
As such it would not be the right approach for use with opencv.
