### ISSUE TITLE
Ffmpeg and omxplayer

### ISSUE THREAD

**Issue by matteoraggi** [huceke/omxplayer#276]
Which rules should I follow to make works well the mp4 created with ffmpeg into omxplayer?
If I create videos from shotcut and openshot for omxplayer, it is all right.
If instead I create videos from ffmpeg then I can't see the videos on omxplayer.
I am using raspbian 8 pixel with raspberry 3 model b and the default omxplayer installed in this os updated and upgraded at the last version.
I create the mp4 file with ffmpeg trough this command:
`ffmpeg -r 1/5 -i frame_%04d.png -s 1080x1920 -vcodec libx264  -pix_fmt yuv420p -preset fast -crf 18 -b-pyramid none -acodec ac3 -ab 1536k -scodec copy  -r 30 omxplayer.mp4`
And omxplayer then answer to me only this line of text and doesn't play:
`video codec omx-264 width 1080 height 1920 profile 100 fps 25.000000 Subtitle ount : 0, state : off, index: 1, delay: 0`
Here attached the 2 log files: NO is the log of the not working file (generated with ffmpeg) and YES is the working well file.
[NO.log.txt](https://github.com/huceke/omxplayer/files/687466/NO.log.txt)
[YES.log.txt](https://github.com/huceke/omxplayer/files/687467/YES.log.txt)

**Comment by popcornmix** [comment]
Can you post mediainfo output of omxplayer.mp4?
Or just provide a link to a sample file I can test?

**Comment by matteoraggi** [comment]
I moved the GPU from 64 to 128 Mb and now it plays well!
