### ISSUE TITLE
Connection between ffmpeg and omxplayer

### ISSUE THREAD

**Issue by matteoraggi** [huceke/omxplayer#278]
In your files I read not rarely some connections between omxplayer and ffmpeg, which connections could be?
omxplayer is just a player and ffmpeg is a video producer. I don't see big connections.
I am going to test a full hd video screen recording from ffmpeg to omxplayer while playing from raspbian 8 on raspberry pi 3 model b. any suggestions?

**Comment by popcornmix** [comment]
Duplicate of https://github.com/popcornmix/omxplayer/issues/524
