### ISSUE TITLE
Video resolutions higher than 1920x1080 are incompatible?

### ISSUE THREAD

**Issue by bp2008** [huceke/omxplayer#280]
I've been trying to stream my IP cameras to omxplayer, and it works fine with 1920x1080 and smaller resolutions, but fails with higher resolutions like 2048x1536, 2688x1520, and 3840x2160.  Nothing but video corruption when trying to stream these higher resolutions.  Actually, a 3840x2160 stream blacks out the monitor even if I told omxplayer to output to a window region.  I'm guessing this is a limitation of the raspberry pi's hardware decoding, and nothing can be done about it?

Using a raspberry pi 2 for this, though someone else was having the same problem with a pi 3.

**Comment by ozett** [comment]
👍 
same issue with my raspi2 and my axis-cam over rtsp.
i have a scrambled image on omxplayer-stream in 4mp resolution (2688x1520),
while the same on my pc with vlc it works perfectly.

a full-hd resolution works on my raspi
(omxplayer --fps 5  --aidx -n rtsp://root:root@192.168.14.4/axis-media/media.amp?resolution=1920x1080)

anybody could help with information about this?

(increase gpu-size, get a raspi3?)

**Comment by popcornmix** [comment]
The Pi video decode hardware is designed for up to 1920x1080 resolution.
It does not support higher resolutions, so omxplayer cannot.

**Comment by ozett** [comment]
my goal was to rotate everything at 90 degree,
grab the axis rtsp-stream of 2688x1520
and show the upper half in 1920x1080 on one rasperry
and show the lower half in 1920x1080 on a second rasperry.

i managed to to this with another cam in 1280x720, 
but with omxplayer on the axis-cam  i am stuck to grab only 1920x1080 from the cam via url.

is there maybe another way to achieve my goal with omxplayer ❓ 

thanks for helping me out,
tozett

**Comment by popcornmix** [comment]
If the encoded video resolution is 2688x1520 then the Pi cannot decode it.
You could perhaps use a desktop PC to decode the 2688x1520 video and re-encode to two separate 1920x1080 streams which the Pi's could then play.
