### ISSUE TITLE
Would jpeg, png, bmp image displaying be of interest to anyone using omxplayer

### ISSUE THREAD

**Issue by Roberiopraciano** [huceke/omxplayer#290]
**Would jpeg, png, bmp image displaying be of interest to anyone using omxplayer?

I know there are other many image viewers out there, but I would like to resort to a single application for the purpose of media center I'm trying to put together - not using openELEC or XBMC at all. Currently I'm running fbi (in console) to show images and omxplayer to play videos.

Another solution would be to create a video from a single image - not sure how to do that. In fact it would probably be the best thing to do, with least coding - It would even make showing multi-page PDFs appear as a smooth slideshow (after they are converted to pngs) :)**

**Comment by minhajakhterkhan199** [comment]
I am also facing the same issue... I suggest Omxplayer team to integrate functionality that display images as well... 
I am sure that omxplayer popularity will grow more, if omxplayer also display images... In addition, alot of developers will be benefited by this feature.

**Comment by popcornmix** [comment]
omxplayer is designed for playing video that is hardware decoded by GPU.
It has no support for software decoded video or images and none is planned.

There are many image viewers in the debian repo which will do what you want.
