### ISSUE TITLE
Player assumes square pixel aspect ratios

### ISSUE THREAD

**Issue by opensiriusfox** [huceke/omxplayer#3]
Currently when presented with a video using non-square pixel aspect ratios OMXPlayer will simply treat the video as having square pixels resulting in distorted video when playback occors. For many video types this is not an issue, but for videos coming from DVD sources where the source videos are all the same size then are distorted using non-square pixels to their intended dimensions, this is the norm.

**Comment by huceke** [comment]
Can you provide a sample video for that ?

**Comment by opensiriusfox** [comment]
Indeed I can. This video ([Dropbox Link](https://www.dropbox.com/s/prqx97zjxc5keba/Fellowship%20of%20the%20Ring%20Test.m4v)) when played with Quicktime, Mplayer, or VLC will be shown at 848 by 360 on the display, but the actual video stream behind it is 716 by 360. This is referred to as an anamorphic video.
