### ISSUE TITLE
Error: a8

### ISSUE THREAD

**Issue by ThatsFluke** [huceke/omxplayer#305]
When trying to run a downloaded video in omxplayer, it just says:
Vcodec id unknown: a8
have a nice day ;)
That's all it says, I've done some research and it says I need h.264 encoding but I have a Pi 3 B+ which has and supports that. Do I need to install any packages? The weirder thing is around a month ago I used the same custom-built os (Based on Raspbian minimal) And could cast youtube videos to my pi via ssh on my tablet.
By the way, I'm on a Raspberry Pi 3 B+. I used popcornmix's pi version.
Please help! I am trying to build something similar to google chromecast (Has wireless display and AirPlay support and im trying to do more) !

**Comment by popcornmix** [comment]
This repo is dead - use the popcornmix one.
