### ISSUE TITLE
play rtmp video sometimes fails

### ISSUE THREAD

**Issue by rklass** [huceke/omxplayer#307]
Dear experts, 
when I  play an rtmp stream in omxplayer, sometimes it just plays only the audio and no video. The message in omxplayer is normally like this (that means video is found):

Video codec omx-h264 width 1920 height 1080 profile 100 fps 30.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@30.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255   aspectMode:0_

When it fails (bringing only audio) it is only

Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0

I tried all combinations of --timeout and -- threshold, but it is not helping. I wait 15 sec after start of the rtmp stream, before I start omxplayer (to be sure, that my stream is ready), the problem also happens from time to time (once in 10). 

I have no idea, how to solve it ! Is there any possibility to force omxplayer to play video **and** audio always ?

Many greetings
Reinhold

[omxplayer.log_nok.txt](https://github.com/huceke/omxplayer/files/5164662/omxplayer.log_nok.txt)
[omxplayer.log_nok1.txt](https://github.com/huceke/omxplayer/files/5164663/omxplayer.log_nok1.txt)
[omxplayer.log_ok.txt](https://github.com/huceke/omxplayer/files/5164664/omxplayer.log_ok.txt)

**Comment by rklass** [comment]
Logfiles are enclosed: 
nok means: only audio is coming through
ok means: video and audio coming through

**Comment by popcornmix** [comment]
This repo is dead. https://github.com/popcornmix/omxplayer is more up to date
but even there omxplayer has been deprecated in favour of vlc.
Does your stream work with vlc?
