### ISSUE TITLE
Omxplayer is not a available in apt source,and libWFC.so is missing.

### ISSUE THREAD

**Issue by wiselot** [huceke/omxplayer#312]
Omxplayer is not a available in apt source,and libWFC.so is missing.
When I try to install omxplayer through 'apt install' , I got
Package omxplayer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'omxplayer' has no installation candidate

then I download the file ' omxplayer_0.3.7~git20160923~dfea8c9_armhf.deb' ,run 'dpkg -i',and start to play an Internet Radio,I got
'...libWFC.so':No such file or...
My Raspi A+ doesn't allow me to compile and install libWFC(gcc spend much time to build it),so,How can I install it?

**Comment by popcornmix** [comment]
It's probably worth reading the README of this repo, then the README of the repo that replaces this.
But omxplayer is no longer supported.

**Comment by wiselot** [comment]
OK,I have turned to mplayer.
