### ISSUE TITLE
Display warning if VideoRam is insufficient

### ISSUE THREAD

**Issue by dns2utf8** [huceke/omxplayer#33]
Hi,

On a Raspberry Pi you have to choose how to split your RAM.
With huge media-streams you need 128MB for vRam. If you don't know that, you will hear the sound, but you will never see a picture.

Thanks

**Comment by ph0ng** [comment]
This is already in the logging mechanism, look in omxplayer.log for

> ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.video_decode - OMX_ErrorInsufficientResources, insufficient resources

The program is not very verbose on stdout, for example you get no message if the input file does not exist.

**Comment by GriffenJBS** [comment]
This is a very common problem in the irc channels, maybe a flag could be set on any detected errors, and a message printed before the 'Have a nice day' message to check the logs, most people don't know they exist.

Having said that there are many common failure modes that are not well reported. Usually with low RAM, the audio plays, and video is black, that doesn't help the typical user. Of the few who do read the log, many end up in irc asking what it means.

**Comment by popcornmix** [comment]
Added in:
https://github.com/popcornmix/omxplayer/commit/af28ef87eb9e810838d77246288c9d3443bddc80
