### ISSUE TITLE
Assertion error on program exit

### ISSUE THREAD

**Issue by ph0ng** [huceke/omxplayer#34]
I am getting the following assertion error from time to time when exiting the program using the 'q' button: 

> omxplayer.bin: OMXCore.cpp:749: OMX_ERRORTYPE COMXCoreComponent::FreeOutputBuffers(bool): Assertion `m_omx_output_buffers.size() == m_omx_output_available.size()' failed.

After spending some time looking for a solution, I gave up and thought that it was better to let @huceke or @torarin take a look at it ;-)

On a normal exit, m_omx_output_available.size() and m_omx_output_available.size() are always 1. But once in a while m_omx_output_available.size() is 0, causing the assertion to fail (and my terminal to break for some reason). 

Furthermore, the normal sequence for manipulating m_omx_output_available when quitting is

```
OMXCore.cpp:1436 | m_omx_output_available.push(buffer)
OMXCore:cpp:749  | assert(m_omx_output_buffers.size() == m_omx_output_available.size())
OMXCore.cpp:771  | m_omx_output_available.pop()
```

and when failing: 

```
OMXCore.cpp:1436 | m_omx_output_available.push(buffer)
OMXCore.cpp:526  | m_omx_output_available.pop()
OMXCore:cpp:749  | assert(m_omx_output_buffers.size() == m_omx_output_available.size())
```

I believe the call to m_omx_text.GetOutputBuffer(10) from COMXVideo::GetText() is what causes the pop on OMXCore.cpp:526. 

The issue is fairly easy to reproduce, seems to happen on every fifth run or so. I found a similar problem here: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=12127

**Comment by torarin** [comment]
I have seen that assertion error before, but I can't for the life of me reproduce it now. In any case, it's a side effect of the old subtitle code which isn't used anymore, so I guess we should just rip that all out. The assert itself breaks the terminal because omxplayer's termios trickery isn't properly cleaned up.

See if this doesn't fix things: https://github.com/torarin/omxplayer/tree/remove_old

**Comment by torarin** [comment]
I wonder if @huceke could chime in on the following:
- `COMXCoreComponent::Deinitialize()` calls `FlushAll`. Why? Changing state to `OMX_StateIdle` should already flush buffers.
- `COMXCoreComponent::DecoderEmptyBufferDone` and `COMXCoreComponent::DecoderFillBufferDone` don't push their buffers if `m_exit == true`. Presumably, this causes the assertion above to trigger. Why can't they push on deinitialization?
- In `COMXCoreComponent::Deinitialize()`, why is the state set to `OMX_StateIdle` twice, both before and after `Free(Input|Output)Buffers`?

**Comment by ph0ng** [comment]
Seems to do the trick!

**Comment by ph0ng** [comment]
I guess you would need to open a pull request to get @huceke's attention. I've been running this for several days without any problems.

**Comment by torarin** [comment]
I will, I just wanted to investigate it a bit further.

**Comment by popcornmix** [comment]
Anyone still seeing this? Can you post a sample file that causes it if you do?
