### ISSUE TITLE
Allow multiple instances of omxplayer running

### ISSUE THREAD

**Issue by jmrunge** [huceke/omxplayer#35]
Hi, 
I would like to use my Raspberry Pi for video survelliance.  For that, I would need to show up to 4 cameras (getting video via stream from the camera) in the screen.  Is there a way of showing 4 instances of omxplayer, each one with his own x and y on the screen and its own size? Can it be done? The streams are low resolution, so I think the GPU will be able to decode them in simultaneous.  Please let me know if I'm asking something undoable or stupid...

Thanks in advance,

**Comment by rebroad** [comment]
Issue #27 will, if done, provide the ability to do this.

**Comment by jmrunge** [comment]
Thanks! Will follow this issue to see if it gets done!
