### ISSUE TITLE
Problem returning to original resolution after using -r flag

### ISSUE THREAD

**Issue by a-downing** [huceke/omxplayer#4]
Running 'omxplayer -r movie.mkv' seems to work as intended, but after quitting or finishing the movie I get a blank screen. The resolution does seem to return back to the original, but the screen is blank forcing a reboot. Everything still works, I just can't see what I'm doing.

**Comment by huceke** [comment]
omxplayer is  sctipt. Look at it.

**Comment by a-downing** [comment]
Very good, problem solved. The Archlinux PKGBUILD I used copies omxplayer.bin to /usr/bin/omxplayer and does not install the script at all. Blindly running 'fbset -xres 1920 -xres 1080' does indeed make my console visible again. I'll let the package maintainer know. Thank you.
