### ISSUE TITLE
DVD folder/iso support

### ISSUE THREAD

**Issue by epideme** [huceke/omxplayer#40]
"COMXPlayer::OpenInputStream - DVD/BD not supported"

Now that RPi released official support for MPEG2 and VC1, and given the fact that omxplayer works well with MPEG2 VOBs, it would be nice with basic DVD support. Not nessecarily full menu support, even though it would be nice. Just main feature playback of VIDEO_TS and ISO's would be a great initial step.

**Comment by Hexagon** [comment]
Agreed!

**Comment by huceke** [comment]
Patches welcome.

**Comment by flipdee** [comment]
Would this cover BD menus too?

**Comment by ghost** [comment]
Hopefully you can also fix the subtitle alligment. I am curious if this is hard to fix? Thanks a lot for all your work!
Example subtile allignment after enabling the DVD support again: http://img690.imageshack.us/img690/6271/subsm.jpg

**Comment by zanardi1982** [comment]
It would be really important to develop a DVD player with basic functions.
Initially for me it is sufficient that between a file and the other were not lost the language settings. It 'a problem to set the audio language every 20 minutes.

**Comment by akerbos** [comment]
That would be cool. I have more than one movie as ISO (legally, mind). 

Of course, we can always wrap 
- mounting the image/disk somewhere,
- iterating over the videos and
- unmounting

in a script. Language, subtitle settings etc can be passed to every run of `omxplayer` itself. I think I'll try and set something up.

**Comment by popcornmix** [comment]
XBMC does support playing the feature from DVD folder/ISOs
