### ISSUE TITLE
Unable to play WMV3 files

### ISSUE THREAD

**Issue by dupondje** [huceke/omxplayer#42]
19:32:15 T:1205216352    INFO: ffmpeg[47D62460]:   Duration: 00:42:01.90, start: 0.000000, bitrate: 3150 kb/s
19:32:15 T:1205216352    INFO: ffmpeg[47D62460]:     Stream #0:0(eng): Audio: wmav2 (a[1][0][0] / 0x0161), 44100 Hz, 2 channels, s16, 96 kb/s
19:32:15 T:1205216352    INFO: ffmpeg[47D62460]:     Stream #0:1(eng): Video: wmv3 (Main) (WMV3 / 0x33564D57), yuv420p, 1280x720, 3049 kb/s, 30 tbr, 1k tbn, 1k tbc
19:32:15 T:1205216352  NOTICE: Opening video stream: 1 source: 256
19:32:15 T:1205216352   DEBUG: OMXClock::OMXStop
19:32:15 T:1205216352   ERROR: OMXPlayerAudio : Error open video output
19:32:15 T:1205216352   DEBUG: OMXClock::OMXReset 0x00000003
19:32:15 T:1205216352  NOTICE: OMXClock using video as reference
19:32:15 T:1205216352 WARNING: OpenVideoStream - Unsupported stream 1. Stream disabled.

I'm unable to play wmv3 files with my RPi.
The wmv3 codec should be supported when the VC1 license is installed.

**Comment by popcornmix** [comment]
This should be supported. Please report if not working.
