### ISSUE TITLE
full screen mode 

### ISSUE THREAD

**Issue by sylverboss** [huceke/omxplayer#44]
Hello,

How can I play all videos in full screen mode ? 

At the moment some videos are stretched horizontally leaving top and bottom desktop visible .. 

Thank you

**Comment by neviaumi** [comment]
omxplayer -r /Path/Of/Your/Video
(But i found that has bug in my case.After video finish, i cannot go back to my shell.)

**Comment by sylverboss** [comment]
Hi ,

I tried that but same result.. I'm not sure if my video has the wrong format or what .. this is what i'm getting:

pi@raspberrypi ~ $ omxplayer -r Videos/my.video.avi 
file : Videos/my.video.avi reult 2 format avi audio streams 1 video streams 1 chapters 0 subtitles 0
Aspect : num 0 den 1 aspect 0.000000 display aspect 1.333333
Video codec omx-mpeg4 width 720 height 304 profile 15 fps 25.000000
Audio codec mp3 channels 2 samplerate 48000 bitspersample 16
Subtitle count : 0 state off : index 0

my screen resolution is set for : 1024x768

for now the workaround I found was to do : xset s 120 120  
that way , the screen goes black after 2min but the video stays..  would be nice if omxplayer could go full screen regardless of the video format , a bit like VLC

**Comment by popcornmix** [comment]
@davidNHK 
"fbset -depth 8 && fbset -depth 16" is the way to get console back after video ends.

**Comment by skgsergio** [comment]
I'm going to make a fix for my debs so, @popcornmix ¿this should work? (I'm far away from my RPi for testing it):

``` bash
#!/bin/sh

OMXPLAYER_BIN="/usr/bin/omxplayer.bin"
OMXPLAYER_LIBS="/opt/vc/lib:/usr/lib/omxplayer"

FBSET="/usr/sbin/fbset"

LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN "$@"

if [ -e $FBSET ]; then
  fbset -depth 8 && fbset -depth 16
fi
```

**Comment by popcornmix** [comment]
Sorry about the delay. Missed this.
My fbset is not in /usr/sbin. It might be worth combining with:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=18694&p=191761

``````
#!/bin/bash

OMXPLAYER_BIN="/usr/bin/omxplayer.bin"
OMXPLAYER_LIBS="/opt/vc/lib:/usr/lib/omxplayer"
FBSET=/bin/fbset

if [ -e $FBSET ]; then
 DEPTH2=`fbset|head -3|tail -1|cut -d " " -f 10`
fi

if [ "$DEPTH2" == "8" ]; then
 DEPTH1=16
 DEPTH2=8
elif [ "$DEPTH2" == "16" ]; then
 DEPTH1=8
 DEPTH2=16
elif [ "$DEPTH2" == "32" ]; then
 DEPTH1=8
 DEPTH2=32
else
 DEPTH1=8
 DEPTH2=16
fi

tput civis
echo -e "\033[0;30m"
clear
LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN "$@"
echo -e "\033[0m"
tput cnorm

if [ -e $FBSET ]; then
  fbset -depth $DEPTH1 && fbset -depth $DEPTH2
fi```
``````

**Comment by skgsergio** [comment]
I already noticed about fbset path but thx for the tip about DEPTH 1 and 2. This is the new script I'm going to put in my .deb files:

``` bash
#!/bin/bash

OMXPLAYER_BIN="/usr/bin/omxplayer.bin"
OMXPLAYER_LIBS="/opt/vc/lib:/usr/lib/omxplayer"

FBSET="/bin/fbset"

if [ -e $FBSET ]; then
    DEPTH2=`fbset | head -3 | tail -1 | cut -d " " -f 10`
    if [ "$DEPTH2" == "8" ]; then
        DEPTH1=16
    elif [ "$DEPTH2" == "16" ]; then
        DEPTH1=8
    elif [ "$DEPTH2" == "32" ]; then
        DEPTH1=8
    else
        DEPTH1=8
        DEPTH2=16
    fi
fi

LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN "$@"; true

if [ -e $FBSET ]; then
    fbset -depth $DEPTH1 && fbset -depth $DEPTH2
fi
```

I don't like the "tput civis" trick beacause sometimes I launch omxplayer using ssh so I want the terminal output.

**Comment by alexjj** [comment]
edit - updated to latest version and works better. However when omxplayer exits the desktop doesn't refresh from black until something triggers it. e.g. moving mouse or dragging a window around. Can only best describe this as cleaning the desktop with a window until all the black is removed.

**Comment by vinloren** [comment]
Alexjj, it work just like you described. I too am having the same problem but unfortunately I could'nt make any further progress.

**Comment by NSMyself** [comment]
Same here Alexjj.

**Comment by Heptode** [comment]
Thanks for the info on this page I had the same repainting issue.

I found that if you get the xrefresh app using';
 sudo apt-get install x11-xserver-utils

then put an:
xrefresh -display :0

at the end of the script, you get the screen repainted.

**Comment by popcornmix** [comment]
Various solutions have been proposed.
