### ISSUE TITLE
Player exits early (again)

### ISSUE THREAD

**Issue by ph0ng** [huceke/omxplayer#45]
For some time, I have been getting 

> ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.audio_mixer - OMX_ErrorPortUnpopulated (0), cannot parse input stream 

at the end of both video and audio file playback. Unfortunately I do not have the time to revert either the commits to omxplayer or my Arch system upgrades right now. 

I am using the latest firmware and linux kernel and it does not seem to be Arch specific: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=162817&sid=fa6c0f228110d25881d59ce403f4e09b#p162817

**Comment by torarin** [comment]
By waiting for `video_render` to complete in lieu of `audio_render`, the Bourne trailer plays all the way to the end for me: https://github.com/torarin/omxplayer/tree/ends_early

I have no idea why audio_render sends EOS prematurely, so it's possible there exist audio files that are cut off.

**Comment by popcornmix** [comment]
Any idea how early the audio_render produces EOS?
Therer is maximum decoded audio buffer size of 2 seconds
(#define AUDIO_BUFFER_SECONDS 2)
Does it always report 2 seconds early, or is it variable?

**Comment by ph0ng** [comment]
I'm sorry @torarin, but it does not do the trick. @popcornmix: It seems to occur about 2 seconds before the end, yes. This is irrespective of which file, audio or video, is being played.

**Comment by ph0ng** [comment]
It is a bit hard to tell in the Bourne trailer, but when comparing with PC playback you can see that the "August 3rd" text does not fade completely in the end. It also gives the `OMX.broadcom.audio_mixer - OMX_ErrorPortUnpopulated` message. 

One might think that I am a bit picky, but this is a real problem -- especially when watching shorter clips like news excerpts.

**Comment by popcornmix** [comment]
@torarin 
You could experiment with waiting for AUDIO_BUFFER_SECONDS after the EOS.
I'll check with openMAX people if they agree the EOS is being sent at correct time.

**Comment by torarin** [comment]
@popcornmix, I just tried setting AUDIO_BUFFER_SECONDS to 10 and 1, and I don't notice a difference. Could be I'm missing some other important magic number.

@ph0ng, the text doesn't fade completely out in VLC either, so until you can give me a more obvious cue, I am unable to match your attentiveness. :) Also, the OMX_ErrorPortUnpopulated thing happens after the EOS, so it might be unrelated.

**Comment by torarin** [comment]
I should mention that setting it to 10 does cause omxplayer to finish sending buffers to audio_decode and start waiting for audio_render much earlier, but it doesn't affect audio_render's EOS.

**Comment by ph0ng** [comment]
@torarin: I thought that the error, originating from OMX.broadcom.audio_mixer, was that this issue was about. I find it most disturbing while listening to audio books. Please try an arbitrary mp3 file and see if you can reproduce it.

**Comment by torarin** [comment]
@ph0ng, that error has been at the end of my logs for as long as I can remember, I just don't think it's related to the early exit.

**Comment by popcornmix** [comment]
I asked OpenMAX guy if this was correct behaviour:
"Entirely correct - the audio_render component sends EOS when it's processed all the buffers.  You need to look at OMX_IndexConfigAudioRenderingLatency to find out how many samples remain in audioplus."

So after EOS, you need to poll OMX_IndexConfigAudioRenderingLatency until it reached zero.

**Comment by torarin** [comment]
Thanks for finding out about that, @popcornmix!
Could you test this, @ph0ng? https://github.com/torarin/omxplayer/commit/085e65ac39255f788852ba814060c9205f47b676

**Comment by ph0ng** [comment]
Works fine!
