### ISSUE TITLE
Mpegs not seeking?

### ISSUE THREAD

**Issue by landymagma7** [huceke/omxplayer#48]
I've just licensed the mpg decoder from the Foundation and Omxplayer is happily playing back mpegs from my USB hard drive, but I find that the up, down, left and right cursor keys are not changing the playback position.

When I use the same build (built from the GitHubs contents as of September 4th) to play back mp4s from the same hard drive, the seek keys work perfectly.

Should the mpegs be seekable or is the fact that they're being hardware decoded somehow going to prevent seeking ever taking place?

Using raspbian hard float, firmware & all OS patches up to today's date (5th September)

_EDIT_ 

Further, I now see that omxplayer.cpp only performs the seek if the video source isn't mpeg (line 666 - I couldn't number that one any better!). 

Can anyone elucidate why mpegs are being expressly ignored?

_EDIT_

Line number now changed, but the line of code is:

```
if(m_incr != 0 && !m_bMpeg)
```

**Comment by thintux** [comment]
It would be really great to be able too seek mpegs :)

**Comment by landymagma7** [comment]
Really? Nobody even wants to let me know why the code explicitly excludes MPEGs from being fast forwarded or rewound? Surely XBMC doesn't impose the same limitation.

I'd just hack out a test myself to see if it's even possible but can't seem to get a dev environment configured to the project's satisfaction - either on the device itself or cross-compiling in the Virtual Machine touted by Element14.

**Comment by thintux** [comment]
Hi landymagma7,
I also had problems with building omxplayer so I have created a simple tutorial:
https://sites.google.com/a/roberteklund.org/www/projects/raspberry-pi#TOC-Video-Player

**Comment by torarin** [comment]
@landymagma7, I think `m_bMpeg` primarily signals non-seekable streams, despite its name. In particular, I don't think it has anything to do with codecs, but it might be set for MPEG-TS containers. Would be great if you could look into it if you get your build process working. I find it most convenient to use the official cross-compilation toolchain: https://github.com/raspberrypi/tools.

**Comment by trideck** [comment]
In my tests, playing a dumped MPEG-TS omxplayer  exits when seek. With MPEG-PS, created from MPEG-TS with ffmpeg, omxplayer ignores seek command.

**Comment by popcornmix** [comment]
This should work with recent builds (http://omxplayer.sconde.net/)
