### ISSUE TITLE
Play streams from STDIN

### ISSUE THREAD

**Issue by ToadKing** [huceke/omxplayer#51]
This feature can be a lot of help for stuff like get-iplayer or livestreamer, without having to resort to scripts that have to hack around this limitation with FIFO files to get support in omxplayer.

I tried adding a special case to translate the file "-" into a streaming URL "pipe:0" in OMXReader.cpp, but while omxplayer detected the stream type and information, it quit before playing any of the stream.

**Comment by singpolyma** [comment]
This seems related to #29

**Comment by popcornmix** [comment]
Have you tried the mkfifo trick?
i.e.
mkfifo fifo.mp4
./produce_data > fifo.mp4 &
omxplayer fifo.mp4

**Comment by basvdheijden** [comment]
I tried the mkfifo trick, in combination with wget. IE:

> mkfifo fifo.mp4
> wget -O fifo.mp4 http://example.com/stream.mp4 &
> omxplayer fifo.mp4

But when the wget command finishes before omxplayer finished playing the stream, it will quit and say: "Have a nice day.".

Is there a trick to evade this problem?

**Comment by popcornmix** [comment]
Try: https://github.com/popcornmix/omxplayer/commit/75f213a5d71d0bc2d0106824db62d931e0c56c52

**Comment by basvdheijden** [comment]
I'll try to build it including your commit. 

In File.cpp [L59] I see the following code:

> if (strFileName.compare(0, 5, "pipe:") == 0)

Does this mean I have to use `omxplayer pipe://fifo.mp4` instead of `omxplayer fifo.mp4`?

**Comment by popcornmix** [comment]
See:
http://ffmpeg.org/ffmpeg-protocols.html#pipe

basically use "pipe:0" as a filename, and it will read from stdin. E.g.
`cat file.mkv | omxplayer pipe:0`

Note: keypresses won't work in this mode as they also use stdin.

**Comment by basvdheijden** [comment]
And this is the only option I have?

**Comment by popcornmix** [comment]
A future feature would be accepting control from a socket, allowing control from another process (with it's own stdin), or external devices (e.g. iPhone/Android).

But this request is implemented.

**Comment by popcornmix** [comment]
See here for a (future) solution to controlling omxplayer when stdin is streaming a video.
https://github.com/popcornmix/omxplayer/issues/10

**Comment by amaaov** [comment]
mkfifo solution works, but omxplayer terminates if no data in fifo. And, well, that's okay. But, omxplayer does blocking terminal.

pipe:0 solution gives error and player terminates: Inconsistency detected by ld.so: dl-tls.c: 446: _dl_allocate_tls_init: Assertion `listp != ((void *)0)' failed!
