### ISSUE TITLE
No longer builds on Arch 

### ISSUE THREAD

**Issue by stronnag** [huceke/omxplayer#6]
Due to the Debian changes, it no longer builds on Arch for the Raspberry. Please consider that Debian is not the only distro out there.

**Comment by torarin** [comment]
Could you post the error messages you get?

**Comment by stronnag** [comment]
On Fri, 8 Jun 2012 08:48:34 -0700
torarin
reply@reply.github.com
wrote:

> Could you post the error messages you get?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/huceke/omxplayer/issues/6#issuecomment-6206176

It was a failure to compile RBP.cpp, due to the changed #define for
Raspberry Pi. Took me a while to figure it out, but its building again.

-jh
