### ISSUE TITLE
Issues playing this mpeg2 file from US cable tv

### ISSUE THREAD

**Issue by sugatam** [huceke/omxplayer#60]
(Cross posted from raspberry pi forums)

This one's a vanilla 1080i mpeg2/ac3 captured from one channel on my hdhomerun prime. Gives omxplayer fits, the thing plays a couple of frames, freezes for a few seconds, then a couple more frames, and so on. All the while the audio is messed up. This is the only stream on my cable lineup to have this problem - hopefully the experts will figure out why.

https://docs.google.com/open?id=0B6kbH3x-yFiiQ3NGcEpPaklUMWs

The mediainfo is:

General
ID : 0 (0x0)
Complete name : /media/MAIN/1576_20120925204200.mpg
Format : MPEG-TS
File size : 120 MiB
Duration : 1mn 4s
Overall bit rate : 15.7 Mbps

Video
ID : 6271 (0x187F)
Menu ID : 1 (0x1)
Format : MPEG Video
Format version : Version 2
Format profile : Main@High
Format settings, BVOP : Yes
Format settings, Matrix : Custom
Format settings, GOP : M=3, N=15
Codec ID : 2
Duration : 1mn 4s
Bit rate mode : Variable
Bit rate : 14.5 Mbps
Maximum bit rate : 18.0 Mbps
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate : 29.970 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan order : Top Field First
Compression mode : Lossy
Bits/(Pixel*Frame) : 0.234
Stream size : 111 MiB (92%)

Audio
ID : 6273 (0x1881)
Menu ID : 1 (0x1)
Format : AC-3
Format/Info : Audio Coding 3
Mode extension : CM (complete main)
Codec ID : 129
Duration : 1mn 4s
Bit rate mode : Constant
Bit rate : 384 Kbps
Channel(s) : 5 channels
Channel positions : Front: L C R, Side: L R
Sampling rate : 48.0 KHz
Bit depth : 16 bits
Compression mode : Lossy
Delay relative to video : -749ms
Stream size : 2.94 MiB (2%)

Text #1
ID : 6271 (0x187F)-608-1
Menu ID : 1 (0x1)
Format : EIA-608
Muxing mode : A/53 / DTVCC Transport
Muxing mode, more info : Muxed in Video #1
Duration : 1mn 4s
Stream size : 0.00 Byte (0%)

Text #2
ID : 6271 (0x187F)-1
Menu ID : 1 (0x1)
Format : EIA-708
Muxing mode : A/53 / DTVCC Transport
Muxing mode, more info : Muxed in Video #1
Duration : 1mn 4s
Stream size : 0.00 Byte (0%)

According to Dom, who took a look,
"I did have a look. xbmc plays it okay, so it seems to be a bug with omxplayer extracting the timestamps. Might be worth posting an issue on github."

**Comment by popcornmix** [comment]
This plays with latest (built from github) omxplayer.
I believe the problem was a resolution change in the video stream.
