### ISSUE TITLE
How can i resize the video?

### ISSUE THREAD

**Issue by neviaumi** [huceke/omxplayer#65]
Hi all,
    I would like to set video size of height and width.
(For example, i play a HD video in a omxplayer , even the resolution of video is 1920 \* 1080 
  I can set the video run as 960 \* 540 through my coding.
)
   I found a function in OMXVideo named SetVideoRect(CRect)
   But i call it is not any affect.
   So that, my question is what should i do to resize the video ???

**Comment by torarin** [comment]
Take a look at https://github.com/huceke/omxplayer/blob/master/OMXVideo.cpp#L600

**Comment by neviaumi** [comment]
Hi torarin,
     I attempted to uncommend Line 593 to 608,But it not work!
     It not response any error message but not any affect of the video too.
     So , i try to other mode (Set transform, set src dis...etc.)
    It is working properly .
   My code following, could you mind let me know where is issue??
  Set src dis (It work)
        OMX_ERRORTYPE omx_err = OMX_ErrorNone;
        OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
        OMX_INIT_STRUCTURE(configDisplay);
        configDisplay.nPortIndex = m_omx_render.GetInputPort();
        configDisplay.set = OMX_DISPLAY_SET_SRC_RECT;
        configDisplay.src_rect = src;
        omx_err=m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
        if (omx_err != OMX_ErrorNone)
        {
                printf("Get The Error!omx_err(0x%08x)\r\n",omx_err);
        }
        else
        {
                printf("Src width:\t%d\r\n",src.width);
                printf("Src Height:\t%d\r\n",src.height);
                printf("Src x offset:\t%d\r\n",src.x_offset);
                printf("Src y offset:\t%d\r\n",src.y_offset);
        }
  Set transform(It work)
        OMX_ERRORTYPE omx_err = OMX_ErrorNone;
        OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
        OMX_INIT_STRUCTURE(configDisplay);
        configDisplay.nPortIndex = m_omx_render.GetInputPort();
        configDisplay.set = OMX_DISPLAY_SET_TRANSFORM;
        configDisplay.transform = trans;
        omx_err=m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
        if (omx_err != OMX_ErrorNone)
        {
                printf("Get The Error!omx_err(0x%08x)\r\n",omx_err);
        }
        else
        {
                printf("Transforms:\t%d\r\n",trans);
        }
  Set dist (It not work:()
        OMX_ERRORTYPE omx_err = OMX_ErrorNone;
        OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
        OMX_INIT_STRUCTURE(configDisplay);
        configDisplay.nPortIndex = m_omx_render.GetInputPort();
        configDisplay.set = OMX_DISPLAY_SET_DEST_RECT;
        configDisplay.dest_rect = dest;
        omx_err=m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion,&configDisplay);
        if (omx_err != OMX_ErrorNone)
        {
                printf("Get The Error!omx_err(0x%08x)\r\n",omx_err);
        }
        else
        {
                printf("Dest width:\t%d\r\n",dest.width);
                printf("Dest Height:\t%d\r\n",dest.height);
                printf("Dest x offset:\t%d\r\n",dest.x_offset);
                printf("Dest y offset:\t%d\r\n",dest.y_offset);
        }

**Comment by neviaumi** [comment]
Hi, i found the solution
It must specify layer before set dest.
