### ISSUE TITLE
Cannot Compile The OMXAudio??

### ISSUE THREAD

**Issue by neviaumi** [huceke/omxplayer#66]
I attempted to compile newly version omxplayer 
While i run the make, i got the compiler error following:

//usr//bin/g++ --sysroot=/ -isystem/include -pipe -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -O3 -mstructure-size-boundary=32 -mno-sched-prolog -std=c++0x -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CMAKE_CONFIG -D__VIDEOCORE4__ -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_OPT_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DTARGET_RASPBERRY_PI -DUSE_EXTERNAL_LIBBCM_HOST -isystem//usr/include -isystem//opt/vc/include -isystem//usr/include -isystem//opt/vc/include/interface/vcos/pthreads -isystem//usr/include/freetype2 -I./ -Ilinux -Iffmpeg_compiled/usr/local/include/ -c OMXAudio.cpp -o OMXAudio.o -Wno-deprecated-declarations

OMXAudio.cpp: In member function ?irtual bool COMXAudio::SetCurrentVolume(long int)??
OMXAudio.cpp:778:5: error: ?MX_CONFIG_BRCMAUDIODOWNMIXCOEFFICIENTS??was not declared in this scope
OMXAudio.cpp:778:45: error: expected ????before ?ix??OMXAudio.cpp:779:5: error: ?ix??was not declared in this scope
OMXAudio.cpp:789:29: error: ?MX_IndexConfigBrcmAudioDownmixCoefficients??was not declared in this scope
OMXAudio.cpp: In member function ?irtual void COMXAudio::WaitCompletion()??
OMXAudio.cpp:1185:19: warning: unused variable ?tarttime??[-Wunused-variable]
OMXAudio.cpp:1185:30: warning: unused variable ?ndtime??[-Wunused-variable]
make: **\* [OMXAudio.o] Error 1

So , refer a stderr , it mean the OMC_CONFIG_BRCMAUDIODOWNMIXCOEFFICIENTS cannot found. But Why? it should default included in the raspberry?
Who can let me know where is the problem???

**Comment by torarin** [comment]
OMX_CONFIG_BRCMAUDIODOWNMIXCOEFFICIENTS is present only in recent versions of the firmware.

**Comment by neviaumi** [comment]
My Image using 2012-09-18-wheezy-raspbian.img . It is a problem caused???

**Comment by torarin** [comment]
You would need to update it.

**Comment by neviaumi** [comment]
I have try to do apt-get update & upgrade
After finish reboot and retry to make the program
i run make clean
make
I got the same result......

**Comment by torarin** [comment]
Try rpi-update: https://github.com/Hexxeh/rpi-update

**Comment by neviaumi** [comment]
This work:)Thank!
