### ISSUE TITLE
Added RTSP support

### ISSUE THREAD

**Issue by peter3161** [huceke/omxplayer#67]
I added RTSP support to OMXReader::Open. It works fine. Allowing RTSP support enables OMXPlayer to play the streams from IP cameras. In my tests I have used Axis cameras. 

The only addition to OMXReader::Open is a adding 
m_filename.substr(0,7) ==  "rtsp://"  to line 146 or 147. Please include the support for the RTSP protocol to OMXPlayer.

**Comment by Stemby** [comment]
Yes, please support the RTSP protocol.

Thank you!

**Comment by popcornmix** [comment]
@Stemby 
This was added 5 months ago. 
https://github.com/huceke/omxplayer/commit/8f6692d864c8922e67cc587737990640246a3945

**Comment by Stemby** [comment]
@popcornmix 
Ah, thanks. So, why this issue is still open?

Is there someone who has tested RTSP by using OMXPlayer on a Raspberry Pi? If yes, how much latency did you get on average?

Thank you!

**Comment by smilingdust** [comment]
Thank you .I need  your demo to complete my demo.

**Comment by prashanthb** [comment]
Hi, May I know if omxplayer supports MJPEG and ADPCM playback from IP camera?
