### ISSUE TITLE
3d subtitles stretched out

### ISSUE THREAD

**Issue by jbaanus** [huceke/omxplayer#68]
Assumption: XBMC is using omxplayer to dusplay subtitles. If this is incorrect, it is XBMC issue instead.

Based on my OpenELEC and Raspbmc experience, when watching 3D Half-SBS movies, the subtitles are stretched out in width - about 1.5 ... 2x.
Height seems to be OK.

Due to wide character nature, sometimes subtitles are displayed on 4 lines, not regular 2.

Tried 1080p Half-SBS movie with .srt subtitles.

**Comment by popcornmix** [comment]
Not an omxplayer issue. xbmc does things like this diffreently.
First can you rename file to <file>.3DSBS.mkv. Then xbmc will know it is a 3D SBS movie.
The other option is to change the hdmi mode to one of the half width ones (e.g. 960x1080) which also forces 3d SBS mode.

**Comment by jbaanus** [comment]
I have set 3DSBS in movie and XBMC automatically detects it and shows subtitles correctly. Only that font has wider characters than it should.

A picture to illustrate the issue:
https://www.dropbox.com/s/zom9igabzxgxf84/2012-10-21%2015.33.04.jpg

**Comment by jbaanus** [comment]
Seems like the font is also higher than in normal movie:
https://www.dropbox.com/s/l2owd4cv4qj3syr/2012-10-21%2015.40.24.jpg

**Comment by jbaanus** [comment]
Looks like XBMC is indeed using its own subtitle rendering, seems safe to close this issue.
