### ISSUE TITLE
question on h.264 bitrates and encoding settings for stutter-free playback

### ISSUE THREAD

**Issue by parasew** [huceke/omxplayer#72]
we just received six raspberry pi boards with 512mb ram and plan to use them for hdmi playout. initial tests were working great with omxplayer, but we are experiencing extreme stuttering issues for every h264 file that has a bitrate over 3mbits. after digging through the web, i found that several people play 11mbit files or higher without any issues. i am wondering if overclocking of the rasp is really needed to get smooth playback or if there are any recommended encoding settings for files to play on the rasp?

our current setting:
- gpu split of 256/256
- latest raspbian from http://www.raspbian.org/RaspbianImages upgraded with apt-get dist-upgrade
- tried with sandisk extreme pro 32GB 95mb/s cards and with standard class 10 SD cards
- omxplayer from http://omxplayer.sconde.net/ Build date: 23/10/2012 01:40 CEST
- omxplayer started from the console with audio passthrough; also tried with videoclips that have no audio track at all

here is one of the videos we are trying to play
http://artisticbokeh.com/videotest/miasma/teaser_temp.mp4

also, we tried with various smaller bitrates. except h.264 ecoded in vbr with 3mbits all the videos stutter.
example videos that we want to play are on video and on youtube:
http://www.youtube.com/user/artisticbokeh
http://vimeo.com/artisticbokeh

thanks for any help on how to get omxplayer to play decent video bitrates!

**Comment by exidyboy** [comment]
Dear parasew,

Your file http://artisticbokeh.com/videotest/miasma/teaser_temp.mp4 plays smoothly for me on both HDMI and composite video outputs with no video or audio stutter off a 4GB Class 4 Sandisk SDHC card. According to 'top' CPU usage is around 15 percent and memory usage <20 percent on a 256MB Pi. GPU split 128/128. I am using LadyAda's Occidentalis distro.

I am happy to help with more testing or provide additional information.

Cheers,
Mike
Melbourne, Australia

**Comment by parasew** [comment]
exidyboy - thanks for your comment; i retried with the Occidentalis distro and there it actually plays much smoother. strange thing but thanks a lot for the pointer!
