### ISSUE TITLE
make omxplayer compile on raspbian

### ISSUE THREAD

**Issue by parasew** [huceke/omxplayer#73]
wrigthrocket has a fork of the repo so it actually builds on raspbian.
see https://github.com/wrightrocket/omxplayer

please, can we merge the changes so there is a way of selecting to either build for raspbian (on the pi) or to cross-compile? i think the project would benefit a lot, since more people would be able to work on the code (especially people that only have the raspberry as development option, without any linux machine to cross-compile).

**Comment by Stasik0** [comment]
try to run this file before building https://github.com/Stasik0/omxplayer/blob/boblight/prepare-native-raspbian.sh it alters the native make files making the whole process more transparent

**Comment by KevinSeghetti** [comment]
Latest doesn't compile under raspbian, even after running prepare-native-raspbian.sh, gives the following compile errors:

OMXOverlayCodecText.cpp: In member function ‘virtual bool COMXOverlayCodecText::Open(COMXStreamInfo&)’:
OMXOverlayCodecText.cpp:44:30: error: ‘AV_CODEC_ID_SSA’ was not declared in this scope
OMXOverlayCodecText.cpp:45:21: error: ‘AV_CODEC_ID_SUBRIP’ was not declared in this scope
make: **\* [OMXOverlayCodecText.o] Error 1

**Comment by popcornmix** [comment]
Did you delete and rebuild ffmpeg? I think those errors come from an old ffmpeg.

**Comment by KevinSeghetti** [comment]
Ah, indeed needing to delete, rebuild an reinstall ffmpeg was what was causing that error. (a step I avoided because it takes quite a long time on the pi, but should have tried when I got the error). Thanks
The build gets further, but now I get: 
In file included from utils/variant.hpp:101:0,
                 from utils/Mailbox.h:35,
                 from OMXPlayerSubtitles.h:26,
                 from OMXPlayerSubtitles.cpp:19:
utils/traits.hpp:141:5: error: expected unqualified-id before ‘using’
In file included from utils/Mailbox.h:37:0,
                 from OMXPlayerSubtitles.h:26,
                 from OMXPlayerSubtitles.cpp:19:
utils/FunctorVisitor.h:37:3: error: expected unqualified-id before ‘using’

**Comment by popcornmix** [comment]
Ah - it need gcc 4.7. See here:
https://github.com/huceke/omxplayer/issues/111

**Comment by KevinSeghetti** [comment]
OK, that did it, I finally got it built. Thanks.   (this project needs configure, which would automatically identify missing requirements).

**Comment by hinxx** [comment]
I avoided compiling the ffmpeg by using the debs found here:

http://www.deb-multimedia.org/dists/testing/main/binary-armhf/

```
pi@raspberrypi ~/omxplayer $ cat /etc/apt/sources.list

deb http://archive.raspbian.org/raspbian wheezy main contrib non-free
deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free

deb http://www.deb-multimedia.org wheezy main non-free
deb-src http://www.deb-multimedia.org wheezy main non-free
```

**Comment by rparfett** [comment]
Hi
I've performed 
install gcc 4.7
run prepare-native-rspbian

 but I get the following error:

/include/ -c utils/log.cpp -o utils/log.o -Wno-deprecated-declarations
In file included from /usr/include/linux/kernel.h:4:0,
                 from /usr/include/arm-linux-gnueabihf/sys/sysinfo.h:25,
                 from linux/PlatformDefs.h:47,
                 from ./system.h:227,
                 from utils/log.cpp:22:
/usr/include/linux/sysinfo.h:8:2: error: ‘__kernel_long_t’ does not name a type
/usr/include/linux/sysinfo.h:9:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:10:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:11:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:12:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:13:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:14:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:15:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:18:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:19:2: error: ‘__kernel_ulong_t’ does not name a type
/usr/include/linux/sysinfo.h:21:22: error: ‘__kernel_ulong_t’ was not declared in this scope
make: **\* [utils/log.o] Error 1

Any help would be appreciated.
ffmpeg compiled OK.  This is the output from make

Thanks

**Comment by popcornmix** [comment]
Did you change the symbolic links for gcc?
https://github.com/huceke/omxplayer/issues/111#issuecomment-13348001

**Comment by rparfett** [comment]
Yes I did.

**Comment by JamesHagerman** [comment]
Can we at least update the README.md to lead us to the prepare-native-raspbian,sh script?

Right now, there isn't enough documentation on just HOW do compile this source tree. If we need a script to set up the environment to compile, shouldn't we include that script in the source tree?

Yes, I know there may be an issue of actually compiling omxplayer on the Pi itself, but at least it would help people compile at all which is better then what it is now...

**Comment by JamesHagerman** [comment]
@Stasik0 is there any reason for not doing a pull request for your prepare script?

**Comment by Stasik0** [comment]
It is in the big pull request of boblight.

Am 12.03.2013 um 21:19 schrieb James Hagerman notifications@github.com:

**Comment by JamesHagerman** [comment]
Ah! Thank you! I missed that!

**Comment by popcornmix** [comment]
I've added Stasik0's prepare-native-raspbian.sh script (with gcc4.7 added)
https://github.com/huceke/omxplayer/commit/5b369233293f3fe927fcfec0a9844d7f16e5e934

which should make this easier
