### ISSUE TITLE
OMXPlayer sometimes freaks out when an HLS stream changes resolution or bitrate

### ISSUE THREAD

**Issue by rcombs** [huceke/omxplayer#75]
I'm having trouble making a test case for this because I've only seen it on HighSchoolCube's iOS streams. I'll be fiddling with it over the next week or so, but for the moment, it looks like the changing of resolution and bitrate that can come with cutting a video to an ad can result in OMXPlayer freezing up for a few seconds, playing the video at double-speed, etc.... I can't get any consistency out of it. If anyone wants to take a look at this, email me or /msg me at llrcombs on Foonetic and I'll help set up a test broadcast on HighSchoolCube with some problematic ads and other clips that can be swapped in from the web interface.

**Comment by popcornmix** [comment]
Can you produce a video file (presumably .ts) that exhibits the problem?

**Comment by popcornmix** [comment]
omxplayer handles resolution changes now.
Please reopen if still a problem.
