### ISSUE TITLE
Black screen instead of video playback

### ISSUE THREAD

**Issue by gogiman** [huceke/omxplayer#78]
I am getting black screen when switching channels in XBMC. Here is the log:

18:47:02 T:3041370752  NOTICE: COMXPlayer: Opening: pvr://channels/tv/All TV channels/2.pvr
18:47:02 T:3041370752 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:47:02 T:2782553152  NOTICE: Thread COMXPlayer start, auto delete: false
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Creating InputStream
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Creating Demuxer
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
18:47:02 T:2782553152 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
18:47:02 T:2782553152  NOTICE: Opening video stream: 0 source: 256
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Creating video thread
18:47:02 T:2844783680  NOTICE: Thread COMXPlayerVideo start, auto delete: false
18:47:02 T:2782553152  NOTICE: Opening audio stream: 1 source: 256
18:47:02 T:2782553152  NOTICE: Creating audio thread
18:47:02 T:2853172288  NOTICE: Thread COMXPlayerAudio start, auto delete: false
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Opening video stream: 0 source: 256
18:47:02 T:2782553152  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Opening audio stream: 1 source: 256
18:47:02 T:2853172288  NOTICE: OMXClock using video as reference
18:47:02 T:2782553152  NOTICE: Opening audio stream: 1 source: 256
18:47:02 T:2844783680 WARNING: CRenderManager::Configure - timeout waiting for previous frame
18:47:02 T:2844783680  NOTICE: Display resolution DESKTOP : 1280x720 @ 60.00 - Full Screen (16)
18:47:03 T:2853172288  NOTICE: OMXClock using audio as reference
18:47:03 T:2782553152  NOTICE: Opening video stream: 0 source: 256
18:47:03 T:2782553152  NOTICE: OMXClock using audio as reference
18:47:03 T:3041370752  NOTICE: Using GL_TEXTURE_2D
18:47:03 T:3041370752  NOTICE: GL: Using BYPASS render method
18:47:03 T:3041370752  NOTICE: GL: GL_ARB_texture_rectangle not supported and OpenGL version is not 2.x
18:47:03 T:3041370752  NOTICE: GL: Reverting to POT textures

**Comment by gogiman** [comment]
Anyone some idea?

**Comment by gogiman** [comment]
Just to add more info...
It happens when switching channels in Live TV.
It seems that it is connected with different kind of frames and waiting for i-frame.
More detail discussion is here: https://github.com/opdenkamp/xbmc-pvr-addons/issues/166

Thank you very much.

**Comment by popcornmix** [comment]
Live TV is a known problem in xbmc.
However this git repo is for command line omxplayer, and I believe your bug report is for xbmc.
Here may be a better place to report issues with live tv on xbmc.
http://forum.xbmc.org/showthread.php?tid=148646
