### ISSUE TITLE
Unable to access pulseaudio sink via upnp

### ISSUE THREAD

**Issue by RobertBuhren** [huceke/omxplayer#79]
Pulseaudio has the cool feature that it can share the sound via upnp. This works great when i try to access it from my android phone via bubbleupnp but it fails when i try it with omxplayer on my openelec. (Regular files shared via upnp can be accessed though) Here's the relevant part of the log:

14:23:58 T:3043147776 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:24:03 T:2804270176   ERROR: CUPnPDirectory::GetResource - unable to find object /org/gnome/UPnP/MediaServer2/PulseAudio/Sinks/1fanart.jpg
14:24:03 T:2694083680   ERROR: CUPnPDirectory::GetResource - unable to find object /org/gnome/UPnP/MediaServer2/PulseAudio/Sinks/0fanart.jpg
14:24:19 T:3043147776  NOTICE: COMXPlayer: Opening: http://192.168.178.38:4714/listen/source/upnp.monitor
14:24:19 T:3043147776 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:24:19 T:2685695072  NOTICE: Thread COMXPlayer start, auto delete: false
14:24:19 T:2685695072  NOTICE: OMXClock using video as reference
14:24:19 T:2685695072  NOTICE: Creating InputStream
14:24:19 T:2685695072  NOTICE: OMXClock using video as reference
14:24:19 T:2685695072  NOTICE: Creating Demuxer
14:24:19 T:2710860896  NOTICE: Thread CFileCache start, auto delete: false
14:24:48 T:2804270176   ERROR: CUPnPDirectory::GetResource - unable to find object /org/gnome/UPnP/MediaServer2/PulseAudio/Sinks/1fanart.jpg
14:24:50 T:2685695072   ERROR: Open - error probing input format, http://192.168.178.38:4714/listen/source/upnp.monitor
14:24:50 T:2685695072   ERROR: OpenDemuxStream - Error creating demuxer
14:24:50 T:2685695072  NOTICE: COMXPlayer::OnExit()
14:24:50 T:2685695072  NOTICE: COMXPlayer::OnExit() deleting input stream
14:24:50 T:3043147776   ERROR: Playlist Player: skipping unplayable item: 0, path [upnp://412dd19f-8976-4f9f-ace2-d3e324ad68b2/%2forg%2fgnome%2fUPnP%2fMediaServer2%2fPulseAudio%2fSinks%2f1]

**Comment by popcornmix** [comment]
We'll only support formats that ffmpeg supports. This is failing before ffmpeg has provided us with any data.
`14:24:50 T:2685695072 ERROR: Open - error probing input format, http://192.168.178.38:4714/listen/source/upnp.monitor`
