### ISSUE TITLE
Option to set the resolution of omxplayer

### ISSUE THREAD

**Issue by parkerlreed** [huceke/omxplayer#82]
omxplayer on my Raspberry Pi Raspbian Wheezy overscans due to TV always overscanning. In XBMC I can alleviate this by doing a custom adjust of the video size to match my screen. 

What would be nice to have in omxplayer would be a resolution parameter like:

omxplayer -o hdmi -res 1214x690 video.mp4

(1214x690 is the resolution that fits my TV while using hdmi_mode=4 and some custom overscan settings)

If this is at all possible this would be a great addition to omxplayer.

**Comment by rebroad** [comment]
Issue #27 would achieve this, no?

**Comment by parkerlreed** [comment]
Ahh it seems like it would. Didn't read that far back.
