### ISSUE TITLE
Option to override screen aspect ratio to provide fix for composite 16:9 televisions

### ISSUE THREAD

**Issue by Jadelor** [huceke/omxplayer#83]
I suggest a command line parameter to override screen aspect ratio, so that videos would look proper on composite 16:9 televisions.

There currently seems no way to get a proper aspect ratio for Raspi video play when using a composite 16:9 television.

In these situations, the film image should be crunched horizontally so that the television can stretch it back into 16:9 aspect ratio. Currently, OMXplayer always outputs 4:3 ratio for composite screens, no matter what options are set in config.txt. This looks overstretched and wrong on analogue 16:9 televisions.

**Comment by popcornmix** [comment]
I have a patch for this, but it requires the "next" firmware tree:
https://dl.dropbox.com/u/3669512/temp/omx_aspect_ratio.patch

I'll commit the fix when we switch to the "next" firmware tree.

**Comment by popcornmix** [comment]
This is now fixed.
