### ISSUE TITLE
SSM multicast playback possible? 

### ISSUE THREAD

**Issue by dbrb2** [huceke/omxplayer#84]
Not sure whether the below is something that would be expected to work or not...I have asked the same question on the raspberry Pi forum, but since it relates so closely to omxplayer here goes: 

I can, using VLC, join a SSM Mpeg4 pt2 multicast stream using an sdp in the format below: 

v=0
m=video <multicast_port> RTP/AVP 96
c=IN IP4 <multicast_ip>
a=rtpmap:96 RTP/AVP
a=source-filter: incl IN IP4 <multicast_ip> <unicast_ip> 

However, VLC can't make use of the pi's GPU, so is very slow

omxplayer, when given the same sdp file, pauses for a while then quits with "have a nice day"

If presensted with the joining instructions in the form:

omxplayer udp://<unicast_ip>@<multicast_ip>:<multicast_port> the result is similar

Would sdp parsing be expected to work? How about SSM...?

**Comment by torarin** [comment]
Omxplayer uses ffmpeg to demux streams, so if avplay can play it, omxplayer can too. I could have a look if you are able to post a public sample stream.

**Comment by dbrb2** [comment]
Hi,
Although there is nothing secret about the video, I'm not sure how I could replicate the multicast stream itself publicly 
However, I may have found (some) of the problem.  An older ffmpeg on a redhat machine can play my sdp fine

ffmpeg -i input.sdp

FFmpeg version git-b319052, Copyright (c) 2000-2011 the FFmpeg developers
  built on Aug 15 2011 16:42:18 with gcc 4.1.2 20070626 (Red Hat 4.1.2-14)
  configuration: 
  libavutil    50. 37. 0 / 50. 37. 0
  libavcore     0. 16. 1 /  0. 16. 1
  libavcodec   52.109. 0 / 52.109. 0
  libavformat  52. 97. 0 / 52. 97. 0
  libavdevice  52.  2. 3 / 52.  2. 3
  libavfilter   1. 74. 0 /  1. 74. 0
  libswscale    0. 12. 0 /  0. 12. 0
found ssm_source..x.y.a.b
found ssm_source..x.y.a.b
udp buf = [udp://xxxxxxx:yyyyyy?localport=zzzzzz&ttl=16&ssm_source=x.y.a.b]

....then proceeds to join and read the stream

But a newer ffmpeg on a debian box complains on same network with same sdp: 

ffmpeg -i input.sdp

ffmpeg version 0.8.4-4:0.8.4-0ubuntu0.12.04.1, Copyright (c) 2000-2012 the Libav developers
  built on Nov  6 2012 16:50:25 with gcc 4.6.3
  configuration: --extra-version='4:0.8.4-0ubuntu0.12.04.1' --arch=i386 --prefix=/usr --libdir=/usr/lib/i386-linux-gnu --enable-vdpau --enable-bzlib --enable-libgsm --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-pthreads --enable-zlib --enable-libvpx --enable-runtime-cpudetect --enable-libfreetype --enable-vaapi --enable-gpl --enable-postproc --enable-swscale --enable-x11grab --enable-libdc1394 --shlibdir=/usr/lib/i386-linux-gnu/i686/cmov --cpu=i686 --enable-shared --disable-static
  libavutil    51. 22. 1 / 51. 22. 1
  libavcodec   53. 35. 0 / 53. 35. 0
  libavformat  53. 21. 0 / 53. 21. 0
  libavdevice  53.  2. 0 / 53.  2. 0
  libavfilter   2. 15. 0 /  2. 15. 0
  libswscale    2.  1. 0 /  2.  1. 0
  libpostproc  52.  0. 0 / 52.  0. 0

[sdp @ 0x928ea80] Could not find codec parameters (Video: mpeg4, yuv420p)
[sdp @ 0x928ea80] Estimating duration from bitrate, this may be inaccurate
input.sdp: could not find codec parameters

Now I can see I have too many variables here - different distributions, and different ffmpeg builds - but in short it seems to be an issue between my sdp and ffmpeg, not with your player :-)
