### ISSUE TITLE
Cross Compiling Omxplayer

### ISSUE THREAD

**Issue by Synoia** [huceke/omxplayer#85]
Instructions need to add installing Toolchain as described at this link

http://ffmpeg.org/trac/ffmpeg/wiki/How%20to%20compile%20FFmpeg%20for%20Raspberry%20Pi%20%28Raspbian%29#no1

And the changes suggested to the Omxplayer make file are in context and are more understandable.

The omxplayer make file would be better structured if moved to the toolchain build environment.

**Comment by popcornmix** [comment]
Instructions are included now.
