### ISSUE TITLE
can omxplayer hardware decoding support resolution more than 1920x1080 ? 

### ISSUE THREAD

**Issue by DachiChang** [huceke/omxplayer#86]
Hi All,

I have three special film
1. test-1.avi resolution is 1920x1080, codec XVID omxplayer is full support  :) 
2. test-2.avi resolution is 2560x480, codec XVID omplayer only have audio decode, and no video display
3. test-3.avi resolution is 2560x480, codec X.264 omplayer play the mess video, but audio is correct. I think does omplayer not support x.264 ?

I want to play the special resolution video that make by myself. can omxplayer support that ? or it's limit   hardware decoding by Raspberrypi board ?

**Comment by DachiChang** [comment]
I have see all the source code of omxplayer including .h and .cpp files, I can't find the code that reference to my problem, is this problem limited by firmware or hardware GPU ?

How can i fix ? pls help me.

**Comment by popcornmix** [comment]
Can I ask why you are encoding 2560x480 videos?
We only claim to support up to 1920x1080 videos.
We'd need some evidence for why it is useful to spend time investigating if it is possible to change these limits.

**Comment by DachiChang** [comment]
Because we use connect more than one camera to build film, so that width is more than 1920.
our goal is make student to learn the class in school by special film, if we use only one camera that can't content width of whole black board. We're aim education in Asia.

**Comment by popcornmix** [comment]
If you post a link to a sample file, I can take a look, although no guarantees I can make it work.

**Comment by DachiChang** [comment]
https://plus.google.com/photos/111356597172506892589/albums/5824679326108987345?banner=pwa

**Comment by popcornmix** [comment]
Bad news. I've checked with the codecs team, and the hardware is limited to 1920 wide. Your 2560x480 files are not possible to decode.

**Comment by DachiChang** [comment]
I very appreciate for solve my problem that about decoding more than 1920x1080 resolution film. thank you.
