### ISSUE TITLE
Is playlist support on the roadmap?

### ISSUE THREAD

**Issue by NSMyself** [huceke/omxplayer#87]
Nothing fancy, but I'd love to be able to set up a small queue of 4 or 5 files and have Omxplayer play them sequentially. 

Since its Christmas and all, smooth fadein/fadeout transitions between each file would really be the icing on the cake.

**Comment by NSMyself** [comment]
No updates regarding this wishlist, are there? :/

**Comment by popcornmix** [comment]
Pull requests are welcome
