### ISSUE TITLE
CLI pts stats output not in sync with video

### ISSUE THREAD

**Issue by turingmachine** [huceke/omxplayer#89]
I've created a 10 min x264 video which contains just a time display of the current position. It is a video without audio.

If I play this video with --stats, the position shown in cli output (e.g. "V: 34.0") is the same as the time shown in the movie. And it stays in sync unless you seek in the movie or put in pause.

Effects on forward seeking:
If I seek forward in the movie, the cli output jumps to say 40 seconds and continues instantly from there. However, the video itself will not be played until the buffer is full again. This takes about 5-10 seconds. So after 5-10 seconds, the cli output is at 45 to 50 seconds, but the video will start playing at 40s.

Effects on pause:
Assuming the display in the video and the cli output are in sync: On entering pause mode, the times are still in sync. If I leave pause mode, most of the time the cli output jumps forward around 1-5 seconds.

Effects on backward seeking:
If I seek backwards, the video will be played again much faster as opposed to forward seeking. Also the cli output and the time signature in the video appear to be in sync.

**Comment by Julusian** [comment]
It acts differently for me. The cli output doesn't match up with the current position, and pausing acts on the cli output how you would expect it to.
From what I can tell, it looks like the cli output is actually reporting on the packets being sent to the hardware decoder, not the packets being displayed on the screen.

**Comment by torarin** [comment]
Julusian is indeed describing what the code does. If you want to print the current reference clock time, call OMXMediaTime.
