### ISSUE TITLE
Enable Multichannel PCM output if system supports it.

### ISSUE THREAD

**Issue by bilditup1** [huceke/omxplayer#94]
No reason the Pi can't do this, from what I've read, and I'm sure other systems could, too. I'm assuming the changes would come in here:
https://github.com/huceke/omxplayer/blob/master/utils/PCMRemap.cpp

**Comment by srtaylor** [comment]
I need this too: using the Pi to run a dsp crossover for loudspeakers.  I have code that outputs 4- or 6-channel PCM, which I'd love to pipe to hdmi via omxplayer.  I can't find any docs that say why every software interface to the Pi's hdmi enforces down-mixing to stereo.

I've been messing with PCMRemap.cpp with no luck.  Is this doable?

**Comment by popcornmix** [comment]
Duplicate of https://github.com/popcornmix/omxplayer/issues/29
