### ISSUE TITLE
Simultaneously run two instances on verticaly oriented desktop

### ISSUE THREAD

**Issue by damagerer** [huceke/omxplayer#95]
We are developing application for RPi which uses omxplayer for video. It's like a slideshow presentation with a series of images and videos. Because of issues we've run into, we are starting another process right after we show the previous one. If there are two videos to be played one after another, we run the first one and right after the first video starts, we start another one and immediately pause it. When the first video finishes, we play the second one. Therefore there is no black screen between videos.

This works fine for horizontally oriented desktop (1920x1080) but not for the vertically oriented (display_rotate=1 => 1080x1920). First video in a row plays normally but the second video won't start. The problem seems to be with resource reservation - video overlay on rotated screen to be precise.

Is there are solution to this that we are missing or it is just a some kind of a bug?

**Comment by popcornmix** [comment]
Does giving the GPU more ram help?

**Comment by damagerer** [comment]
Yes it does, thank you! It seems like 64MB is not enough and 128MB or higher is. It now runs videos without any problem.

**Comment by ondonadas** [comment]
Hi damagerer

Please could you share with me your video resolution and compression?
In my case it doens't work with 1920x1080 videos, even with gpu mem = 320MB

BR
ondonadas

**Comment by damagerer** [comment]
Important detail is that we switched the resolution of vertically oriented videos from 1080x1920 to 720x1280, otherwise they won't play. I guess the video has to be in some kind of boundaries of horizontal dimenzions... We used profile "Main 4.1" with the 2MBs bitrate, because we wanted the video to be small and load fast.

**Comment by ondonadas** [comment]
oh! this is just my case, but I'm using only horizontal formatted videos

When I try to manage a playlist of 1080p videos it shows only a black screen
Same videos at 720p works perfect

**Comment by damagerer** [comment]
Hm, 1080p videos on horizontally oriented desktop should work fine. Maybe you have problem with screen refresh, I know we also had to go through this phase. Author describes the problem and the solution on page http://omxplayer.sconde.net/#troubleshooting, but as far as I can recall we used the solution proposed here http://www.raspberrypi.org/forums/viewtopic.php?f=27&t=27367#p300534
#/bin/bash
omxplayer "$@"
xrefresh -display :0

**Comment by ondonadas** [comment]
Thank you damagerer for the info

What a shame! it doesn't work for me... anyway I'm not using X window manager only console

I'm thinking that maybe this continuously play (playlist) feature doesn't work at all for 1080p
