### ISSUE TITLE
Image distortion at startup

### ISSUE THREAD

**Issue by julianscheel** [huceke/omxplayer#96]
When playing back live streams or captures from livestreams the image is garbled at start of playback in most cases. I guess it would help to drop incoming data until an I-Frame is seen. Would this be possible to implement with omxplayer?

**Comment by popcornmix** [comment]
change:
  concanParam.bStartWithValidFrame = OMX_FALSE;
to OMX_TRUE in OMXVideo.cpp
will do this.

**Comment by julianscheel** [comment]
This does not seem to work for h264 streams. For mpeg2 it works fine, but when playing back h264 (mpeg-ts live stream) no video output will be started at all.

**Comment by popcornmix** [comment]
Most likely the stream has no I or IDR frames. (e.g. continuous update through I blocks in P frames).
This is only supported with concanParam.bStartWithValidFrame = OMX_FALSE;

**Comment by julianscheel** [comment]
Yes, that's actually the case. But I figured out in the meantime that most of the distortions I see on startup are not actually decoder related. I am playing mpeg ts stream thorugh rtsp (udp unicast). In this case the avformat_find_stream_info will decide to hook up a software h264 decoder to retrieve stream resolution, fps, etc. as ffmpeg seems not to have a standalone h264 parser which would just extract these information from sps/pps. So when the h264 decoder starts up and tries to decode some 1080i frames the system load raises dramatically and the raspi starts to drop network packets. Finally when the analysis is done, the hardware decoder is fed with the data received from the beginning, so after the first few packets a lot dropped packets are following. This obviously causes the decoder to show lots of artefacts.
I am actually wondering what information we need from avformat_find_stream_info. Afaik the decoders don't need much input beforehands, do they? The biggest issue seems to be the detection of audio tracks, etc.
Any brainstorming on options to avoid the software decode at startup?

**Comment by popcornmix** [comment]
I would investigate this:

```
    m_pFormatContext->max_analyze_duration = 500000;
```

on OMXReader.cpp.

**Comment by julianscheel** [comment]
I'm aware of that one, but simply reducing that time does not work out well for MPEG TS as it will quite often fail to detect the tracks at all. I have a pretty hacked ffmpeg version here, which reduces the analyze time, but it's really hackish and not completely reliable as well. IMHO the whole concept of preparsing like it's done with find_stream_info is not very well suited for MPEG TS.

Besides this: Any chance that streams without I/IDR frames could be supported with concanParam.bStartWithValidFrame? If I recall correctly there is one field describing the amount of frames needed to completely rendering the first frame for such streams? (In case of h264)

**Comment by popcornmix** [comment]
I've bumped the original bug report (recovery point SEI messages are not supported).
If that were supported we could enable bStartWithValidFrame without getting no output on some streams.

**Comment by julianscheel** [comment]
Any updates on this bug?

**Comment by popcornmix** [comment]
Unfortunately not. It's not considered high priority by codec team.

**Comment by julianscheel** [comment]
@popcornmix Just wanted to bug a little and see if the priority has maybe raised a little? ;)

**Comment by popcornmix** [comment]
Sorry no. I prod them regularly, but they are no considering it a bug, and proper SEI parsing support is low priority.

**Comment by julianscheel** [comment]
@popcornmix Any news here? Any chance to raise the priority?

**Comment by popcornmix** [comment]
No news I'm afraid.

**Comment by julianscheel** [comment]
Shouldn't it be as simple as handling the recovery point sei messages? Which basically consist of one relevant field which is recovery_frame_cnt? And can be handled pretty simple, as one can see in the ffmpeg code: http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavcodec/h264.c;h=dd70af32e1b4f6c105aa190f6dab1055ee566408;hb=HEAD#l1573

Actually I implemented it in the h264_packetizer we use in vlc, but it seems the actual decoder is a bit behind, so the frame I accept as first recovery point in the code does not seem to be it. If I wait for the second recovery point it seems to be ok. I will do some more testing.
But obviously it would be way cleaner to have it in the decoder.

**Comment by popcornmix** [comment]
Please try the latest firmware update.
That includes SEI parsing and should allow concanParam.bStartWithValidFrame = OMX_TRUE to work without breaking streams with recover points and no IDR messages.

**Comment by julianscheel** [comment]
Thank you, I have just tested this via mmal and it works fine so far. I will do some more testing and close bug if nothing spurious comes up.
