### ISSUE TITLE
Streaming OTA Content via OMXPlayer not working (black screen)

### ISSUE THREAD

**Issue by polini** [huceke/omxplayer#98]
A bunch of people have problems watching ota content via omxplayer (used in XBMC). They always get a black screen instead of the stream (this isn't a MPEG2 licensing problem).

It's a MPEG2 (TS-)Stream transported over a so called HTSP protocoll.

The software used is XBMC and TVHeadEnd as Live-TV Streaming Server

Please refer to the following threads/issues:
http://forum.xbmc.org/showthread.php?tid=148646
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=35&t=23243
OpenELEC/OpenELEC.tv#1356
http://trac.xbmc.org/ticket/13783
https://github.com/raspberrypi/firmware/issues/137

**Comment by MartinAyla** [comment]
I have this problem too, it happens with all the latest XBMC nightlies. Recordings made with Tvheadend can play back just fine, it's only the Live TV streaming that doesn't work (results in black screen). Sometimes, starting and stopping playback, several times, will result in the stream playing, but it's very random.

**Comment by popcornmix** [comment]
This github repo is for command line omxplayer, not the omxplayer in xbmc.
This would be a better place for bug reports:
http://trac.xbmc.org/ticket/13783
